### ISSUE TITLE
Edge label is not positioned in the middle of the edge

### ISSUE THREAD

**Issue by DmitriyPogorelov** [almende/vis#768] opened 2015-04-08 15:45 UTC
Hi,

I`m using hierarchical layout in direction mode. My nodes are all SVGs. The problem is that labels on edges are displayed not in the middle of the edge, but rather close to the "from" node.

![image](https://cloud.githubusercontent.com/assets/11856253/7048995/9713a8cc-de16-11e4-8236-575cf0ca0e19.png)

Here is my options object:
var options = {
          keyboard: true,
          stabilize: true,
          dragNodes: false,
          hierarchicalLayout: {
            levelSeparation: 300,
            direction: "UD",
            layout: "direction"
          },
          edges: {
            style: "line",
            fontSize: 50
          },
          physics: {
            hierarchicalRepulsion: {
              centralGravity: 0.5,
              springLength: 150,
              springConstant: 0.01,
              nodeDistance: 900,
              damping: 0.09
            }
          }
        };

SVG`s sizes are: width="460", height="85".

**Comment by josdejong** [comment] 2015-04-09 08:31
Are you sure this is the label of an *edge* and not the label of the top node in your image?

Labels seems to be positioned fine in examples like http://visjs.org/examples/network/35_label_stroke.html

**Comment by AlexDM0** [comment] 2015-04-09 08:47
The cause here is the smooth curves in a hierarchical layout. Try settings smoothCurves:false to correctly position the labels. I'll see if I can make a cleaner fix for this in 4.0.

Regards,

Alex

**Comment by DmitriyPogorelov** [comment] 2015-04-13 14:54
Alex, your suggestion to use smoothCurves:false helped. Thanks for help!

**Comment by AlexDM0** [comment] 2015-04-13 15:02
Glad to hear it helped! Im not sure if I'm going to fix the original issue in 4.0 though. The smooth curves are described by a mathematical equation with a variable differential so if I fill in t =0.5 (half way) I don't always get the geometrical mid-point. The alternative is much more computationally expensive so it might stay this way.

**Closed** 2015-04-22 14:45 UTC
Labels: Network, wontfix
