### ISSUE TITLE
Error when using date before Christ

### ISSUE THREAD

**Issue by lucianopes** [almende/vis#1552] opened 2016-01-07 11:24 UTC
Hi,
I am new using VisJs but i think is an exceptional project, compliments.
I have a question about  using  a date before christ (for example -4000). In this case  the libray falls or have problems in visualisations. 
Using  the basicusage.html example  if you insert 
var items = new vis.DataSet([
 {id: '1', content: 'item 1', start: '-4000'},
)]
this is handled not like 4000 before crist but 4000 after christ.
Perhaps i am wrong in something:
is the correct way to indicate -4000 or we have to use another syntax.
thanks in advance and more compliments
Luciano

**Comment by AlexDM0** [comment] 2016-01-07 13:47
Maybe like this? Date(-4000,10,1,0,0,0)

**Comment by josdejong** [comment] 2016-01-07 13:47
I think this is a duplicate of #307

**Comment by lucianopes** [comment] 2016-01-07 20:06
Yes, correct is a duplicate of the #307. Thanks josdejong and AlexDM0

**Comment by josdejong** [comment] 2016-01-08 08:09
You're welcome

**Closed by josdejong** 2016-01-08 08:09 UTC
Labels: duplicate, Timeline
