### ISSUE TITLE
First view today and select year & month

### ISSUE THREAD

**Issue by cerensimsek1984** [almende/vis#3666] opened 2017-11-17 12:53 UTC
Hello,

When I run the project, I want to see  the week with the today in the center..  How can i code it ? 
and 
i can choose year with a selectbox and later going current year in timeline.. so but how can i go current year and current month ? with two selectbox.. 

thanks

**Comment by yotamberk** [comment] 2017-11-18 21:41
first question: 
have you tried options including a `start` and `end` equal to `new Date()` minus/plus 3.5 days?
second question:
I dont fully understand the question... 
I think `timeline.setWindow()` is what you're looking for. see docs:  http://visjs.org/docs/timeline/#Methods

**Comment by marcortw** [comment] 2017-11-20 20:09
First question: I think `timeline.moveTo(new Date())` was designed exactly for that.

**Comment by cerensimsek1984** [comment] 2017-11-22 07:12
thanks for help guys.. 
1. ques:  i mean first opening i want to see "only today" like this 

![untitled-1](https://user-images.githubusercontent.com/26116669/33113568-0c9cf25a-cf6a-11e7-8625-8c42c978e47b.jpg)

2. ques:  choose year and month ... I want to go to the month of the selected year :)

![untitled-2](https://user-images.githubusercontent.com/26116669/33114364-991a7e70-cf6d-11e7-88f0-9f1c07e7390f.jpg)

Pls check the jsfiddle https://jsfiddle.net/hc83Lpfw/3/

**Comment by brichbe** [comment] 2017-11-22 13:21
Like I mentioned earlier in #3027, your questions seem to be about using the `Timeline.setWindow()` method and learning how to use [moment.js](https://momentjs.com/).  A few of the [Timeline Examples](http://visjs.org/timeline_examples.html) use moment.js such as the [Time Zone example](http://visjs.org/examples/timeline/other/timezone.html).

So for 1) you'd create a moment object that represents the start of today, then create a second moment that's the same date but it's time is 11:59:59 PM, then use those two moment objects to pass into the setWindow() method (the docs say you must pass in a Date, Number or String, which you can get from the moment).

For 2) again, it's a matter of figuring out how to use moment.js so you can take the user's chosen year, plus the user's chosen month, set those into a moment object to be your start, then figure out what's the last day of that month to be your end, and then call Timeline.setWindow().

Also, just my opinion but having separate choosers for year/month is not the best user interface, because the user should choose both things at once.  You might want to try something like [this](https://stackoverflow.com/questions/2208480/jquery-ui-datepicker-to-show-month-year-only).

**Comment by cerensimsek1984** [comment] 2017-11-22 13:33
yes thank you !  I have to go a little further.. I am trying to improve..  
https://jsfiddle.net/hc83Lpfw/5/ 
"Also, just my opinion but having separate choosers for year/month is not the best user interface, because the user should choose both things at once. You might want to try something like this." 
you right..  like datepicker?  it will be hard :D thnk u

**Comment by cerensimsek1984** [comment] 2017-12-15 15:12
hello again @brichbe  https://jsfiddle.net/hc83Lpfw/6/ 
when i go to selected day from datepicker, can i see different angle ? for exp. 
how can i change the setwindow as per moveTo Id ? (zoom in / zoom out )

timeline.moveTo(id);
timeline.setWindow(startDate, endDate);

I tried every way, i can t find :(

**Comment by brichbe** [comment] 2017-12-15 16:45
Are you asking for something like [this](https://jsfiddle.net/hc83Lpfw/8/)?  I've changed your example so that when a date is selected from the chooser, the timeline window is set to the start/end of that day.

**Comment by cerensimsek1984** [comment] 2017-12-15 17:29
oh yes very good thank you, a bit confused..  
      var dayStart = moment(dateString).subtract(3, 'days');
      var dayEnd = moment(dayStart).add(6, 'days');
and i think it makes centered view..

**Comment by brichbe** [comment] 2017-12-15 17:47
Yeah, that works too, if you prefer to add a 3 day buffer on each side of the user's chosen date.  Please close this issue if your questions have been addressed.

**Closed** 2017-12-15 18:29 UTC
Labels: Question, Timeline
