### ISSUE TITLE
Timeline displayed in UTC

### ISSUE THREAD

**Issue by daniel-pfeiffer** [almende/vis#1096] opened 2015-07-16 11:20 UTC
If I add items with ISO UTC start and end (i.e. a T between date and time) they get picked up correctly.  However, since my PC is running in European summer time (UTC+2) they are displayed off by 2 hours which is startling.
In order for all users of my timeline to have the same view, it would be great to have an option to display labels and current time in UTC.
I have looked at moment.js, and it looks like everything needed is there, but I'm not sure of all the places where this would be plugged into vis.js.  Likely all places where you call `moment(...)` need to be changed to optionally call `moment.utc(...)`.  Or else, after that, you optionally call `result.utc()`.

**Comment by Fice** [comment] 2015-07-16 18:09
I've just made a PR that would address that issue: #1098. This allows yout to pass a custom function as the format option. Displaying UTC was exactly my use case (as well as a 'x days ago' label on another timeline instance).

**Comment by daniel-pfeiffer** [comment] 2015-07-21 10:33
Thanks!  But I think that would not get it quite right.  It's not enough to modify the labels.  The lines separating days would need to move accordingly.

**Comment by josdejong** [comment] 2015-07-21 13:21
Duplicate of #24. 

Support for time zones will be available in the first next release (see https://github.com/almende/vis/issues/24#issuecomment-123301866).

**Closed by josdejong** 2015-07-21 13:21 UTC
Labels: duplicate, Timeline

**Comment by daniel-pfeiffer** [comment] 2015-07-29 18:10
Upgraded to 4.7.0 and the new option moment looks like it's working great.  Thumbs up to Almende!

**Comment by josdejong** [comment] 2015-07-29 19:49
Thanks :)
