### ISSUE TITLE
Endless Loop in Network if maxWdt < word

### ISSUE THREAD

**Issue by mojoaxel** [almende/vis#2953] opened 2017-04-06 07:55 UTC
From https://github.com/almende/vis/commit/8a9edbbf8750c7527e8e30bf8e11281cf0e0e975#commitcomment-21618963
> Hi @eymiha and @mojoaxel,
>
>Just a quick heads-up: this commit goes into an unlimited loop when maxWdt < word length. Basically the >loop in: lib/network/modules/components/shared/Label.js#828 has no progress if 'w' is not incremented, >which happens if line 832 is true.
>See: http://jsfiddle.net/ce92dhtx/72/ (if you uncomment the widthConstraint{ maximum} field it will go into >an unlimited loop)
>
>I'll be able to create a fix later this week, but if one of you guys could fix it, even better.
>
>Kind Regards,
>Ludo..

**Comment by wimrijnders** [comment] 2017-07-16 14:16
Duplicate of #3171.
Fixed by #3228.

**Closed by wimrijnders** 2017-07-16 14:16 UTC
Labels: Confirmed Bug, Network, PRIORITY
