### ISSUE TITLE
Network: Getting weird error

### ISSUE THREAD

**Issue by dragonzone** [almende/vis#1308] opened 2015-09-17 15:42 UTC
See screenshoot below. This only happens in rare cases, which I cannot trace. Can you see what is happening?

![vis-js-error](https://cloud.githubusercontent.com/assets/10065158/9937996/2e81b700-5d31-11e5-8df8-f95d6334d8f0.png)

**Comment by AlexDM0** [comment] 2015-09-17 15:45
There's something off about the kamada kawai algorithm appearently. When this happens, can you do network.getSeed() to get the random seed. You can then use that with layout:{randomSeed: seed}

There is something appearently dependent on the initial layout... It sounds very strange though. I'd be happy to look into it if you can reproduce it.

**Comment by dragonzone** [comment] 2015-09-17 15:49
On initial load, I set an arbitrary randomSeed = 2. What you are saying is that I cannot just assign a value of "2", but use network.getSeed() to set that randomSeed instead?

Below is the result of the error.

![vis-js-error2](https://cloud.githubusercontent.com/assets/10065158/9938110/cfa5e872-5d31-11e5-9517-a75d6fe3dbfb.png)

**Comment by AlexDM0** [comment] 2015-09-17 15:51
Hi, 

You can definately set a value of 2. I thought since you cannot reproduce it, it would be due to the random initialization.

It could be due to self-referenceing edges but now I'm just guessing... 

Having something to reproduce this would go a long way to solving it. In your case, just do layout:{improvedLayout:false} to avoid it for now.

Regards

**Comment by dragonzone** [comment] 2015-09-17 16:57
Yes, setting layout:{improvedLayout:false} works on initial load. After the initial load, I set that value back to true, which works fine from then onward (*so far*). Is this something you can fix? Or you will need further detail in order to fix it?

**Comment by dragonzone** [comment] 2015-09-17 17:31
Hmm, what's also weird is, once loaded w/ the error, if I change to a hierarchy layout, then it'll work fine. Then, if I change back to default. It'll come back.

**Comment by dragonzone** [comment] 2015-09-17 19:17
I'm able to reproduce the problem after vetting our data, so here is it:

http://jsfiddle.net/et89rypm/

**Comment by AlexDM0** [comment] 2015-09-17 19:42
Hi Dragon,

The cause is that you have an edge that is not connected, ie. either the toId or the fromId does not exist.

I've pushed a fix to develop!

Cheers

**Comment by dragonzone** [comment] 2015-09-18 13:28
I disagree, I just put a test to see if all the edges "from" and "to" point to an existing nodes and it all did. I think something else is going on here. Here is the code:

```
http://jsfiddle.net/et89rypm/1/
```

**Comment by AlexDM0** [comment] 2015-09-18 14:09
You're right. Turns out it was the clustering system not handling self-referencing nodes correctly. It's fixed now on develop!

Even though it was not the case in your example, unconnected edges should have been checked for nonetheless. 

Thanks for checking!

**Comment by dragonzone** [comment] 2015-09-30 18:55
Can I get an idea when we'll have another release? We have a production release coming soon, which I hope will have this in it. Thx.

**Comment by AlexDM0** [comment] 2015-09-30 19:32
Hi,

Ill have to refer to @josdejong for this as I'll be on holiday soon. 

Regards

**Comment by josdejong** [comment] 2015-09-30 20:01
I will do a release this week, no problem.

**Comment by AlexDM0** [comment] 2015-10-01 12:22
Released in v4.9.0

**Closed by AlexDM0** 2015-10-01 12:22 UTC
Labels: bug, Fixed awaiting release, Network
