### ISSUE TITLE
Edges with same from and to got combined to one

### ISSUE THREAD

**Issue by upbeat21** [almende/vis#2675] opened 2017-02-04 01:13 UTC
Hi, I have couple of edges shared same "from" and "to" value. And when the vis.js render, it'll combine them to only one edge. I have different labels for these edges and I want to separate them into different edges. I have tried to put different ids to these edges but it does not work. Hope someone can help me please.

**Comment by mojoaxel** [comment] 2017-02-05 18:23
duplicate of #1957

**Closed by mojoaxel** 2017-02-05 18:23 UTC
Labels: Duplicate, Network, Problem
