### ISSUE TITLE
vis.js and materialize-css : Hammer.assign is not a function

### ISSUE THREAD

**Issue by yume117** [almende/vis#3661] opened 2017-11-16 10:52 UTC
I'm trying to run vis.js in an Angular4 project configured with Angular-cli that is already using Materialize-css

When running the angular application I get this error in console : 

```
    Uncaught TypeError: Hammer.assign is not a function
    at propagating (vis.js:37731)
    at Object.<anonymous> (vis.js:1915)
    at __webpack_require__ (vis.js:57)
    at Object.<anonymous> (vis.js:34498)
    at __webpack_require__ (vis.js:57)
    at Object.<anonymous> (vis.js:28975)
    at __webpack_require__ (vis.js:57)
    at exports.__esModule (vis.js:100)
    at vis.js:103
    at webpackUniversalModuleDefinition (vis.js:30)
```

In package.json : 

    "vis": "4.21.0",
    "jquery": "^2.2.4",
    "hammerjs": "^2.0.8",
    "materialize-css": "^0.100.2",
    "angular2-materialize": "^15.1.10",
    "typescript": "~2.3.3"
    "zone.js": "^0.8.14"

In angular-cli.json

    "styles": [
            "../node_modules/materialize-css/dist/css/materialize.css",
            "../node_modules/vis/dist/vis.min.css",
            "assets/scss/main.scss"
          ],
          "scripts": [
            "../node_modules/jquery/dist/jquery.js",
            "../node_modules/hammerjs/hammer.js",
            "../node_modules/materialize-css/dist/js/materialize.js",
            "../node_modules/vis/dist/vis.min.js"
          ],

I check that **hammerjs**, **jquery**, **vis** and **materialize** and correctly installed and present in `/node_modules` directory

**hammerjs**, **jquery** and **materialize** were already installed and working in the project. Which is a simple web site.

---

**Any idea what could lead to this error and how to correct it ?**

**Comment by yotamberk** [comment] 2017-11-16 18:44
It doesn't seem like the problem is in vis.js. Does the error specify where the problematic code is?

**Comment by yume117** [comment] 2017-11-16 19:37
I updated the error log it's from vis.js a line with `Hammer.assign()`

Assign() is not recognized

**Comment by yotamberk** [comment] 2017-11-16 19:50
Is it because vis uses a more updated version of Hammer?

**Comment by yume117** [comment] 2017-11-17 09:19
Materialize and vis.js both use Hamerjs 2.0.8, I check the package-lock.json

**Comment by ArtificialInsights** [comment] 2018-01-04 22:31
Has anyone been able to solve this? I am wanting to use vis.js but I am having the same issue... I use Materialize, and this is causing the issue...

Anyone come up with a fix?

**Comment by yotamberk** [comment] 2018-01-06 21:43
This is a duplicate of #2000. Please see references there and continue discussion there

**Closed by yotamberk** 2018-01-06 21:43 UTC
Labels: Question, source/non-public API

**Comment by ArtificialInsights** [comment] 2018-01-07 01:02
This appears to be a duplicate issue, but both are closed threads and no one has answered the question. Only a duct-tape answer of including VIS before Materialize... however, I tried this and still get error. It seems someone said I could load the CDN in the index file, but even doing this, I am getting an error. 

How to reproduce the error? Create and Angular project, install Materialize and Angular2materialize and then install VIS. So, if there is a way to get this to work, can someone provide the fix... in either this thread or one that has not been closed?

**Comment by yotamberk** [comment] 2018-01-07 06:21
I've reopened the other issue to continue the thread there
