### ISSUE TITLE
[Question] - Export data after manipulation

### ISSUE THREAD

**Issue by derfericb** [almende/vis#1490] opened 2015-12-04 16:12 UTC
Hello,

Sorry for my newbie question but, is it possible to export the data of a graph (in JS format, as in the example file "worlcup2014.js") once modified through the manipulation tools proposed (add nodes, ...) ?

Regards.

**Comment by AlexDM0** [comment] 2015-12-09 14:33
All manipulation tools update the data in the dataset. You just use the vis.DataSet and get() the data back from it.

Regards

**Comment by derfericb** [comment] 2017-02-14 10:09
Hello,

I know this post is very old but the answer does not fit to my question.
Once I modified tha node in the network graph, I would like this modification be reported in my JS file (on my hard drive).

**Comment by wimrijnders** [comment] 2017-05-08 07:44
@derfericb From what I understand, you want a method to store network data once it has changed. The following is my suggestion.

This sets up event callbacks to detect changes in the data, and then retrieves all current node and edge data in an object which can be converted to JSON.
There is no save to file here because that is outside the scope of `vis.js network` and, to be honest, I currently wouldn't know how to do that.

I hope this helps.

```
var data;

function getExport() {
  var out_data = {
    nodes: data.nodes.get(),
    edges: data.edges.get()
  };

  // Optional: retrieve node positioning data and add to output
  var positions = network.getPositions();
  out_data.nodes.forEach(function(item, index, array) {
    var pos = positions[item.id];
    if (pos !== undefined) {
      array[index].x = pos.x;
      array[index].y = pos.y;
    }
  });

  console.log(out_data);
  // Save your data to file here
}

function draw() {
  data = {
    nodes: new vis.DataSet(in_data.nodes),
    edges: new vis.DataSet(in_data.edges),
  }

  //
  // Catch the change events.
  // These are called before data has changed, so a delayed call is 
  // set up with setTimeout() to retrieve the data after current
  // loop has completed.
  //
  data.nodes.on('*', function(event, properties, senderId) {
    console.log('Nodes changed');
    setTimeout(getExport,0);
  });

  data.edges.on('*', function(event, properties, senderId) {
    console.log('edges changed');
    setTimeout(getExport,0);
  });
...
  // Further regular initialization here
}
```

**Comment by wimrijnders** [comment] 2017-09-28 07:58
Duplicate of #2255. Closing for that reason.

**Closed by wimrijnders** 2017-09-28 07:58 UTC
Labels: Network, Question
