### ISSUE TITLE
Network add node do not work always.

### ISSUE THREAD

**Issue by mdre** [almende/vis#2958] opened 2017-04-07 14:58 UTC
Hi! I have this trouble. If I add a node before I call the vis.Network constructor all work fine but if I add a network with icons later everything blow up.
Here my code:

```
var Network = function (contenedor) {
//var shadowState, nodes, edgesArray, edges;

    console.log("Ingresa: " + contenedor);
    this.contenedor = contenedor;
    console.log("dataset");
    // create an array with nodes
    this.nodes = new vis.DataSet([]);
    console.log("edges");

    // create an array with edges
    this.edges = new vis.DataSet([]);

    console.log("data");
    this.data = {
        nodes: this.nodes,
        edges: this.edges
    };
    
    // Test 1
//    this.nodes.add({
//        id: 5,
//        label: 'Organisation 1',
//        shape: 'icon',
//        icon: {
//          face: 'Ionicons',
//          code: '\uf47c',
//          size: 50,
//          color: '#f0a30a'
//        }
//    });
    
    this.options = {
//        configure: 'nodes,edges'
    };
    console.log("network");
    this.nk = new vis.Network(this.contenedor, this.data, this.options);

};

Network.prototype.addNode = function (nodeInfo) {
    console.log("*************** Agregando nodo *********************");
    console.log(nodeInfo);
//    var newId = (Math.random() * 1e7).toString(32);
//    var lbl = label || "Node: " + newId;
    var _node = eval("("+nodeInfo+")");
    console.log(_node);
    
    this.nodes.add(_node);
    
//    Test 2
//    this.nodes.add({
//        id: 5,
//        label: 'Organisation 1',
//        shape: 'icon',
//        icon: {
//          face: 'Ionicons',
//          code: '\uf47c',
//          size: 50,
//          color: '#f0a30a'
//        }
//    });
    
    console.log("nodes: ",this.nodes);
    console.log("*************** FIN *********************");
};
```
If you uncomment "Test 1" code, it work.

If you try to call:
```
net.addNode('{id: 5, label: \'test\'}');
```
it work fine. 
but, if you call:
```
net.addNode( {
        id: 5,
        label: 'Organisation 1',
        shape: 'icon',
        icon: {
          face: 'Ionicons',
          code: '\uf47c',
          size: 50,
          color: '#f0a30a'
        }
    });
```
or if you uncomment the "Test 2" code, it blow up!
There no trace error. The Chome only say "Oh! no!" and I need to reload the page.
I test it against Ionicons and FontAwesome. The css were correct added since "Test 1" work.
Thanks.

**Comment by wimrijnders** [comment] 2017-04-10 14:38
Hi there,

Following tested with current `develop` branch, without `ionicons`.

1. I can get `Test 1` to work, no problem.

2. The example with the call `net.addNode({id: 5, label: 'test'});` works if I make the following change:

```
Network.prototype.addNode = function (nodeInfo) {
...
    //var _node = eval("("+nodeInfo+")");
    //console.log(_node);
    //this.nodes.add(_node);
   this.nodes.add(nodeInfo);
```
To be honest, I don't understand the  `eval()` call, it's not necessary.

3. I can get `Test 2` to work by completely commenting out the handling of `_node`.

----

So, as far as I can tell, it's the handling of `_node` that causes an issue. Did you test `Test 2` without those lines?
It's always possible it has something to do with `ionicons`. I'll see if I can test for that.

**Comment by mdre** [comment] 2017-04-10 15:18
Hi!
I'am working in make a wrapper to the vis.js to use it from Java + Vaadin Framework. The eval() is used because the call is originated in Java side as a String and I need  to transform it again to Javascript Object.
Really I can not understand why is not working in some case and in other works.

**Comment by wimrijnders** [comment] 2017-04-11 06:39
> Really I can not understand why is not working in some case and in other works.

Ah, right. So it works sometimes. Are you getting any error messages when it does not work? If so, please share.

If not, you might be experiencing the _infinite loop problem_, as reported in #2953. If you have a moment, can you try out the example jsfiddle link there and tell if that is the same that is happening with your code?

**Comment by wimrijnders** [comment] 2017-04-11 08:32
> net.addNode('{id: 5, label: 'test'}');

The outer quotes should be double, I think.

>     var _node = eval("("+nodeInfo+")");

Why not use `JSON.parse()` here? It's safer and should be faster. But then the `nodeInfo` contents must be legal JSON, of course.

**Comment by mdre** [comment] 2017-04-11 16:05
Yes! Yes! Yes! That is the error!! 
As it is reported in #2953, if you set the widthConstraint.maximum, in some case, it start a endless loop. 
I set it in the setOptions call. 
Now I have commented out the "maximum" clause generator and everything work!
Thank's!

**Comment by wimrijnders** [comment] 2017-04-11 17:28
:laughing:  I must say your hapiness is contagious!

OK, happy that you found a solution for your needs. Also good to know that someone else is working on fixing it. I will report this issue as a duplicate.

**Comment by wimrijnders** [comment] 2017-04-11 17:28
Duplicate of #2953.

**Closed** 2017-04-11 17:31 UTC
Labels: Network, Problem
