### ISSUE TITLE
Dynamic vs. other edges

### ISSUE THREAD

**Issue by sklarman** [almende/vis#1398] opened 2015-10-27 14:14 UTC
Hi,

First of all - thanks for making available this fantastic package!

I'm developing a simple graph browser, which dynamically adds nodes and edges, and I'm looking for some reasonable compromise between using dynamic and other types of (smooth) edges. 

With the other types, if I understand correctly, I cannot obtain non-overlapping edges between the same nodes. So for instance with this setup:

 "edges": {arrows:'to',
  "smooth": {"type": 'continuous'}}

I'm getting overlapping edges, e.g. domain & range edges between bindsTo and BindingFeature: 

<img width="350" alt="overlap" src="https://cloud.githubusercontent.com/assets/12385097/10760342/0e36f1ca-7cb4-11e5-8cac-f1726707a086.png">

The dynamic edges, as in:

 "edges": {arrows:'to',
 "smooth": {"type": 'dynamic'}}

solve the problem of overlapping, but instead they are quite wild when adding new nodes and edges to the network. At the first moment they are "pulled" heavily towards the center of the network dragging the nodes behind them and making the entire process visually very chaotic, as e.g. in here:

<img width="352" alt="dynamicedges" src="https://cloud.githubusercontent.com/assets/12385097/10760411/59b99ac6-7cb4-11e5-981c-5e2cdcf1b2c3.png">

Would you be able to suggest some pragmatic strategy of resolving this trade-off? 

All Best,
Szymon

**Comment by josdejong** [comment] 2015-10-30 10:26
Thanks for reporting this, looks weird. Not sure, but it could be related to #1342 and/or #1351.

**Comment by josdejong** [comment] 2015-10-30 10:27
A pragmatic solution could be to dedupe your duplicate labels yourself, and merge their two labels into a single edge.

**Comment by sklarman** [comment] 2015-10-30 11:05
Yes, this does look as an issue related to https://github.com/almende/vis/issues/1351. It probably is the effect that gravity has on dynamic edges... 

As for your suggested solution - right, that's what I was thinking of as well, although the clear downside is that I won't be always able to associate different edge styles with different labels, which is quite an essential requirement in my scenario.

Thanks, Jos!

**Comment by AlexDM0** [comment] 2015-11-02 09:54
Hi,

Could you make a JSBin to show this? I'm having trouble reproducing this.

Regards,

Alex

**Comment by sklarman** [comment] 2015-11-02 12:40
Hi Alex,

I assume you mean the effect related to the use of dynamic edges. Here's the link: https://jsbin.com/wohejocoji/edit?html,output. You can expand the network by double-clicking on nodes. The bigger the network is and the farther from the center you expand it the more visible the effect becomes. 

All Best,
Szymon

**Comment by AlexDM0** [comment] 2015-11-02 14:30
Hi,

Thanks! I've pushed a fix for this to develop.

Cheers

**Comment by sklarman** [comment] 2015-11-02 14:41
Great, thanks! Is there also any chance that the problem of overlapping non-dynamic edges is going to be resolved any time in the coming future?

**Comment by AlexDM0** [comment] 2015-11-02 14:46
No, I'm not sure how you figure that would work? What controls would we have to solve overlap? Brute forcing and collision detection?

**Comment by sklarman** [comment] 2015-11-02 14:52
Sure, sorry, I obviously don't understand the technicalities behind this. It just feels like an intuitive feature to ask for, particularly that you can already have 2 non-overlapping non-dynamic edges between the same nodes (provided they go into opposite directions), then why not 3 or more? But clearly, as you say, there must be some good reasons for why it is not possible. 

All Best,
Szymon

**Comment by AlexDM0** [comment] 2015-11-02 15:07
Hi,

The dynamic edges are the solution for this, there is no other way that is computationally not expensive, to do this.

Regards

**Comment by sklarman** [comment] 2015-11-02 15:09
Ok, I see. Thanks again! 

Al Best,
Szymon

**Comment by sklarman** [comment] 2015-11-02 17:28
Hi Axel,

One last idea on this issue :) Perhaps I'm reinventing the wheel, but one potentially pragmatic solution could be to automatically diversify (and adjust) roundness of non-dynamic edges in case there is more than one between the same nodes. In the following example I just randomize roundness, but this could be obviously done more intelligently: https://jsbin.com/falegeleka/edit?html,output. If only the maximum available curvature of edges was greater, I think this could look and behave rather well. 

All Best,
Szymon

**Comment by AlexDM0** [comment] 2015-11-02 17:47
It's an interesting idea!

Should it be on by default? How do you keep edges readable? Should you loop over the edges to avoid randomness? Should it be configurable?

If you want you can solve these problems and do a pull req for this option? We always welcome contributions!

Cheers

**Comment by sklarman** [comment] 2015-11-02 18:36
I'd love to contribute to this project, but I'm honestly just making my first baby steps in the programming world, so I'm afraid this could be a little too challenging for the moment :)

As for your questions, I believe that a good solution (at least from the perspective of my use case) would fix this mechanism to be on by default and dependent exclusively on the number of edges between two given nodes in the network - this number should be used to determine the (unique and uniformly distributed) values of roundness/curvature for all the edges (thus no randomness). I don't think there should be a need for parametrizing this additionally - the mechanism could just override (or perhaps amplify) the original roundness setting provided by the user. The readability of the edges should come pretty much for free if the curvatures are properly harmonized. 

...or at least that's what I would imagine - for now, it's just my uneducated idea :)

Cheers,
Szymon

**Closed** 2015-11-27 15:37 UTC
Labels: bug, Fixed awaiting release, Network
