### ISSUE TITLE
Node drawn on top of circuit when using hierarchical layout. Gives misleading circuit paths.

### ISSUE THREAD

**Issue by ghost** [almende/vis#2311] opened 2016-11-14 03:41 UTC
When using version 3.12.0, I do not have this problem. However, when using version 4.0.0 or higher, a node will overlap onto a circuit path and give the impression that the circuit is going to that overlapping node. See attached screenshots. This first screenshot is when hierarchical layout is set to false.
![newlibhierarchical](https://cloud.githubusercontent.com/assets/19678058/20252165/88e8018e-a9e5-11e6-9786-afe88a56d81c.JPG)

This second screenshot is what happens when the hierarchical layout is set to true.
![newlibhierarchical_1](https://cloud.githubusercontent.com/assets/19678058/20252164/88e78bc8-a9e5-11e6-8616-95ccb6c5b643.JPG)

As you can see, the second and third nodes have edges pointing to each other. But when in hierarchical mode, the third node is drawn to the left of the second node. Also, the edges pointing between the second and third nodes are overlapping each other, which in this case, means that there are three edges overlapping each other.

The latest version that does not appear to have this problem is 3.12.0. After that, the issue exists.
Here is my setup below:

```js
var nodes = new vis.DataSet([
{id: 1, label: 'First'},
{id: 2, label: 'Second'},
{id: 3, label: 'Third'},
{id: 4, label: 'Fourth'},
{id: 5, label: 'Fifth'}
]);

var edges = new vis.DataSet([
{from: 1, to: 2},
{from: 2, to: 3},
{from: 3, to: 2},
{from: 2, to: 4},
{from: 4, to: 5}
]);

var container = document.getElementById("network-area");
var data = {
	nodes: nodes,
  edges: edges
};

var options = {
autoResize: true,
edges:{
arrows: 'to'
},
interaction:{
dragNodes: false
},
layout:{
improvedLayout: true,
hierarchical:{
enabled: true,
direction: 'LR',
sortMethod: 'directed'
}
}
};

var network = new vis.Network(container, data, options);
```

Here is a JSFiddle to see it in action - [LINK](https://jsfiddle.net/redcameron/dwzd6znq/3/)

**Comment by mojoaxel** [comment] 2016-12-06 12:15
@redcameron I see the problem, but how would you expect the graph to look in a hierarchical layout?

**Comment by redcameron** [comment] 2016-12-06 16:02
I would expect that the graph would not allow the edges to overlap or for a node to overlap an edge in this small graph because in this situation, a user would only be able to select one edge rather than the other two edges between nodes 'Second' and 'Third'.  This would be very inconvenient for the user who would need to select either edge.  

This issue gives the false impression that the edge between the 'Second' and 'Third' nodes is a two-way or two-directional connection, which is incorrect. It also gives the false impression that node 'Third' comes before node 'Second', which is also incorrect. 

Ideally, I would think that in this situation in a hierarchical layout, the 'Third' node should be displayed above or below the 'Second' node with both edges from 'Second' to 'Third' and 'Third' to 'Second' visible for the user to view and select.

**Comment by wimrijnders** [comment] 2017-04-30 10:02
Confirmed. There are two issues here:

- Multiple edges between two nodes overlap for hierarchical networks: Duplicate of #1957.
- Nodes render on top of edges.

For the second issue, I have tracked the problem to clouse `levelByDirection` in `LayoutEngine._determineLevelsDirected()`. This code has trouble dealing with bidirectional edges.
By forcing the levels assignment to increment only, the layout for the given network can be fixed:

![download](https://cloud.githubusercontent.com/assets/769037/25563425/80d2f5b8-2d9c-11e7-9ce6-0795e7491c16.png)

However, I'm not convinced yet  that this solution is general enough for all hierarchical networks.. I need to test more before submitting a PR.

**Comment by theredcameron** [comment] 2017-09-19 21:19
OP here. Thank you so much for the fix!!
Any idea what version this fix will be included in and when that version will be released?

**Comment by theredcameron** [comment] 2017-10-05 21:22
I've applied the changes to a test instance and I can confirm that the real issue has not been fixed according to my original description. I will attempt to resolve this issue.

**Comment by wimrijnders** [comment] 2017-10-06 04:30
@theredcameron Thanks in advance for your effort! Please regard me as standing by for assistance.

**Closed** 2017-10-12 13:23 UTC
Labels: Confirmed Bug, Fixed awaiting release, Network

**Comment by theredcameron** [comment] 2018-02-26 23:42
Sorry about the wait. I'll continue work on this soon.
