### ISSUE TITLE
IE flicker

### ISSUE THREAD

**Issue by kundusandeepan** [almende/vis#922] opened 2015-06-03 18:21 UTC
Internet explorer (ie11), the network flickers.
VisJs @version 4.1.0

**Comment by AlexDM0** [comment] 2015-06-03 18:23
Hi,

Yes, this is a duplicate of #912. It is caused by highDPI settings and is fixed on the develop branch. It will be released Friday. 

Regards,

Alex

**Closed** 2015-06-05 08:48 UTC
Labels: bug, duplicate, Fixed awaiting release, Network
