### ISSUE TITLE
Timeline - vis-minor ticks are sometimes not generated on DST days

### ISSUE THREAD

**Issue by logscl** [almende/vis#2444] opened 2016-12-13 10:16 UTC
Hello,

We are facing an issue with the Timeline component of VisJs. When we render the events of a day that contains a daylight saving time switch (in this case, from summer time to winter time), the minor ticks are not generated.

Here is a fiddle that shows the error: https://jsfiddle.net/md2sdes2/1/

The first timeline has only the first tick (00h), while the second timeline (that displays the day before) is correct.
If you zoom in multiple times in the timeline, the ticks will appear. But the problem will eventually reoccur when you pan the timeline.

Please note that this issue seems to occur only when the timeline is less than ~1200px in width. It occurs every time when the timeline is fully zoomed and panned.

We reproduced this problem with the 1.16.1 and 1.17.0 versions of VisJS.

Is there something in the configuration we missed or is it a bug ?

Thank you very much.

Logan

**Comment by yotamberk** [comment] 2016-12-13 11:44
@josdejong I think the PR you posted (#2290). It seems like something is still going wrong. Can you please take a look at it?

**Comment by josdejong** [comment] 2016-12-15 19:55
I think that fix isn't yet released? Scheduled for v4.18.0?

**Comment by mojoaxel** [comment] 2016-12-16 08:00
> I think that fix isn't yet released? Scheduled for v4.18.0?

Not released yet. See https://github.com/almende/vis/milestone/3 for the planed release date.

**Comment by yotamberk** [comment] 2016-12-16 19:26
duplicate of #2251

**Closed by yotamberk** 2016-12-16 19:26 UTC
Labels: Duplicate, Fixed awaiting release, Problem, Timeline
