### ISSUE TITLE
[Network] GUI Manipulation, node level doesn't update visually

### ISSUE THREAD

**Issue by cridus** [almende/vis#3220] opened 2017-06-30 15:21 UTC
I have a Network with a hierarchical tree. I added the GUI buttons to add and edit the nodes, however when I edit a node and I change its level, the node doesn't move to that level, visually. As a workaround I call `network.clustering.updateClusteredNode(data.id, {level : theNewLevel});` after the callback to update the node and that does make the node appear in its new position.

Here's a fiddle that shows the issue: https://jsfiddle.net/y2kwv76v/3/
Edit a node changing its level and you'll see it won't move.
After that, click on the button "Use workaround" and the node will go to the right level.

For some reason the fiddle only works on Chrome...

**Comment by wimrijnders** [comment] 2017-07-04 05:16
It didn't work for me either in chromium. When I remove this line from options:

```
  locale: navigator.language, 
```
...all was well, also in firefox.

Hey, I know that network! Great example BTW.

**Comment by wimrijnders** [comment] 2017-07-04 06:36
Adding a new node appears to work fine. So the problem is in the update. Digging in...

I believe it's the following:
* when *adding* a node, `LayoutEngine.setupHierarchicalLayout()` is called, which re-initializes the layout, thus determining the position of the new node.
* This method is not called when *updating* a node, thus a new position is not calculated. The workaround forces the recalculation.

Thus, the logical thing to do is to force the recalculation on the update as well. However, it's a bit overkill to do this on every arbitrary change in the node data; `LayoutEngine.setupHierarchicalLayout()` is a pretty hefty method to run.

I propose to add a check on update if option `level` has changed; if so, do the recalculation. There may be other node data that have an effect; I can't think of any right now but these can be added as needed.

**Comment by wimrijnders** [comment] 2017-07-06 07:07
Fix has been submitted. It was pretty straightforward after preceding analysis.

**Closed** 2017-10-12 13:22 UTC
Labels: Confirmed Bug, Fixed awaiting release, Network
