### ISSUE TITLE
Vis is swallowing click events

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#911] opened 2015-06-02 12:37 UTC
Hi @ devTeam
Bug description: 

I give you $10 if you manage to write your firstname and your lastname into the textboxes in the JSBIN provided here¹: http://output.jsbin.com/ficeca/1

-Felix

¹ Disclaimer: this is just a joke. But the bug is real.

**Comment by josdejong** [comment] 2015-06-02 12:47
I think this is a duplicate of #893, it's probably a bug in the clickToUse functionality which is shared by Network, Graph2d, and Timeline.

**Comment by AlexDM0** [comment] 2015-06-02 12:58
Aww.. I was so ready to insert some small JS there using the keycharm from vis to be able to type my first and last name in those boxes....

**Comment by josdejong** [comment] 2015-06-02 13:06
Sounds like we're going to have a nice fight between Hammer.js and keycharm :D

**Comment by AlexDM0** [comment] 2015-06-02 13:08
nah, I'll just getElementsByTagName and fill them with the document-level keystrokes :) Hammer can do all the clicky clicky stuff it wants

**Comment by josdejong** [comment] 2015-06-02 13:11
```js
document.write('I win!');
```

**Comment by AlexDM0** [comment] 2015-06-02 13:12
thats not in the forms..

**Comment by ludost** [comment] 2015-06-02 13:16
May I claim that $10? (I have both Jos and Alex as my witnesses) Right-click on the first field, left-click to ignore the context menu, write name, next field:)

**Comment by josdejong** [comment] 2015-06-02 13:17
You're really busy aren't you Ludo?

**Comment by felixhayashi** [comment] 2015-06-02 13:25
Guys... it was just a joke. I really cannot afford to give away $10 as I already promised my girlfriend I would take her out to dinner tonight. Please have mercy with a poor guy.

**Comment by josdejong** [comment] 2015-06-02 13:49
Should be fixed now in the `develop` branch. Have fun tonight ;)

**Comment by stanleyxu2005** [comment] 2015-06-03 04:52
You people are quite productive. Second-level community response. Minute-level bug fix. +1A user satisfaction.

**Closed** 2015-06-05 11:39 UTC
Labels: bug, Fixed awaiting release, Network
