### ISSUE TITLE
Image nodes in network are square until interacted with

### ISSUE THREAD

**Issue by lucaswerkmeister** [almende/vis#3203] opened 2017-06-23 11:34 UTC
After upgrading from vis 4.19.1 to 4.20.0, images in the network visualization are squeezed to square aspect ratio until the network is somehow interacted with, at which point they assume their correct aspect ratio. (Usually the switch happens as soon as you select a node, sometimes only upon deselection.)

We can reproduce this on Firefox and Chromium (both Ubuntu Xenial).

Small reproducer:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Vis Network Image Aspect Ratio Test</title>
    <script src="node_modules/vis/dist/vis.js"></script>
    <link rel="stylesheet" href="node_modules/vis/dist/vis.css">
  </head>
  <body>
    <div id="mynetwork"></div>
    <script>
      new vis.Network(
        document.getElementById('mynetwork'),
        {
          nodes: new vis.DataSet([
            { id: 1, label: 'Test node', shape: 'image', image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Aspect-ratio-16x9.svg/320px-Aspect-ratio-16x9.svg.png' }
          ]),
          edges: new vis.DataSet([])
        },
        {}
      );
    </script>
  </body>
</html>
```
(Assumes that `vis` is in `node_modules`; adjust the paths in `<head>` if necessary.)

Before interacting with the graph:
![screenshot from 2017-06-23 13-32-57](https://user-images.githubusercontent.com/2346599/27480511-84c722f6-5818-11e7-8f29-760a82d8c44f.png)
After selecting and deselecting the node:
![screenshot from 2017-06-23 13-33-04](https://user-images.githubusercontent.com/2346599/27480527-938e6aa6-5818-11e7-9757-a321304e3df5.png)

From a quick glance over the release notes, #3010 sounds like it might be responsible for this.

**Comment by lucaswerkmeister** [comment] 2017-06-23 11:39
Here’s a live example with a slightly larger graph on query.wikidata.org: http://tinyurl.com/yazbfwy8 – as soon as you click one of the nodes, all of the images correct their aspect ratio (so it’s not per-node – I forgot to mention that in the issue description).

(Note that we might roll back to 4.19.1, which would break the live example. See [T168714](https://phabricator.wikimedia.org/T168714) for more information on what we’re doing about this bug.)

**Comment by wimrijnders** [comment] 2017-06-23 12:00
Confirmed. I've seen this happen as well with SVG's.

**Comment by wimrijnders** [comment] 2017-06-23 12:49
### Analysis:

1. The `Network` instance is loaded and running before the images actually load. this can be due to the delayed loading through the network connection. When the images are actually loaded, an event is emitted to the renderer, which doesn't honor the event, because it thinks it's redrawing already.

2. Due to the delayed loading of the images, the nodes initially take the default node sizes. Because the previous event never gets processed, the sizes aren't recalculated until there is a reason to.

----

I've tried forcing the event, without success. I think the next thing to try is to force the resizing within the nodes until the images are there. I still have trouble fathoming why it's going wrong. Will keep you posted.

**Comment by wimrijnders** [comment] 2017-06-23 13:49
OK, have a fix for this. Are you capable of patching it in the vis source? This would be the quickest way to fix the issue for you.

**Comment by lucaswerkmeister** [comment] 2017-06-23 14:14
I’m not sure if that’s possible, I’m not responsible for deployment – let’s ask @SMalyshev :)

**Comment by wimrijnders** [comment] 2017-06-23 14:31
The alternative is that I supply you with an interim version with a fix. Is that acceptable? You will have to wait till monday, though.

**Comment by wimrijnders** [comment] 2017-06-24 06:06
I've submitted a PR for this issue in the hope that it can be accepted for the release planned this weekend. This would avoid any problems with deployment on your side.

**Closed** 2017-07-02 20:45 UTC
Labels: Confirmed Bug, Network

**Comment by lucaswerkmeister** [comment] 2017-07-02 21:23
Thanks, now I can confirm that the issue seems to be fixed.

**Comment by wimrijnders** [comment] 2017-07-03 04:35
OK, great! You must have gotten a notification of the new release, TIL.

**Comment by lucaswerkmeister** [comment] 2017-07-03 07:07
No, just a notification that this issue was closed :)
