### ISSUE TITLE
Timeline - zooming causes months/years to jump

### ISSUE THREAD

**Issue by smopucilowski** [almende/vis#3144] opened 2017-06-07 08:30 UTC
vis 4.20.0 timeline module, Chrome 58 under Ubuntu MATE.

Zooming on a timeline with multiple background ranges causes a redraw of the timeline labels.

This sometimes fails to update the position of these background ranges. These are then rendered at completely the wrong start/end ranges.

A code example which demonstrates this issue is at:
http://jsbin.com/fereqazoqi/edit?html,output

[A short recording of the issue in action](https://media.giphy.com/media/3og0IExZPEj4S9I9c4/giphy.gif)

**Comment by yotamberk** [comment] 2017-06-17 11:01
same as #3105

**Comment by bradh** [comment] 2017-06-19 06:49
Closing as duplicate of #3105.

**Closed by bradh** 2017-06-19 06:49 UTC
Labels: Confirmed Bug, Duplicate, Timeline
