### ISSUE TITLE
need multiple edges in hierarchical layout

### ISSUE THREAD

**Issue by SylvainGallois91** [almende/vis#2957] opened 2017-04-07 14:52 UTC
Hi guys ,

First -> I'm new here 
Second ->
Excuse me guys , i try to build a network graph , it's working perfectly but with hierarchical layout , it's impossible to have multiple edges between nodes. I guess it's the particularity of the hierarchical layout to collapse all my edges between two nodes to make one and only one edge between them. But , i need to have multiple edges between them , otherwise i will loose data informations (values of edges). I ask for feature or if this upgrade already exist please link me this , I've searched in your issue like 3 days.

In hope to get a response .. Thanks !
See you soon.

PS : I'm from France , sorry about my english level ..

**Comment by centi123** [comment] 2017-04-08 22:07
Also interested in such a feature. After a week of searches finally found this comment to realize that it does not exist.

**Comment by SylvainGallois91** [comment] 2017-04-09 11:48
Hi!

It's a problem for me to have one and only one edge because in barnesHut
layout got like 6 edges between nodes , and i need this six edges.. When i
try to put space between node i'm must choose the hierarchical layout but
you can't have multiple edges.. so this is a problem , i search like a
fusion between these two layout..

2017-04-09 0:07 GMT+02:00 centi123 <notifications@github.com>:

**Comment by Deano24** [comment] 2017-04-11 23:29
I am also interested in such a feature, I did not find any documentation as to why it is not possible while using a hierarchical layout.

**Comment by wimrijnders** [comment] 2017-04-12 04:10
Hi there,

It is, in fact, possible to have multiple edges between nodes in an hierarchical layout. There are two distinct issues here:

**1. Storage of edge information** - `network` can deal with multiple edges between two nodes; to have full control over the data, it is wise to define the node and edge data as `DataSets` on initialization.
**2. Display of multiple edges** - Due to the drawing method, the edges will be drawn precisely on top of each other, so that they appear as one edge in the hierarchical graph.

So, if the issue is retaining the edge data, this can be solved. But the distinct edges will not be visible when the graph is drawn.

Please note that this is technically an abuse of the hierarchical structure. I don't expect support for drawing multiple edges in hierarchical graphs to be implemented; feel free to have a go at it.

**Comment by SylvainGallois91** [comment] 2017-04-20 08:31
The main problem is to have minimal node space to avoid two nodes overlaped. So i use hierarchichal layout to put space between them , but in a theoric hierarchical way , it's impossible to have multiple edges between 2 nodes , because the system will think it's "the same edge but repeat multiple times" so the system squeeze all edges in one. Take in account the fact of each edges values are different , there is a problem i think.

**Comment by wimrijnders** [comment] 2017-04-30 09:54
Duplicate of #1957. Closing this issue, continuing further work there.

Please note the workaround in said issues, perhaps it might apply to your situation. This workaround has also given me an idea on how to solve this.

**Closed by wimrijnders** 2017-04-30 09:54 UTC
Labels: Duplicate, Network, Problem
