### ISSUE TITLE
Scrolling so that groups collapse and then back makes ranges overlap - Bug?

### ISSUE THREAD

**Issue by brainwipe** [almende/vis#751] opened 2015-03-30 15:35 UTC
I have a timeline of grouped items, which draw as expected on first render. If I scroll a long way to the left such that the groups collapse (no items shown) and then scroll back to the items, they overlap:

![image](https://cloud.githubusercontent.com/assets/1922279/6899716/21879d16-d6fa-11e4-95a3-caf6c1af2fa5.png)

While experimenting, I discovered that if you zoom (scroll wheel) when they are overlapped, they redraw correctly.

Vis version: 3.11.0
Here's the code, tested in Chrome 41.0.2272.101 on Win 8.1

```html
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="utf-8">
        <title>Example</title>
        <link href="assets/css/vis.min.css" rel="stylesheet" type="text/css"/>
      </head>

      <body>
        <h3>Timeline</h3>

        <div id="timeline"></div>

        <script src="./assets/js/vis.min.js"></script>

        <script type="text/javascript">
            var container = document.getElementById('timeline');

            var data = [
              {
                id : 1, 
                name: "Group 1",
                items: [
                  {
                    name: "Single event",
                    start: new Date("2015,1,1"),
                  },
                  {
                    name: "Group 1 Item 1",
                    start: new Date("2014,1,1"),
                    end : new Date("2014,12,31"),
                  },
                  {
                    name: "Group 1 Item 2",
                    start: new Date("2015,1,1"),
                    end : new Date("2999,12,31"),
                  }
                ]
              },
              { 
                id : 2, 
                name: "Group 2",
                items: [
                  {
                    name: "Group 2 Item 1",
                    start: new Date("2015,5,1"),
                    end: new Date("2999,12,31"),
                  },
                  {
                    name: "Group 2 Item 2",
                    start: new Date("2015,3,10"),
                    end: new Date("2999,12,31"),
                  },
                  {
                    name: "Group 2 Item 3",
                    start: new Date("2015,3,1"),
                    end: new Date("2999,12,31"),
                  },
                  {
                    name: "Group 2 Item 4",
                    start: new Date("2015,2,1"),
                    end: new Date("2999,12,31"),
                  },
                  {
                    name: "Group 2 Item 5",
                    start: new Date("2015,1,3"),
                    end: new Date("2999,12,31"),
                  },
                ]
              },
            ];

            var groups = new vis.DataSet();
            var items = new vis.DataSet();
            var itemid = 0;

            for (var g = 0; g < data.length; g++) {
              
              var group = data[g];
              groups.add({id: group.id, content: group.name});

              for (var i=0 ; i< group.items.length; i++)
              {
                itemid = itemid + 1;
                var item = group.items[i];
                items.add(
                  {
                    id : itemid,
                    group: group.id,
                    content: item.name, 
                    start: item.start,
                    end: item.end,
                  });
              }
            }

            // Set start and end dates
            var now = new Date();
            var timelineStart = new Date();
            timelineStart.setMonth(now.getMonth() - 5);

            var timelineEnd = new Date();
            timelineEnd.setYear(now.getFullYear() + 2);

            // Configuration for the Timeline
            var options = {
              maxHeight: 600,
              start: timelineStart,
              end: timelineEnd,
              orientation: "top",
            };

            // Create a Timeline
            var timeline = new vis.Timeline(container);
            timeline.setOptions(options);
            timeline.setGroups(groups);
            timeline.setItems(items);
        </script>

      </body>
    </html>
```

Am I doing something wrong; or is it expected by everyone but me; or is it a bug?

Thank you everyone!

**Comment by josdejong** [comment] 2015-04-09 08:52
Thanks for the clear description, this looks like a bug.

I've put your example code in a jsbin: http://jsbin.com/ronisu/1/edit

To reproduce the issue, move (not scroll) to the past until all groups are empty and collapsed, then move back to the present and you will see the ranges being drawn wrongly, overlapping each other.

**Comment by josdejong** [comment] 2015-06-16 14:09
This seems to be fixed in v4

**Closed by josdejong** 2015-06-16 14:09 UTC
Labels: bug, Timeline
