### ISSUE TITLE
is it possible to display timeline by duration from zero to one hour

### ISSUE THREAD

**Issue by dancingalone** [almende/vis#2504] opened 2016-12-27 03:05 UTC
hi everyone thanks for a great lib. I am a new guy for js, so far i meet a new requirement that i need to display the timeline like this pic
<img width="674" alt="2016-12-27 10 56 09" src="https://cloud.githubusercontent.com/assets/2200697/21489291/bfb5af44-cc23-11e6-8293-8c737b13ffb3.png">
is it possible to fix it using vis

**Comment by yotamberk** [comment] 2016-12-27 07:34
duplicate of: #92

try this: 
``` javascript
var options = {
    start: new Date(0),
    end: new Date(100),
    min: new Date(0),
    format: {
      minorLabels: function(date, scale, step) {
        switch (scale) {
          case 'millisecond':
            return new Date(date).getTime() + "ms";
          case 'second':
            var seconds = Math.round(new Date(date).getTime() / 1000);
            return seconds + "s";
          case 'minute':
            var minutes = Math.round(new Date(date).getTime() / 1000 * 60);
            return minutes + "m";
         ............................ and so on ..........................
      }
    }
  };
```

**Closed** 2016-12-27 07:34 UTC
Labels: Question, Timeline
