### ISSUE TITLE
vis is not defined error

### ISSUE THREAD

**Issue by larrysmith79601** [almende/vis#2981] opened 2017-04-13 14:23 UTC
In vis.js, (v4.19.1), I was getting a "vis is not defined" error.

Looking at the code, at line 3386, char 50 (immediately after the "||") there is an "Â" character that shouldn't be there. Remove it and the error disappears.

So:
(this._dayOfMonthOrdinalParse.source ||Â this._ordinalParse.source) +

should be:
(this._dayOfMonthOrdinalParse.source || this._ordinalParse.source) +

![vis error](https://cloud.githubusercontent.com/assets/27429069/25008814/6b44569e-202a-11e7-92a9-a707bee5dc0a.png)

**Comment by wimrijnders** [comment] 2017-04-13 15:15
Duplicate of #2912.

This is a bug with a priority fix. It will be fixed in the next release.
In the meantime, please just delete that weird character.

**Closed** 2017-04-14 09:01 UTC
Labels: Duplicate
