### ISSUE TITLE
Network. Empty nodes in a hierarchical network

### ISSUE THREAD

**Issue by colotiline** [almende/vis#2509] opened 2016-12-28 10:03 UTC
Hello. 

I've got an issue with VisJs Network. A hierarchical network doesn't draw nodes when I have more than 200 of them, also zoom completely destroys a network. As opposite a non-hierarchical network draws all nodes.

A hierarchical network:
![image](https://cloud.githubusercontent.com/assets/5231197/21519120/e96eba50-ccfb-11e6-89b4-84a2ad2371b5.png)

A non-hierarchical network:
![image](https://cloud.githubusercontent.com/assets/5231197/21519130/f6c4fd2c-ccfb-11e6-8f5d-ad65b1d8a601.png)

JSBin for the hierarchical network - http://jsbin.com/luwavu/edit?html,output. 
JSBin for the non-hierarchical network - http://jsbin.com/kupusex/edit?html,output.

I've added `if` to convert a hierarchical network to a non-hierarchical when there are more than 200 nodes, but I'm not happy with this solution.

Do you have any idea where should I dig to solve this issue?

**Comment by LLTommy** [comment] 2017-01-09 15:56
I don't really have an idea, just something I realised by clicking on your jsbins: In the console it complains about a missing file (404). Why is that, what file is that?

**Comment by colotiline** [comment] 2017-01-10 21:06
@LLTommy, hi. I don't see any 404 error.

**Comment by LLTommy** [comment] 2017-01-11 09:33
At least if you start it in a new window (full screen), it says 404 and the file that it tries to get is  https://cdnjs.cloudflare.com/ajax/libs/vis/4.17.0/vis.map ... I don't know about a vis.map file so that is why I was confused/curious. Might have nothing to do with your actual problem though.

**Comment by colotiline** [comment] 2017-02-13 14:08
Everything is ok when I remove edges below:

```
{
	"to": "28018",
	"arrows": "to",
	"label": "0.18%",
	"from": "162795",
	"color": "#000000"
}, {
	"to": "3550669",
	"arrows": "to",
	"label": "0.13%",
	"from": "2747889",
	"color": "#000000"
}, {
	"to": "28106",
	"arrows": "to",
	"label": "30%",
	"from": "10209503",
	"color": "#000000"
}

```

Continue searching for reasons.

**Comment by colotiline** [comment] 2017-02-13 14:11
The hierarchical version with removed edges http://jsbin.com/basopehequ/edit?output.

**Comment by colotiline** [comment] 2017-02-13 14:22
Everything became more interesting. The only one edge that I should remove is:
```
{
	"to": "28106",
	"arrows": "to",
	"label": "30%",
	"from": "10209503",
	"color": "#000000"
}
```

**Comment by colotiline** [comment] 2017-02-13 14:32
The graph is collapsed when I try to connect edge `28106` and `10209503`.

![image](https://cloud.githubusercontent.com/assets/5231197/22887138/f37ae704-f211-11e6-9918-63170de4ca90.png).

Digging further.

**Comment by colotiline** [comment] 2017-04-18 15:10
I "fixed" this issue by disabling `this._condenseHierarchy()` in the `setupHierarchicalLayout`.

**Comment by wimrijnders** [comment] 2017-04-26 13:40
Except for the big curves in the hierarchical layout, this looks suspiciously like #1735. I am tempted to label this as a duplicate; will investigate a bit further.

**Comment by wimrijnders** [comment] 2017-04-26 14:17
> Everything became more interesting. The only one edge that I should remove is:

Doesn't work for me (`vis.js v4.191.1`). I can leave it in, though, and remove the other two and that works as well.

**Comment by wimrijnders** [comment] 2017-04-26 14:34
> I "fixed" this issue by disabling `this._condenseHierarchy()` in the `setupHierarchicalLayout`. 

Great find! With this info, I can narrow the issue down to the handling of option `layout.hierarchical.edgeMinimization: true`. Set this to false, and the network works.

Please accept this as a workaround for now. The other news is, this confirms that it's the same issue as #1735, since that workaround works there as well.

Closing this issue, work continues in #1735.

**Comment by wimrijnders** [comment] 2017-04-26 14:35
Duplicate of #1735.

**Closed by wimrijnders** 2017-04-26 14:35 UTC
Labels: Duplicate, Network, Problem
