### ISSUE TITLE
No zoom events fired for keyboard presses

### ISSUE THREAD

**Issue by yamini16** [almende/vis#953] opened 2015-06-09 18:59 UTC
I was going through the cluster by zoom example (visjs.org/examples/network/other/clusteringByZoom.html) hosted on vis website. It does not seem to work. I edited the example to allow keyboard controls for zoom. I can zoom now but the graph does not change. I cannot see any clustering being done there. Is there something that I'm not doing correctly?

**Comment by AlexDM0** [comment] 2015-06-09 19:09
Hi,

I'll edit the title here to state "No zoom events fired on keyboard actions". That is the cause of the problem here. We'll fix this for the next release.

Thanks for letting us know!

Regards,

Alex

**Comment by yamini16** [comment] 2015-06-09 19:11
Thanks Alex.

**Comment by AlexDM0** [comment] 2015-06-18 16:30
Hi, 

This has been fixed on develop.

Cheers

**Closed** 2015-07-03 13:04 UTC
Labels: bug, Fixed awaiting release, Network
