### ISSUE TITLE
Labels for edge endpoints

### ISSUE THREAD

**Issue by gomezgoiri** [almende/vis#1865] opened 2016-05-20 10:44 UTC
Right now, the edges can have labels associated. These labels are displayed in the centre of the edge.

However, sometimes it is also useful to label not only the edge but, the "to" or the "from" endpoints of the edge. The idea is to have text instead of (or in addition to) arrows.

**Comment by Tooa** [comment] 2016-12-12 23:39
Duplicate of https://github.com/almende/vis/issues/2104. Closing in favor of the other issue.

**Closed by Tooa** 2016-12-12 23:39 UTC
Labels: Network, Question
