### ISSUE TITLE
Unmet peer dependency webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc

### ISSUE THREAD

**Issue by BrandonNoad** [almende/vis#2685] opened 2017-02-06 17:54 UTC
When I run `npm install vis`, I'm getting the following warning:

```
└─┬ vis@4.18.1
  └── UNMET PEER DEPENDENCY webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc

npm WARN babel-loader@6.2.10 requires a peer of webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc but none was installed.
```

**Comment by yotamberk** [comment] 2017-02-06 20:50
@mojoaxel Can you take care of this?

**Comment by rretter** [comment] 2017-02-08 03:45
Just installed node.js, which worked.
Just *tried* to install vis, which didn't, reporting this same problem.
Not so great a sign when software doesn't even *install* correctly.
Is installing even tried before a version gets put forth for general use?

**Comment by yotamberk** [comment] 2017-02-08 19:15
@BrandonNoad Thanks for reporting. 
@rretter It's kind of rude to answer like that... Sometime we miss things... We are currently working on automated tests so we don't have these kinds of misses. In any case, a bit of manners would be appreciated... We do this project for fun - we don;t get paid to do this...

**Comment by mojoaxel** [comment] 2017-02-08 19:40
I'll try to take a look later tonight.
@rretter Yes, oft course we test the lib before releasing. Not sure what went wrong here...

**Comment by yotamberk** [comment] 2017-02-08 19:45
Whoops. I didn't mean to close it... sorry

**Comment by mojoaxel** [comment] 2017-02-08 20:59
Looks like this was introduced in #2513 (4.18.0).
Because I had webpack@2 installed globally I did not noticed the problem during testing. Sorry!

**Comment by BrandonNoad** [comment] 2017-02-09 17:26
I was able to install 4.18.0...but not 4.18.1.

**Comment by mojoaxel** [comment] 2017-02-09 17:58
Strange. Should be fixed now. 
We should keep a close eye on this topic during the next release.

**Comment by krispyp** [comment] 2017-02-10 09:59
I'm getting this with 4.18.1. I'm not installing dev dependencies, and then cannot shrinkwrap due to unmet peer dependency.

It seems the problem is that you have babel-loader as a dependency:
https://github.com/almende/vis/blob/master/package.json#L33

I can only see it being used by a gulpfile, so probably this should be a dev dependency.

The problem happens because babel-loader has a peer dep on webpack. So if you only install deps, babel-loader is installed without its peer dep webpack alongside it.

**Comment by mojoaxel** [comment] 2017-02-25 19:46
will be (hopefully) bee fixed in v4.19.0

**Comment by mojoaxel** [comment] 2017-03-18 14:44
:hankey: This is still an issue with 4.19.0

**Comment by mojoaxel** [comment] 2017-03-19 09:49
Keep it open until merged with master

**Closed** 2017-03-19 10:16 UTC
Labels: Fixed awaiting release, PRIORITY, Problem, source/non-public API
