### ISSUE TITLE
Auto optimizes the position of nodes in a tree

### ISSUE THREAD

**Issue by JaroslavPrt** [almende/vis#3322] opened 2017-07-31 13:31 UTC
Is there a way to automatically optimize the position of nodes in a tree like style ?
![tree](https://user-images.githubusercontent.com/11339544/28779948-a9cf44c6-760d-11e7-88df-162f3d093a9c.png)

or automatically resolve crossing edges
![tree_cross](https://user-images.githubusercontent.com/11339544/28780552-ccb6ae14-760f-11e7-9c61-90cf7fe1cd89.png)

**Comment by wimrijnders** [comment] 2017-08-01 05:57
Duplicate of #3081.

Yes, there is. However it only works well with strict hierarchical trees and has been known to fail spectacularly with other ones, see #1735 and many related issues. This was so bad, I blocked the optimization for non-hierarchical trees. Please view the discussion in #3081.

I'm also committed to finding a better solution for this, as promised in #3213. However, more critical issues keep on getting in the way.

**Closed** 2017-08-01 19:28 UTC
Labels: Duplicate, Network, Question
