### ISSUE TITLE
Exporting the full network as an image (not just the currently visible part)

### ISSUE THREAD

**Issue by s4448** [almende/vis#4113] opened 2018-09-06 17:21 UTC
I have pretty large networks, that dont fit fully on the screen (unless zoomed out to the point where you cant read text), and I would like to export it as an image. Currently the way to do that is to use the canvas the network is drawn on, but the canvas shows the "current view" - it does not show the full network. Would it be possible to get a method that could export the full network as an image? A raster image is fine, but I would really like to be able to do it without relying on any external software (there was a thread about saving to svg which basically devolved into exporting the network to graphviz)

**Comment by 91mohit** [comment] 2019-01-30 11:35
I am also suffering same problem to export entire network rather than screen shot.
Any suggestion ?

**Comment by mojoaxel** [comment] 2019-01-30 18:50
This is not possible.

Also closing this as duplicate of #723 and #1784

**Closed by mojoaxel** 2019-01-30 18:50 UTC
Labels: Network, Question

**Comment by justinharrell** [comment] 2019-01-31 21:31
This should be possible by saving the view options, calling a fit, calling redraw, save canvas to image, then resetting view options we have done something similar to double the canvas size for export for higher dpi.

**Comment by nevakee716** [comment] 2019-01-31 21:57
I did that for a project check the code here

https://github.com/nevakee716/cwNetwork/blob/master/src/cwLayoutNetwork.download.js
