### ISSUE TITLE
[Timeline] Firefox vs Chrome

### ISSUE THREAD

**Issue by serge144** [almende/vis#1519] opened 2015-12-16 14:40 UTC
Hey everyone,

I'm building a timeline in which i receive data from ajax calls to a Controller MVC action method. Basically i process that data ( in JSON ) and build the timeline from it.
For some of my data the timeline works fine with smooth drag, but when i open other bigger amount of data ( 36 groups with approximately 1000 items overall) the drag will have "brakes" or "lag" that can reach 1 second until it goes to desired position of the drag. And i know that obviously it will lag with more data, but in the VIS.examples ( which have the same or more data than mine ) it only decreases lets say the 'frame rate' by a small amount, while in my case it has brakes ( like i said earlier ) that can reach almost 1 second until it goes to desired position. So i tried to discover the problem and so for the same amount of groups i only included 1 item, and the problem was still there! So i don't think it has anything to do with my implementation or the amount of that.
In Firefox it goes much smoother just like the VIS.examples. 
So my question is that if there is something about chrome or maybe about the processing/implementation that i should consider. I've seen other threads in which discuss ways to boost performance of timeline but i don't think i really need it.

Best Regards
Serge

**Comment by AlexDM0** [comment] 2015-12-16 14:56
Hi,

Are you using range items or normal items? The normal items have optimizations for getting only the relevant data. 

Regards

**Comment by serge144** [comment] 2015-12-16 15:08
I'm using normal items, i don't specify the type of the items so the default is 'box'.

Regards

**Comment by josdejong** [comment] 2016-01-04 13:06
I think I can reproduce this, see the following jsbin: http://jsbin.com/hiheci/edit?html,output

**Comment by serge144** [comment] 2016-01-04 13:32
That's exactly what's happening in my timeline! Thanks josdejong.

**Comment by mast0r** [comment] 2016-01-07 08:44
I have had this issue only with Chrome browser since version 4.10.0. I have then rolled back to the version 4.7.0 an the problem disappeared.

**Comment by serge144** [comment] 2016-01-07 09:48
I tried with all versions from 4.7 to 4.11 but the problem is still there

**Comment by yotamberk** [comment] 2016-11-05 20:46
@serge144 We've implemented some performance boosters (such as vertically hiding items that are not visible, etc). This issue seems to be solved in v4.17.0 so I'm closing this issue for now. If you are still having problems with this issue in the new version, please reopen this issue.

**Closed by yotamberk** 2016-11-05 20:46 UTC
Labels: Problem, Timeline

**Comment by mojoaxel** [comment] 2016-11-05 22:00
@yotamberk We should check it with the jsbin example above.

**Comment by mojoaxel** [comment] 2016-11-07 07:55
I can't see a problem in http://jsbin.com/hiheci/edit?html,output 
So it's probably fixed.
