### ISSUE TITLE
Programmatic edge remove/add confuses network.getSelected().edges

### ISSUE THREAD

**Issue by valtih1978** [almende/vis#623] opened 2015-02-07 20:33 UTC
Here is [an example](http://valtih1978.github.io/VisualDict/almende-bug623.html). Create two nodes connected by edge. Select the edge, press Ctrl, pretend that you have edited the edge but leave the connection in place and unpress the control. 

You'll see that the edge was unselected because I use GUI controls just to control my model. I undo any changes made (it is amazing that you support this in onConnect/onDelete and etc. callbacks) and send the modification commands to the underlying (database) model instead. I use model updated events from the DB to actually update the GUI.  To recap, once user ended edge edit, I first call `network._createManipulatorBar`. Then, I use network `edges.add` and `edges.remove` to undo the edit and then use edges.add/remove again to actually synchronize the view with underlying updated model. In result, the poor edge is unselected. 

Despite edge is unselected, `network.getSelection().edges.length` reports `1` as if nothing happened to the edge. It is not surprising therefore that when I activate edit mode next time (pressing the Control key once more) edit fails. I receive error "Cannot read property 'id' of null" at 

```javascript
 Edge.prototype._disableControlNodes = function() {
    this.fromId = this.from.id;
``` 

but it happens obviously because we should not enter the edit mode. Correct reporting of `network.getSelection()` would fix this error. 

Notably, `getSelection == 1` after `editedEdge.unselect()` or unselecting all `network.getSelection().edges` in the same way. But I see clearly on the screen that nothing is selected. But `network.selectEdges([])` does have effect after I redo the edit after model update. Nothing is selected if I unselect edges once (re)create any of them using this call. The effect of intentionally unselecting edited edges to prevent the trap, can be [found here](http://valtih1978.github.io/VisualDict/almende-vis.html).

The problem with my dirty hack is that it makes loading of my graph (almost 1k words) pretty slow. I have to wait for a minute it loads before the "big bang" instead of 8 seconds in case I comment the edge unselect.

**Comment by AlexDM0** [comment] 2015-02-07 23:59
If the controlnodes are the problem, disbe the smoothCurves. 

I'm not sure what this issue is about. You have hacked around in the code, it does not behave the way you want it too and I don't see a specific question asked.

The moment you alter the codebase, warranty is void as they say. Any advice we can give is unfounded and unless there is a directed question on our own implementation, we're not here to debug your work. 

You also modified the selection and unselect before the edit edges. At this point there is nothing we can do to help here. 

If you can reproduce this in our own example, please let me know and I'll look into the problem. 

Regards,

Alex

**Comment by valtih1978** [comment] 2015-02-08 00:23
> it does not behave the way you want it too and I don't see a specific question asked

Do you mean that it is ok that vis.lib misreports the (amount of) edges selected?

> You also modified the selection and unselect before the edit edges. If you can reproduce this in our own example, please let me know and I'll look into the problem.

Are you saying that is forbidden to mix programmatic select/uselect of the nodes with edge edit tool? Do you see that I unselect just to suppress the bug under the second, almende-vis, link? It serves only purpose to demonstrate that my workaround works. If you like, I can delete the workaround. In order to look at the bug you must check the first link (almende-bug623). Nothing is unselected there explicitly. Only if your add/remove edge code does. It is also rediculous to demand the programmatic/edge tool mixing bug to be demonstrated with your examples. I see no example which does both. I may though try to prune my example.

**Comment by valtih1978** [comment] 2015-02-08 02:41
[Here is the code I reduced to bare minimum](http://jsfiddle.net/a2bdh74L/) (besides your original example).

**Comment by AlexDM0** [comment] 2015-02-08 11:10
> Do you mean that it is ok that vis.lib misreports the (amount of) edges selected? 

No, its not OK. The problem is that you have introduced this bug yourself by editing the _createManipulatorBar function.

> Are you saying that is forbidden to mix programmatic select/uselect of the nodes with edge edit tool? Do you see that I unselect just to suppress the bug under the second, almende-vis, link? It serves only purpose to demonstrate that my workaround works. Basically, you say that you are not going to fix the bug because you dislike the proposed workaround. Bad workaround should enthuse fighting the bug rather than opposite. I can delete the workaround, if you like :).

Nothing is forbidden. The software is free and open, you can do whatever you want with it :). No I have not been through all your code in the references you give to you project. What I'm trying to say is that we have a public API. It is documented and that is the intended behaviour of our system. Through the public API we offer methods, events and options. If anything combination of those results in a bug we will do our best to fix it. 

Now since this is a opensource project people can alter the code to suit their needs and that is fine. But if they then introduce a bug, it is not our job to fix it. I tried reproducing your scenario in our example 25 and there everything works, which leads me to conclude that the alterations you have done to the internal method(s) is the problem.

> It is also rediculous to demand the programmatic/edge tool mixing bug to be demonstrated with your examples. I see no example which does both.

This may have been poorly phrased on my part. If you can show the existence of a bug using ONLY the public API we offer, we'll do our best to fix it.

The codebase for the network is quite large, it is not always nicely modularized and the logic is not always central in the functions where you'd expect it. It is in dire need of a large refactoring and we have that on our roadmap. As is the case here, a simple alteration in the internal structure may not work as intended due to secondary effects in other places.

You make it a little difficult for us to help you. As was mentioned in previous issues, the right way to approach this is either to (in a friendly manner) make a feature request to disable the unselect, with an usecase and argumentation or alter the internal code manually. Feature requests have often been added it in the official releases.

If you hack around the code and make it to what you want, the responsibility of making sure everything works as intended is on you. I'd also recommend that you do your modifications to the files in the lib directory and compile them using gulp. Everything is more separated and clean there. The compiled version is can change a lot!

In regards to your code on the fiddle:
```
edges.remove(ee.id)
edges.add({id: "1-2", from: "1", to: "2"})
```
Why do you do this? By doing the callback, the update is already performed in the dataset. To remove it and to add it just to unselect is a little strange. You also 'unselect'  the edge AFTER the original function has created the manipulation toolbar. When it did that, the selection was still present.

If the only goal is to do the unselect, try this:
http://jsfiddle.net/a2bdh74L/2/

Regards,

Alex

**Comment by valtih1978** [comment] 2015-02-09 20:05
> No, its not OK. The problem is that you have introduced this bug yourself by editing the _createManipulatorBar function.

That is total crap. You not only keep on blaming me in "my bug", you dare to ignore the fact that your, "error free" repository behaves similarly, after I have demonstrated this to you in the last demo. `_createManipulatorBar` is declared in http://almende.github.io/vis/dist/vis.js. I have never pushed anything into that project. Which "edit" are you talking about?


> What I'm trying to say is that we have a public API. It is documented and that is the intended behaviour of our system.

This crap contradicts to your first statement, which claimed `No, its not OK.` You cannot relate two consequentive paragraphs together. 


> Why do you do this? By doing the callback, the update is already performed in the dataset. To remove it and to add it just to unselect is a little strange. 

I have told you this in the post. You obviously did not read it. I have realized it from very beginning and even asked you to start doing that before proceeding with replies. It would be stupid from my side to recap, repeating what I explained. It is stupid to recap when you still have the original text in front you and not going to read/understand anything. The only right question in this situation is therefore different: why do you ask me anything? You say that you do not listen. Why do you ask?


> You also 'unselect' the edge AFTER the original function has created the manipulation toolbar. When it did that, the selection was still present.

Where is it present? I see a bug is present in the selection. It makes it impossible to determine whether selection is present or not. This is what this issue is about.

> If the only goal is to do the unselect, try this:

You are obviously insane. I have told you why I did that and even did it twice. Either you are insane or unaware what the `workarounds` are or talking to somebody else.

sincerely yours
valentin

**Comment by AlexDM0** [comment] 2015-02-09 20:50
Hi,

After re-reading everything I seem to have jumped to some conclusions, for which I apologize. I suppose I shouldn't skim git issues on a Sunday morning. I have reduced your bug report to the following:

http://jsbin.com/kulugerure/3/edit?html,output

The fact that after the dataset modification the selection is not verified is indeed a bug on our side and we'll fix it. 

> That is total crap. You not only keep on blaming me in "my bug", you dare to ignore the fact that your, "error free" repository behaves similarly, after I have demonstrated this to you in the last demo. _createManipulatorBar is declared in http://almende.github.io/vis/dist/vis.js. I have never pushed anything into that project. Which "edit" are you talking about?

I am referring to the part below:

```
var originalCMB = network._createManipulatorBar
		network._createManipulatorBar = function() {
		
			originalCMB.call(network)
		
			if (ee != null) {
				edges.remove(ee.id)
				edges.add({id: "1-2", from: "1", to: "2"})
				alert("Now, see that edge was unselected. Yet, selected edges count = "
				+ network.getSelection().edges.length + " and 'edit edge' is available. Click it immediately again and see what happens!")
			}
			ee = null
		}
        var ee = null
```

Here you alter the internal functions. This is an edit of the source code in the sense that you are directly affecting the internal logic of the system as we designed it. That is fine of course, we only cannot guarantee any modifications on these functions will remain functional in upcoming releases, nor do we offer support from problems arising from these modifications. Seeing as when I removed the added part the problem also stopped occurring, I somewhat prematurely concluded that you introduced it. 

What I meant with:

> What I'm trying to say is that we have a public API. It is documented and that is the intended behavior of our system.

is that we do not consider modifications as the code snippet I have sampled above as the public API, those we refer to as modifications of the source. If you have found a bug in vis, it would be greatly appreciated if you could show it without such modifications, in a small example like the one I've shown here (and except for the modification of the _createManipulatorToolbar, the fiddle you posted as well).

Regards,

Alex

**Comment by AlexDM0** [comment] 2015-02-10 10:39
Hi,

The bug shown in the jsbin has been fixed in the develop branch. There will be a release soon and this fix will be included.

Regards,

Alex

**Closed by AlexDM0** 2015-02-10 10:39 UTC
Labels: Network, source/non-public API

**Comment by josdejong** [comment] 2015-02-16 09:59
@valtih1978 this is the second time I have to warn you for misbehaving. You reaction is extremely offensive and insulting. This didn't happen just once, *many* of your posts have an arrogant, disrespectful tone, sounding like you know how to do stuff right and us being just stupid monkeys or something.

I will remove your last post in this topic, it's *way* over the top. It would be neat if you would apologize to Alex and the community and start communicating in a grown up, respectful, constructive way instead.

**Comment by valtih1978** [comment] 2015-02-16 19:01
Essentially, if we leave out the demagogy, you say that "being constructive" = "ignoring what other party says, ignoring the problem". I know about this part of your culture, which is also called "tolerance". But thanks for reminding me anyway.

**Comment by josdejong** [comment] 2015-02-17 08:29
@valtih1978 you are no longer welcome here until you are able to be respectful to others.

**Comment by valtih1978** [comment] 2015-02-17 14:38
People should certainly go over the truth/justice/common sense.
