### ISSUE TITLE
Timeline view incorrect when zoomed out at the level of months

### ISSUE THREAD

**Issue by emiliosalazardonate** [almende/vis#3179] opened 2017-06-16 09:13 UTC
I am running in Firefox 34.0.5 in Linux, but it happens also in Chrome with vis 4.20.0.
I have a time line and everything looks perfect as soon as I don't zoom out to the level of months.
You can see that with this granularity the occurrences are seriously misplaced. In the image you can see one example of an occurrence which happens at the end of April, but in the image seems to be happening at the middle of that month.

![visjs2](https://user-images.githubusercontent.com/12808577/27220153-75d25b06-5284-11e7-8bce-91b64c957c35.png)
![visjs1](https://user-images.githubusercontent.com/12808577/27220154-75d47670-5284-11e7-88db-5ec1b0d16ccf.png)

Thanks,
Emilio.

**Comment by yotamberk** [comment] 2017-06-16 21:08
duplicate of #3105?

**Comment by bradh** [comment] 2017-06-16 22:46
Looks like it. A patch release for 4.20.1?

**Comment by yotamberk** [comment] 2017-06-17 10:59
@bradh yes... Definitely need to. This issue is popping up again and again.

**Comment by bradh** [comment] 2017-06-19 06:49
Closing as duplicate of #3105.

**Closed by bradh** 2017-06-19 06:49 UTC
Labels: Confirmed Bug, Duplicate, Timeline
