### ISSUE TITLE
We need your help

### ISSUE THREAD

**Issue by josdejong** [almende/vis#1781] opened 2016-04-07 10:14 UTC
Almende is looking for people who can help maintaining and improving vis.js. We've put a lot of effort in building these visualizations, fix bugs, and support users as much as we can. Since some time we're lacking the manpower to maintain the library as we've done latest years. We need your help!

What can you do? 
- Help out other users having questions
- Help fixing small bugs
- Help with implementing new features
- Become a collaborator and help with releases & maintenance
- ...

Are you interested in helping some way or another? Please let us know.

**Comment by for-sagacity** [comment] 2016-04-08 07:50
Hi, My english name is winston Jeong and Korean name is SeungJin Jeong.
I am from Daejeon in South Korea.
I am 34 yeas old.
Nice to talk with you.
I am interested in helping your project.
I have been programming using java, javasciprt, flex, extjs, etc for about
10 years.

I am using network of visjs for my working project.
and I have been customized for rotating ellipse that is my project
requested function.
and I understood many part of your source code.
but I didn't understand your algorithm for phisics, .improvedLayout because
I don't need understand on my project.
Maybe I can help your network function.

But I have a problem that is my english skill.
At this time I think My english skill is poor.
but I just started studying english for IELTS.

Could I join your project for helping?

Sincerely,
Winston Jeong.

2016-04-07 19:14 GMT+09:00 Jos de Jong <notifications@github.com>:

**Comment by AlexDM0** [comment] 2016-04-08 07:57
Hi Winston,

We can use whatever help you want to provide. If you'd like to join just respond to the issues on here. If there are bugs in vis you can do a pull request with the solution until we find a better way to do it. 

Thanks for helping out!

**Comment by for-sagacity** [comment] 2016-04-08 08:09
Ok I got it.
I will help you as far as i can.

2016-04-08 16:57 GMT+09:00 Alex <notifications@github.com>:

**Comment by beingsagir** [comment] 2016-04-12 08:14
This is an awesome library. In future it will serve a lot of professional designs and apps. We need to come forward and carry it together. I will be there. 
I also do suggest to (let's) make everything little organised so, each time we come here know what to do. 

[-] The website also needs to be little more organised.

**Comment by AlexDM0** [comment] 2016-04-12 08:15
Thanks! We're open to suggestions and pull requests to the website as well. What do you have in mind?

**Comment by yotamberk** [comment] 2016-04-14 07:30
I can pick up some bugs during some weekends. 
I deal mostly with the timeline so I'm willing to take any bugs there.

**Comment by AlexDM0** [comment] 2016-04-14 07:41
That would be great!

**Comment by beegeesquare** [comment] 2016-04-15 12:17
I'm happy to help !

**Comment by josdejong** [comment] 2016-04-16 07:34
Thanks @beegeesquare . Just sniff around for smaller or bigger issues/feature requests that you find interesting to pick up.

**Comment by kurtcagle** [comment] 2016-04-19 17:42
I'm a regular user (and evangelist) of visjs, I can't promise much, but I'll try to spend some time in the code as well.

**Comment by SepiG** [comment] 2016-04-19 19:58
Interested, what's next?

**Comment by AlexDM0** [comment] 2016-04-19 20:12
That would be great! If not the code then we could use a lot of help with answering issues. 

Regards

**Comment by AlexDM0** [comment] 2016-04-19 20:15
@SepiG answering issues, both open and new ones. Help out in code where you can or improve the website and/or documentation. Any changes can be done with pull requests to the ghpages or develop branch. 

Regards

**Comment by kurtcagle** [comment] 2016-04-19 20:58
Alex,

I'd definitely be willing to help there. I'm kind of a JS-lite kind of guy,
good enough to understand what's going on and use the tools, but definitely
much better writing about it than deep-diving. If there a particular faq or
similar area that you need to have filled in?


Kurt Cagl​e
Founder, Semantical LLC
kurtcagle@semantical.co
443-837-8725

**Comment by AlexDM0** [comment] 2016-04-19 21:00
If you feel that a faq would alleviate the amount of issues that come in then sure. It would be nice if there would be only one place to find answers though: the documentation.

**Comment by kurtcagle** [comment] 2016-04-19 23:55
That makes sense. How do you generate your documentation?


Kurt Cagl​e
Founder, Semantical LLC
kurtcagle@semantical.co
443-837-8725

**Comment by DanielZhangQingLong** [comment] 2016-04-20 03:25
I have been using your vis.js for quite a long time, I like to help though I am not very good js developper.

**Comment by AlexDM0** [comment] 2016-04-20 07:56
@DanielZhangQingLong a lot of the work now is answering issues. Most of them do not require coding, like users with questions or users misunderstanding the dataset or events or options. If you can help out responding to these that would be great! You can always ask for help in the issue if you feel it's going over your head. 

@kurtcagle we write it in html in the develop branch. Every release we overwrite the docs on ghpages with those on develop. If you feel like automating it all, be me quest ;). it could improve the inline documentation. 

Anyone else: it would be a great help if someone could go over all examples and add a clone in jsbin link to them. This would make is much much easier to help new people as you can take a jsbin staring point from any example. It would also make it easier for users with questions to show their issues.

**Comment by rcbyrne** [comment] 2016-04-22 08:45
I use Vis.js as a key part of an internal application I develop. I have also been wanting to get into some open source development outside of work, so would be happy to help pick up some work on the odd weekend.

**Comment by andreasmacht** [comment] 2016-04-30 13:50
Hi Almende team, 

First time I saw visjs library, I was very impressed about the visual features that you implemented. I am still a light-weight JS guy, but I want to get more proficient in JS and start a new career in there. I am definitely strong in documentation, issues' handling and management, answering questions as far my knowledge takes me. And the more I deep dive into JS, I would also like to support in fixing bugs in the future. 

Currently, I am doing a capstone project with MeteorJS where I also use visjs (I've recognised in the past that visjs doesn't always respond well with MeteorJS). Due date is 23rd May. Hence, till then you won't find me being crazily active here, but I keep watching the progress and I am willing to support.

Best!

**Comment by murarisumit** [comment] 2016-05-02 05:49
Hi @josdejong , I'm more into devops, so if anything in that domain is required, I'll be happy to help :)

**Comment by acefxlabs** [comment] 2016-05-03 14:01
Just saw vis and actually we are intending on extending it in the office so we can also be part of this, will do all i can to contribute

**Comment by data-hack-scripts** [comment] 2016-05-11 23:07
Hello
I would like to help, I like VIS!
:)

**Comment by frankc60** [comment] 2016-05-18 18:23
Hi, I am more than happy to be available to help out and contribute.

**Comment by AlexDM0** [comment] 2016-05-18 19:58
Thats great! We're looking for people helping out on issues and putting in / reviewing pull requests. 

Cheers

**Comment by igbopie** [comment] 2016-05-20 19:05
Hi!

I am interested!

**Comment by carthworks** [comment] 2016-05-24 07:27
please add me too

**Comment by AlexDM0** [comment] 2016-05-24 07:54
Thanks!

**Comment by igalapedia** [comment] 2016-05-29 15:33
I will be ready to contribute with the best of my knowledge in which ever way it comes before me. I am in the practice of applying VIS.js to my web based design application for solving engineering problems.

Please add me to the team of contributors and don't forget to send alert when there is issue to attend to.

**Comment by AlexDM0** [comment] 2016-05-29 17:55
Hi, thanks for helping out! If you watch the repo you'll be notified of new issues. Solving those is the main priority. We won't explicitly call on a list of people, just help out where and when you can. 

Regards

**Comment by brylie** [comment] 2016-05-30 07:00
@AlexDM0 are there any plans or ideas for a collaboration between Almende/vis and the [Cytoscape Consoritum](http://js.cytoscape.org/)?

**Comment by AlexDM0** [comment] 2016-05-30 07:07
Hi,

At this time no.

Since both @josdejong and I have new jobs we'll have to suspend aggressive development on vis until Almende has new people to fill the places. 

Regards

**Comment by filippoguida** [comment] 2016-06-02 22:55
I like this project. Can i help you?

**Comment by dimosr7** [comment] 2016-06-04 18:39
I will also try to help as much as possible. I have been using the Network module during the last months for an academic project. So, I started responding to some issues and hopefully I will try to work on some bugs/features in the future.

**Comment by abhismart02** [comment] 2016-06-13 08:11
i wanted to add bootstrap popover after clicking Network - nodes can any-One help

**Comment by AlexDM0** [comment] 2016-06-13 08:12
Hi,

This issue is not meant for questions. Please make a new issue. 

Regards

**Comment by jatanpatel92** [comment] 2016-06-17 17:19
Hi guys,

I really enjoyed using vis.js for my professional as well as academic projects and I would like to help you guys to improve it.

**Comment by hjalte79** [comment] 2016-06-21 10:41
I would like to help but not a pro programmer (im student). Could you label issues that are probably easy to fix for a beginning programmer?

**Comment by jatanpatel92** [comment] 2016-06-25 20:55
Hey guys, there are some redundant pending issues still open. Does it require write access to close them? I would like to close them and start focusing on the actual ones.

**Comment by AlexDM0** [comment] 2016-06-25 20:59
Hi,

Which ones in particular? The one posting the issue can also close, if they didn't then maybe it's not resolved yet?

Cheers

**Comment by jatanpatel92** [comment] 2016-06-25 21:07
For example,  #1910 , #1909 , #1901

**Comment by AlexDM0** [comment] 2016-06-25 21:14
Those are not answered yet. If you feel like they should be closed, you can ask the poster if it is still pending and if not, he can close it.  @ludost can you look into this? There can be more issues open that should be closed so we can clean the list.

**Comment by ludost** [comment] 2016-06-28 09:58
Hi All,

It's about time to provide some information about the current status of this project from Almende's point of view. As you've seen (at the start of this thread) the two main developers of Vis.js have moved away from the maintenance of this project. @josdejong has left the company for a new opportunity, and @AlexDM0 has moved internally to a daughter company, with severe impact on his time and availability for Vis.js. Although Almende is looking to replace the expertise required for Vis.js, we don't expect to be able to do comprehensive project management any time soon. At the same time we like to spare Vis.js from becoming abandonware, especially given the relative healthy user base. For the longer term future we would be happy if vis.js could stand on its own feet, community supported.

What the project currently needs to survive is:
1: A group of people that will handle the issues, answering, chasing the issuers for required info, and in some cases closing incomplete issues.
2: A maintainer that can look at pull requests, request enhancements, accept or reject them, etc. This person can also help decide when to release new versions.
3: A community supported roadmap, maintained by aforementioned maintainer.

If you are willing and capable of being either such a maintainer and/or part of the support group, please contact me directly. I'll take a quick look at your 'application' and provide you with the necessary writing rights if appropriate.

Kind regards,
Ludo.
Senior Software Engineer, Almende B.V.

**Comment by leoaraguas** [comment] 2016-07-01 13:15
Hi, 

My name is Leandro and i'm from Argentina. I have been using VIS for some time and it's a great library with a lot of potential. 

I would like to participate in this project and make it grow in functionalities. My free time isn't something that abounds, but please lets talk what needs to be done and I'm sure we can find a way to make it work.

Please let me know if anyone of you need more information on my skillset, role and expertise.

Sincerily, Leo

**Comment by cgrandfield** [comment] 2016-07-01 17:59
I'm interested in helping with 1, especially as related to graph3d.  

Never used javascript before and I started playing around with graph3d and it was easy and fun. I've filed a pull request here : https://github.com/almende/vis/pull/1940 with some enhancements to legend support. 

I can also help with the tagging of issues, etc... if given the permissions. 

Working on some of these items do appeal to me :  https://github.com/almende/vis/labels/Graph3D 

If I did take them up I'd like some assurance that someone would be managing pulls & releases

**Comment by tleehealey** [comment] 2016-07-02 07:19
I use the VIS library extensively and would love to help. One feature I think we need is the ability to print to PDF so that people can use the visualizations beyond our applications. Are you interested in that?

**Comment by HoangSonTran** [comment] 2016-07-05 02:06
Hi. My name is Hoang and i am living in VietNam. I am a front-end developer and willing to help you in my free time.

**Comment by shawnhuang2015** [comment] 2016-07-12 04:19
Currently, I am using vis.js for daily work. I would like to help to improve and maintain this awesome canvas based visualization library. I am mainly working on network visualization. I can work on fixing bugs and providing new features.

**Comment by mojoaxel** [comment] 2016-07-13 12:14
@josdejong Nice move. Thank you for asking for help instead of just letting the project die slowly!

**There are probably too many open issues to stay on top, at the moment!**
I would like to recommend to make heavy use of labels in Github. This way It would be much easier to get an overview what the interesting bugs and feature requests are and what are just simple questions. I like to recommend the following Labels:
* Bug (New)
* Bug (Confirmed)
* Feature Request
* Question
* Help Wanted!

Maybe additional labels like _Timeline_, _Network_ and _Graph3D_ could help to separate concerns!?

**Too many implementation questions stay open for too long!**
I also would recommend to pass on simple implementation questions e.g. to [stackoverflow](http://stackoverflow.com/tags/vis.js). Questions like _"I would like to build a booking app. How can I do this?"_ have in my opinion no place here, and should be passed on and closed as soon as possible.

**Pull Requests should have the priority of the maintainers.**
PRs should not stay open until there are too many to keep track. As I see it there are always two options to handle a PR:
1. Ask the committer to change something or provide more information.
2. Merge it.
Just leaving it sit there is not an option. If the PR stays open for too long the submitter gets discouraged. If a PR is not ready for merging and nor the submitter nor the community is willing to fix it it should be closed in a time-frame of a few weeks.

**Development-Branches**
I also see an issue with all the open branches. It would be helpful to have a little overview what branches are still in use and what there purpose are. Old branches should be removed after merging.

You also should think about moving the project to a more "neutral ground" like [visjs](https://github.com/visjs). It probably would be easier to attract external maintainers an submitters and grand them easy access.

Thanks and keep up the good work!

**Comment by hunglqe** [comment] 2016-07-19 12:04
I have some time for helping.

**Comment by rampajs** [comment] 2016-07-22 04:46
I am a Javascript developer and I can help you guys in my free time.Is there any guide to get me started on this project?
I appreciate your help.

**Comment by madangopalsingh** [comment] 2016-07-27 08:30
**I can help you guys in my free time.Is there any guide to get me started on this project?
I appreciate your help.**

**Comment by mojoaxel** [comment] 2016-07-27 08:49
The [pull requests](/almende/vis/pulls) are stacking up. 
It would be helpful if people would review and test them and add comments if they think they should be merged.

**Comment by CarlosRicagno** [comment] 2016-07-30 02:31
I would like to help too, I can work with the bugs or with documentation whatever you need

**Comment by mojoaxel** [comment] 2016-08-07 10:15
**TO ALL: If you want to help:**
* Ask owners of [old](/almende/vis/issues?q=is%3Aissue+is%3Aopen+sort%3Acreated-asc) or answered issues if it can be closed.
* Encourage users to ask projects specific questions on [stackoverflow](http://stackoverflow.com/tags/vis.js) and [help answering questions there](http://stackoverflow.com/unanswered/tagged/vis.js).
* Help answering/closing [questions](/almende/vis/labels/question) or try to fix issues with the label ["For everyone!"](/almende/vis/labels/For%20everyone%21) or every other issues you like. 
* Review, test and comment on [Pull-Requests](/almende/vis/pulls).
* Implement a [feature request/enhancement](/almende/vis/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3Aenhancement%20) ;-)

**Thank You for your help!**

**Comment by cgrandfield** [comment] 2016-08-08 00:19
@mojoaxel Do you have permissions to merge pull requests? 
My pull request tests itself with updated example apps - https://github.com/almende/vis/pull/1940 

If you will be actively maintaining this project I'll feel more comfortable starting to implement further requests / enhancements :)

**Comment by Stexxen** [comment] 2016-08-08 15:53
@mojoaxel completely agree with @cgrandfield.
I have pull request #1987 to fix issue #1857, but if its not going to get merged or responded too, i'm not really going to be too enthused to contribute further....

I have discovered another issue with improvedLayout, but currently waiting to see what happens with the above before I get more involved.

**Comment by mojoaxel** [comment] 2016-08-08 18:22
@cgrandfield @Stexxen Thanks for you comments. I'm using vis.js for quite some time but I'm a very new member of the support team. I'm neither an employee of almende nor do I have any official responsibility. I'm just a guy like you don't want so see vis.js starving to death.

> Do you have permissions to merge pull requests? 

Yes, I have full access now. As far as I understand it everybody can apply for access by taking to @ludost.

> I can see you tagging issues and pulls and appreciate that, but are others required to merge?

Thanks! Now, that all issues are labeled I will focus more on reviewing and testing pull requests, but I'm not so sure if I should merge complex changes without somebody of the more experienced guys having a look at it! You know the code probably better than me - You could also help by reviewing PRs from others!

**At the moment the support team is really very weak (as you can see). If we all work together we should be able to keep the project going until a new maintainer is found! Thanks for everybody who spends some time helping out!**

**Comment by ludost** [comment] 2016-08-08 19:08
As you guys can see, it is hard to find time/focus for this project, so the only thing I can do at this moment is cheer for the attitude and approach of @mojoaxel. As he mentioned, if any of you have the time and expertise and are willing to help, I can provide you with the necessary rights and support. 

Hopefully if there are two to three people that can help working on the PRs, I can find some time to do the more long term structuring, like helping setup a development roadmap.

**Comment by theaverageguy** [comment] 2016-08-11 16:41
Hi there.
I would also like to join the community and help. :)

**Comment by ram-c** [comment] 2016-08-12 09:24
I'm a newbie to the opensource contribution! could anyone please guide on how/where to start? Thanks :)

**Comment by mojoaxel** [comment] 2016-08-12 10:32
@theaverageguy @ram-c See [the comment above](https://github.com/almende/vis/issues/1781#issuecomment-238074389).

**Comment by jankdiss** [comment] 2016-08-17 07:40
looking to get support on drag item from different component to timeline view, that automatically populate, same to double click

**Comment by mojoaxel** [comment] 2016-08-17 09:41
@jankdiss No questions in this issue, please. The best place to ask this kind of questions is [stackoverflow](stackoverflow.com/tags/vis.js).

**Comment by garthtee** [comment] 2016-08-21 17:25
I'd love to help :+1:  @josdejong

**Comment by yotamberk** [comment] 2016-08-27 20:18
How can I submit an application to the support team?

**Comment by mojoaxel** [comment] 2016-08-27 20:39
@yotamberk Just start helping [here](https://github.com/almende/vis/issues/1781#issuecomment-238074389). 
After you started getting "into the flow" of the project you can contact @ludost with a request for access.

**Comment by yotamberk** [comment] 2016-08-27 20:57
No problem. I've added recently the rtl to the timeline, and now working on horizontal hiding of items when not visible + horizontal scroll. I'll submit the two in two separate pull request hopefully in the next two weeks after I've fully tested them. I'll be happy to go over other pull requests and test them out.

**Comment by ceomuse** [comment] 2016-09-10 00:24
Hello, I'm afraid I don't have the skills to assist but perhaps I can help in so other ways. I can provide a paid staff we've contracted for the next few years. The other is that dirty word, money to pay for some additional help. I like what you're doing and see some features we may be able to utilize in one of our projects down the road.

May we help and if so, who is the best contact?

**Comment by josdejong** [comment] 2016-09-12 07:16
Thanks for your offer @ceomuse. I think it's best to send an email to Andries Stam (andries@almende.com) for financial/business related ideas, and to contact Ludo (@ludost) for technical ideas.

**Comment by balguri23** [comment] 2016-09-13 09:54
Interested to pick some bugs, what next?

**Comment by ram-c** [comment] 2016-09-25 10:06
Sure :) I'll be happy to help! I'll start with bug regression/testing

**Comment by bardcrack** [comment] 2016-09-27 04:58
My English no is very good, but i want Help for this project.

**Comment by wimrijnders** [comment] 2016-10-09 20:47
Hi Almende,

This is to inform you that I have forked vis.js and am currently refactoring the Graph3D part.
My ultimate goal is is make multiple graphs ('groups' I believe they are called elsewhere), but this is the first step.

I'm rearranging the code so that the parts per graph style are grouped together in 'style handlers', in the process getting rid of all the tests on selected style such as:

```js
if (this.style === Graph3d.STYLE.GRID ||
    this.style === Graph3d.STYLE.SURFACE) {
    this._redrawDataGrid();
  }
  else if (this.style === Graph3d.STYLE.LINE) {
    this._redrawDataLine();
  }
  else if (this.style === Graph3d.STYLE.BAR ||
    this.style === Graph3d.STYLE.BARCOLOR ||
    this.style === Graph3d.STYLE.BARSIZE) {
    this._redrawDataBar();
  }
  else {
    // style is DOT, DOTLINE, DOTCOLOR, DOTSIZE
    this._redrawDataDot();
  }
```

I hope this can be appreciated.

En groetjes uit Groningen!

Wim.

**Comment by wimrijnders** [comment] 2016-10-10 09:30
Question, wrt. my previous post here:

I'm making the changes in the master branch - I understand that these should later be pulled into the develop branch.
But shouldn't I have done the changes in the develop branch to begin with?

Just wondering.

**Comment by Stexxen** [comment] 2016-10-10 09:56
@wimrijnders Hi is there any reason you are specifically forking vis.js and not adding your changes as a pull request?

**Comment by wimrijnders** [comment] 2016-10-10 09:59
OK, my ignorance is showing here....

I thought that was how a pull request worked, i.e. you fork, make changes
and return the changes from the fork in a pull request.

If this is not the way to do it, please advise me what the correct
procedure is.

Met vriendelijke groet,

Wim Rijnders
http://axizo.nl

**Comment by Stexxen** [comment] 2016-10-10 10:09
Sorry that was my assumption, that you meant fork as in a permanent one.
Please ignore me :-S

In regards to your changes, any pulls must be done on the develop branch, not the master.
Cheers,
S.

**Comment by wimrijnders** [comment] 2016-10-10 10:16
Ah, ok. No, I wasn't planning on maintaining a fork myself! I have every
intention of folding the changes back to the main project. I have enough
kids to take care of :-).

Pulls to the develop branch: understood. But chould I also be doing the
changes in the develop branch? I used the master as base right now.

Met vriendelijke groet,

Wim Rijnders
http://axizo.nl

**Comment by Stexxen** [comment] 2016-10-10 10:18
yes please make changes to develop branch, as that has quite a few pulls already done on it. So is significantly ahead.

**Comment by wimrijnders** [comment] 2016-10-10 10:21
OK thanks, will do. I'll merge my changes into develop and continue from
there.

Met vriendelijke groet,

Wim Rijnders
http://axizo.nl

**Comment by rohanmallelwar** [comment] 2016-10-18 10:51
Yes, I'm interested both in learning and contributing. Let me know the process to enrol myself for this.

**Comment by mojoaxel** [comment] 2016-10-18 14:30
@dragonzone Can you please contact me. I would like to make you a team member if you are interested.

**Comment by dragonzone** [comment] 2016-10-19 00:48
@mojoaxel , Thanks for the invite, however, I don't think I will have that much time dedicated to the project. Further, I only have experience w/ the vis.js Network & DataSet portion only. Once in awhile in my spare time, I will try to pitch out w/ the project since @AlexDM0 had helped me alot awhile back so I want to give back and don't want the project to be abandonware.

**Comment by mojoaxel** [comment] 2016-10-19 08:37
##################################################################################

Please read [the new "We need help" page](//github.com/almende/vis/blob/develop/misc/we_need_help.md)! If you want the help out [start Here](//github.com/almende/vis/blob/develop/misc/how_to_help.md).

##################################################################################
_This issue is closed now._

**Closed** 2017-02-16 15:24 UTC
Labels: For everyone!
