### ISSUE TITLE
License information is missing in project file

### ISSUE THREAD

**Issue by stanleyxu2005** [almende/vis#882] opened 2015-05-28 01:59 UTC
I tried to submit vis 4.0 to webjars.org. However their system has rejected the request because the license information is not included in `bower.json` and `package.json`. Could you kindly add the information, so that java/scala users can use webjars to include visjs 4.0?

https://github.com/webjars/webjars/issues/1046#event-315091911

**Comment by josdejong** [comment] 2015-05-28 09:09
Thanks.

Duplicate of #876

**Closed by josdejong** 2015-05-28 09:09 UTC
Labels: duplicate
