### ISSUE TITLE
Timeline not working after updating from 4.9.0 to 4.15.0

### ISSUE THREAD

**Issue by aske-cph** [almende/vis#1697] opened 2016-02-29 00:57 UTC
The timeline doesn't show up, only some weird small button like thing. (both newest chrome and firefox) 

And when i click on it the console returns:

`Uncaught TypeError: Cannot read property 'scale' of undefined`

I am using vis through angular-vis if that has any effect.

Tried to debug a bit:

if you look at this album on imgur : 

http://imgur.com/a/ywuQW

The image on the bottom is my timeline in 4.9.0.

The image in the middle is in 4.15.0 

The top image is after adding inline CSS via Chrome debugger like this to the vis-timeline tag:

```
width: 600px;
height: 400px;
display: block;
```

So it seems the data is there, but the Timeline does not get properly expanded length / heightwise..

**Comment by josdejong** [comment] 2016-02-29 10:09
Can you create a jsbin to demonstrate the issue? What is the code and options are you using to create the Timeline? 

I'm not sure whether there have been changes in angular-vis lately, and whether this issue originates in vis.js or in the angular directive

**Comment by daniel-pfeiffer** [comment] 2016-03-03 09:47
Oh, for me this happened from 4.12 to 4.13.  Because your examples work, I thought this was the Angular wrapper and finally reported this yesterday: [https://github.com/visjs/angular-visjs/issues/46](url)

**Comment by josdejong** [comment] 2016-03-03 10:28
How to reproduce the issue?

**Comment by josdejong** [comment] 2016-03-03 10:39
Looking at the changes in v4.13.0, it could be related to the fix of #1541. The Timeline now loads synchronously (again) and maybe that's at a moment Angular hasn't yet attached everything to the DOM or something?

**Comment by daniel-pfeiffer** [comment] 2016-03-09 10:31
I wonder if that would explain it.  Apparantly calling setWindow redraws the whole timeline.  But it still doesn't make it show up.  As I said, by the time I look, my data is in the dom.  So at least the next setWindow should be able to calculate sizes?

**Comment by josdejong** [comment] 2016-03-09 11:14
Can you create a jsbin demonstrating the issue?

**Comment by daniel-pfeiffer** [comment] 2016-03-10 11:20
Here you go: http://jsbin.com/kotenu/edit?html,js,output
If you change it to load your 4.12 you see a timeline.

**Comment by josdejong** [comment] 2016-03-11 14:00
Thanks for setting up a clear, minimal example. Will check it out.

**Comment by josdejong** [comment] 2016-03-14 16:25
This has been fixed now in the develop branch. 

The reason was that the Timeline did check `container.clientWidth === 0` to see whether the Timeline is mounted in the HTML DOM. However, the `container` element of the angular.js directive is no regular HTML DOM element like a DIV, and it's clientWidth is always 0 for some reason.

**Closed** 2016-04-07 09:12 UTC
Labels: Timeline

**Comment by daniel-pfeiffer** [comment] 2016-04-07 17:35
I confirm this to be fixed in 4.16.0 :+1:
