### ISSUE TITLE
storePositions gives error 

### ISSUE THREAD

**Issue by yearsy** [almende/vis#903] opened 2015-05-31 17:28 UTC
Hi,

When calling the storePositions() function the console gives a uncaught error

Uncaught TypeError: Cannot read property 'x' of undefined

network.on("stabilized", function() { network.storePositions(); });

I would like to store the positions of nodes after stabilized so when i alter the filter function in de dataview the node will apear on a already stabilized position. Is this the correct way or i there another solution for this problem?

Greetings.

**Comment by Tooa** [comment] 2015-05-31 21:37
Are the nodes in a Dataset? Like this:

    var nodesDataset = new vis.DataSet(nodes);
    ...
    network = new vis.Network(container, {nodes: nodesDataset, edges: edgesDataset}, options);

**Comment by ericvandever** [comment] 2015-06-01 01:58
I've also seen the error in my application after upgrading to 4.1

Simple demo 1 fiddle that replicates it
https://jsfiddle.net/b79eb45L/

From debugging, it looks like this.body.data.nodes._data[nodeId] returns undefined for the nodeIds that represent edges.  I haven't been able to track down why the edgeIds are included in the NodeHandlers list at all.

**Comment by yearsy** [comment] 2015-06-01 05:08
Yes, a dataset with a dataview was used, also without the dataview I got the same error message.
My code is similar as the jsfiddle from 'ericvandever'

**Comment by AlexDM0** [comment] 2015-06-01 06:18
Hi all,

The nodeIds you see are from the support nodes from dynamic edges. This behaviour is a bug, I'll look into it. As a workaround you could use getPositions for now and manually put them into the dataset. 

Seems like there will be another bugfix release soon. 

Regards,

Alex

**Comment by AlexDM0** [comment] 2015-06-01 10:43
Hi,

This has now been fixed on the develop branch. We'll release a this at the end of the week.

Regards,

Alex

**Comment by yearsy** [comment] 2015-06-01 11:27
Hi Alex,

I tried the develop branch, but unfortunately i keep getting the same error
![vis411-error](https://cloud.githubusercontent.com/assets/12561893/7911797/d3a106ca-0861-11e5-8efb-5579ec564344.png)

Any ideas?

**Comment by AlexDM0** [comment] 2015-06-01 12:01
Hi,

Could you make a jsbin showing this? I cannot reproduce it after the fix..

Regards

**Comment by yearsy** [comment] 2015-06-01 12:15
Hi Alex,

http://jsbin.com/xaquqecage/1/edit?html,output

Not sure how to reference the vis.js and vis.css files, but you get the idea ;)

**Comment by AlexDM0** [comment] 2015-06-01 12:36
Hi,

I see, that was because of the use of the dataview which is not originally ment to be used for alterations to the dataset. I have patched the code so it will write the positions back into the original dataset.

Regards

**Comment by yearsy** [comment] 2015-06-01 13:14
Hi Alex, thanks for the update,

Can i ask you two more short questions?
1. can you export the network canvas to an image file?
2. how can you view é like chars in as the node label?

![vis411-diacriet](https://cloud.githubusercontent.com/assets/12561893/7913513/d9c4ca32-0870-11e5-960a-0dc6a8c46d28.png)

**Comment by AlexDM0** [comment] 2015-06-01 14:58
Hi,

1: right click the canvas and save image as. Alternatively try phantom.js
2: put this tag in your head: 
```
<meta http-equiv="content-type" content="text/html; charset=UTF8">
```

Regards,

Alex

**Comment by felixhayashi** [comment] 2015-06-02 11:20
Hi @AlexDM0 

Just wanted to say, I also had this bug with 4.1.0 and after installing the develop version it is gone.

-Felix

**Closed** 2015-06-05 11:39 UTC
Labels: bug, Fixed awaiting release, Network
