### ISSUE TITLE
Edges overlap when physics is disabled

### ISSUE THREAD

**Issue by AlexETF** [almende/vis#2449] opened 2016-12-14 11:14 UTC
The behavior of network when physics is turned off suits the best for my application (it is possible to move nodes without dragging the rest of the network like when physics is enabled and default layout is used).

But, when physics is disabled, edges between nodes overlap. For example I create two nodes, and add multiple links between these two nodes. All edges will overlap. Is it possible to avoid overlapping ? When physics is enabled and smooth.type of edges is dynamic, edges do not overlap but behavior of network when physics is enabled, does not suit me well.

How to avoid overlapping of edges but keep the behavior of network like when physics is disabled ?

Thanks

**Comment by LLTommy** [comment] 2017-01-09 16:18
What you are looking for is not to use physics for the nodes but use physics for the edges. I don't know if there is a workaround, but did you try something like giving the nodes mass 0 - which might not include them in the physical model) while giving your edges a mass?

**Comment by mojoaxel** [comment] 2017-02-05 18:20
duplicate of #1957

**Closed by mojoaxel** 2017-02-05 18:20 UTC
Labels: Duplicate, Network, Problem
