### ISSUE TITLE
Network rotates crazy with force atlas solver

### ISSUE THREAD

**Issue by Tooa** [almende/vis#1321] opened 2015-09-25 09:25 UTC
Hi,

have a look at the following example [1] which is using the latest develop version. When dragging the network the graph will start to rotate and never stops. In addition one node is overlapping with the "Google" node. I also wonder why the node labels are missing. 

I tried the same data on the `imageWithBorder.html` example. There is works fine. Looks like the solver behaves strange then. Maybe the "avoidOverlap" option causes problems again. 

If you remove the solver, the graph looks like this [2], but the labels appear.

Best Uli

[1] http://jsbin.com/rusibinope/1/edit?html,output
[2] http://jsbin.com/gugehepuqo/1/edit?html,output

**Comment by AlexDM0** [comment] 2015-09-25 18:01
Hi,

The cause for rotation is the avoidOverlap. I'd suggest you do not use it, it shouldnt have been released in its current state.

You don't see labels because the graph is zoomed out, the font settings determine when the label is shown.

Regards

**Closed** 2016-01-04 10:00 UTC
Labels: Network, question
