### ISSUE TITLE
Network: Getting "undefined" error

### ISSUE THREAD

**Issue by dragonzone** [almende/vis#1416] opened 2015-11-05 14:59 UTC
We are starting to get this errors using v4.9

![la-vis-error](https://cloud.githubusercontent.com/assets/10065158/10971725/b87fe6b4-83a3-11e5-9ac1-edd981ef45f1.PNG)

**Comment by AlexDM0** [comment] 2015-11-05 15:09
Hi,

Seeing as our examples do not do this, can you reproduce this for us?

Cheers

**Comment by dragonzone** [comment] 2015-11-05 15:41
http://jsfiddle.net/x7oz3sc6/

**Comment by AlexDM0** [comment] 2015-11-05 16:46
It seems to be a bug in the improved layout algorithm. You can turn it off
so this will not happen. I'll look into the cause for future releases.

Cheers

**Comment by dragonzone** [comment] 2015-11-05 17:29
Are there any major performance or benchmark differences between the previous layout algorithm vs the "improved" ones?

**Comment by AlexDM0** [comment] 2015-11-05 17:59
For some graphs the stabilization is much fastest. Especially ones with less than 100 nodes.

**Comment by dragonzone** [comment] 2015-11-06 16:11
Turning off the improvedLayout seems to be working for now. Let me know once you've fixed it so I can switch back.

BTW, I've created a quick & simple app the relies on vis.js to generate an ERD diagram that I think you can also add as a showcase or place somewhere where you can use as a utility to view any DB relationship. I've place them here where you can pull them. (https://github.com/dragonzone/ErDiagram)

**Comment by AlexDM0** [comment] 2015-11-20 11:47
Hi Dragon,

I've pushed a fix for this issue. Thanks for reporting. 

I've benchmarked the improved layout for your case and in this specific network the improved layout actually causes a slowdown of a factor 2. For other networks I've noticed a speed up of about a factor 4. It depends on the interconnectivity of the network. If its is not very interconnected, there are great performance boosts.

Regards

**Comment by dragonzone** [comment] 2015-11-20 13:48
So, if I have a network with lots of interconnected nodes, then it would be slower to use the "improved layout"? What is the best way to calculate when to use the improved layout and when not to?

**Comment by AlexDM0** [comment] 2015-11-20 14:30
I don't know how to calculate it.. If youre unsure, just leave it off. If you have static(ish) networks, try both and time.

**Comment by dragonzone** [comment] 2015-11-20 14:37
Our nodes and edges are dynamically generated based on user's access and their search query. I'll just default to use the improved layout, if it fails, i'll switch it off as a workaround.

**Closed** 2015-11-27 15:37 UTC
Labels: bug, Fixed awaiting release, Network
