### ISSUE TITLE
fix: added 'module name' for grunt usage

### ISSUE THREAD

**Issue by kuehn-sba** [almende/vis#1997] opened 2016-07-29 18:56 UTC
in vis.js -->row 32: 

`define([], factory);`

change to:

`define('vis', [], factory);`

will fix following grunt error:
Uncaught Error: See almond README: incorrect module build, no module name

can you please fix, merge and update bower package? Thank you.

> see: https://github.com/requirejs/almond

**Comment by mojoaxel** [comment] 2016-08-01 11:21
The AMD definition is created by webpack. Webpack provides one single anonymous module definition. This is actually a compatibility problem between webpack and r.js.

@kuehn-sba Here are the options you have to handle this problem: https://github.com/almende/vis/issues/883#issuecomment-106725967

Duplicate of #883
@ludost There is no solution here. I think we can close this.

**Comment by ludost** [comment] 2016-08-01 11:30
Yes, duplicate. This one is closed.

**Closed by ludost** 2016-08-01 11:30 UTC
