### ISSUE TITLE
TypeError related to hammer code

### ISSUE THREAD

**Issue by felixhayashi** [almende/vis#1556] opened 2016-01-08 22:48 UTC
When bumping to v4.12.0 I get this error. In my case, it turns up when I open the network with the configurator enabled, but no clue what exactly is causing it.

**edit:** Has nothing to do with the configurator, solely happens when the manipulator toolbar is used. Please got to http://visjs.org/examples/network/other/manipulation.html and open the manipulation bar, this will trigger the error.

When switching back to v4.11.0, everything works fine again.

**Comment by josdejong** [comment] 2016-01-09 11:58
How to reproduce this error? I tried http://visjs.org/examples/network/other/configuration.html which does not give the error.

**Comment by felixhayashi** [comment] 2016-01-09 12:24
Hi @josdejong 

I'll try to isolate that bug.

**Comment by felixhayashi** [comment] 2016-01-11 10:52
Sorry, in a larger refactoring process at the moment but I'll get back to this issue as soon as I can.

**Comment by felixhayashi** [comment] 2016-01-11 17:51
Hi @josdejong and @AlexDM0 

this bug seems to be everywhere. Please got to http://visjs.org/examples/network/other/manipulation.html and open the manipulation bar, this will trigger the error!

-Felix

**Comment by felixhayashi** [comment] 2016-01-11 17:58
Seems like the `elem.hammer` property is reset to undefined after passing the guard `if(elem.hammer)`…

Otherwise I don't understand how this can happen after the check.

          if(elem.hammer){
            var _handlers;
            for(var k = 0; k < elem.hammer.length; k++){ // <-- error elem.hammer undefined!
              _handlers = elem.hammer[k]._handlers[event.type];

**Comment by felixhayashi** [comment] 2016-01-12 15:18
By the way, this has nothing to do with the configurator, but happens when the manipulator toolbar is used. I made this assumption before because I open the configurator from the toolbar.

**Comment by AlexDM0** [comment] 2016-01-13 09:41
Hi, 

@josdejong this seems to be in the propagatingHammer system. Maybe something does not work correctly with the new version of hammer? We upgraded hammer versions due to the deprecation message right?

Regards

**Comment by felixhayashi** [comment] 2016-01-13 10:27
Thanks @AlexDM0 and @josdejong for picking this up. @josdejong could you please compile the dist folder in develop so the fix is available for testing?

**Comment by josdejong** [comment] 2016-01-13 10:33
I've fixed the issue, though I'm not entirely through the bottom of the problem. The problem occurred because the touch event listener of the button was being removed during execution of a callback of this event. I still don't know which recent change caused this problem to pop up now, but I've made the code of `propagating-hammerjs` robust against it now.

I will update `/dist` (it's not hard though to build it yourself ;) ).

**Comment by felixhayashi** [comment] 2016-01-13 10:37
Hi @josdejong 

> The problem occurred because the touch event listener of the button was being removed during execution of a callback of this event.

Ah, k.

> I will update /dist (it's not hard though to build it yourself ;) ).

I know, but I have a custom build process that expects to be bound to a commit of the vis repo and loads the dist from there ;)

**Comment by josdejong** [comment] 2016-01-13 10:55
... so your custom build process could perfectly fine rebuild vis.js on the fly too, right ;).

I'm not really happy with polluting a source repository with distribution files but it's necessary for bower. But well, it works and has other advantages like you can use the lib directly from github.

**Comment by felixhayashi** [comment] 2016-01-13 16:53
Hi @josdejong 

works fine. Many thanks!

> ... so your custom build process could perfectly fine rebuild vis.js on the fly too, right ;).

Yes of course you are right, technically speaking that is no problem. But I decided to include Visjs as a git submodule so when repacking Visjs as TiddlyWiki plugin, the submodule is retrieved from your repo and the code is extracted from the `dist` folder. This keeps things simple and fast and does not require the installation and execution of several node modules just to receive the `dist/vis.js`.

> I'm not really happy with polluting a source repository with distribution files but it's necessary for bower. But well, it works and has other advantages like you can use the lib directly from github.

Maybe I am misunderstanding you here, but I always found it very useful that you include a dist folder to  allow plug'n'play and make referencing of the dev and the master versions in e.g. jsbins possible.

**Comment by josdejong** [comment] 2016-01-14 08:43
> Maybe I am misunderstanding you here, but I always found it very useful that you include a dist folder to allow plug'n'play and make referencing of the dev and the master versions in e.g. jsbins possible.

True, it's definitely important that users can immediately use and play around with your library, including the latest develop version. I don't think though that keeping the latest builds inside the *source code* is the right way for that, it pollutes your source code history terribly. 

For example yesterday I tried to figure out which recent changes could have introduced the problem of this issue, so I did go though the latest commit's. But it's hard to see the actual changes, because in almost every commit the largest part is taken up by changes in the dist folder. You really have to search around that to see the actual changes in the actual source files. For vis.js we don't use code reviews, but these would be painful too due to all the clutter. Merging the repo after a collegue has made changes always results in conflicts due to the committed and local dist folder. That's not really the idea of source code control you know. This article has a clear paragraph about the issue: [Why my team uses npm instead of bower](https://medium.com/@nickheiner/why-my-team-uses-npm-instead-of-bower-eecfe1b9afcb#5947).

I would love to set up some script that keeps the bundles in a separate repository, maybe to `gh-pages` like discussed [in this article](http://blog.kevinlamping.com/publishing-bower-components/), but this doesn't have a high priority as the current solution works.

**Comment by AlexDM0** [comment] 2016-01-14 08:59
The merge conflicts are easily solved though. Pick one and rebuild. 

I agree though a cleaner solution would be better (and in the process we could get an actual release script :)). 

Until then, I would argue we keep committing dist.

**Comment by felixhayashi** [comment] 2016-01-14 10:34
> For example yesterday I tried to figure out which recent changes could have introduced the problem of this issue, so I did go though the latest commit's. But it's hard to see the actual changes, because in almost every commit the largest part is taken up by changes in the dist folder. 

Ok, now I understood you. I thought you are against doing version control for dist files in general. I agree, it makes sense to host dist files on another branch. I have the same problem, I also generate jsdoc along with the source code so I end up with a billion doc files for every final commit. It completely spams my diff-view (at least at github).

> This article has a clear paragraph about the issue: Why my team uses npm instead of bower.

Thanks for sharing.

>  I would love to set up some script that keeps the bundles in a separate repository, maybe to gh-pages like discussed in this article, but this doesn't have a high priority as the current solution works.

Hmm, that is not a bad idea. gh-pages has the advantage that files are raw http-served and this way dist content doesn't need to be served using rawgit.com. On the other hand, semantically speaking, I would favour a dist branch over gh-pages because the gh-pages is usually containing all project docs – I mean, ideally, docs and "binaries" should also be separated in this utopia repo :)

**Comment by felixhayashi** [comment] 2016-01-14 10:34
> Until then, I would argue we keep committing dist. 

Yay!

**Closed** 2016-02-01 11:19 UTC
Labels: Fixed awaiting release, issue
