### ISSUE TITLE
[vis-network] move node crash javascript due to text inside and or 'widthConstraint'

### ISSUE THREAD

**Issue by Clemaul** [almende/vis#3432] opened 2017-09-10 14:07 UTC
vis network
version : 4.20.1
firefox
OS : windows 8.1

some nodes can move well by clicking on them 
others nodes crash vis.js javascript 
check my example here  https://jsfiddle.net/Clemaul/5Lrgktjn/21/
you can try to move "Environnement de développement graphique" node or "logique de programmation" , it will crash, but "SQL" node works well.

i think is due to the text inside node and/or 'widthConstraint' parameter  the problem ...

**Comment by Clemaul** [comment] 2017-09-10 16:25
problem append here :  vis.js

lign : 37824
code : while (_w < _words.length) {

**Comment by wimrijnders** [comment] 2017-09-12 12:17
Duplicate of #3429.

As mentioned there, this is supposed to be fixed. You and the OP of #3429 have apparently found combinations of words that still manage to get the infinite loop going on `widthConstraint`.

I will use your example to test.

**Comment by wimrijnders** [comment] 2017-09-12 12:40
I can't get the example to stop when it's in the infinite loop. Would it be possible to make the example so  that does not auto-run?

**Comment by wimrijnders** [comment] 2017-09-13 06:30
I can confirm that this is fixed (with #3228) in the current development build:

![download 4](https://user-images.githubusercontent.com/769037/30362720-9d7836c0-985d-11e7-9433-0e4e06bf4557.png)

It will be in the next release.

FYI, I had to add the following in order to display the accented characters properly:

```html
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
```

**Comment by Clemaul** [comment] 2017-09-13 07:19
Thank's a lot ;)

**Comment by wimrijnders** [comment] 2017-09-13 08:06
If you're satisfied with the handling, please close the issue.

**Closed** 2017-09-13 08:23 UTC
Labels: Duplicate, Network, Problem
