### ISSUE TITLE
SCRIPT5009: 'vis' is undefined

### ISSUE THREAD

**Issue by MrGrj1010** [almende/vis#2972] opened 2017-04-11 14:14 UTC
I have some issues when I'm trying to integrate `vis.js` with Oracle APEX. I've posted an SO question [here](http://stackoverflow.com/questions/43340907/vis-js-vis-undefined-in-apex) and I gave all the details I had at the moment.

**Details about the environment:**

- Windows 7
- the latest version of `vis.js`
- IE 11.0.96

Summary:

- I've tried to downgrade `vis.js` to version `4.15` and the `Expected identifier, string or number` error disappeared. So I'm only left with `SCRIPT5009: 'vis' is undefined` error. I really don't know how to manage it or what I'm doing wrong. The code is linked in the SO question.

**Comment by wimrijnders** [comment] 2017-04-11 14:45
Hi, my knowledge of APEX is so limited, I didn't even know it existed.

From the link, I understand that the script itself works fine when used independently from APEX, so I really expect the issue to be on that side.

I hope for you that there are some APEX guru's hanging around here who can help you out.

**Comment by wimrijnders** [comment] 2017-04-13 15:20
Oh, yes, that one. I apologize for not thinking of that earlier. Well hunted!
For the bookkeeping:

----
Duplicate of #2912.

This is a bug with a priority fix. It will be fixed in the next release.
In the meantime, please just delete that weird character.

**Closed** 2017-04-14 09:09 UTC
Labels: Duplicate
