### ISSUE TITLE
Node overlapping with large labels

### ISSUE THREAD

**Issue by vcamaral** [almende/vis#2349] opened 2016-11-22 11:03 UTC
![vis_nodes_overlapping](https://cloud.githubusercontent.com/assets/860466/20521417/573e5bac-b092-11e6-89d2-8b5e8fd71298.PNG)

How can I solve this problem?

**Comment by vcamaral** [comment] 2016-11-22 17:08
@yotamberk can you help me?

**Comment by yotamberk** [comment] 2016-11-22 19:54
Sorry but I'm not really strong with the network section... I deal mostly with the timeline... 
I think you can maybe have a max-width for a node (with overflow hidden and word-break). That should solve the problem. There might be some kind of min-margin between nodes, I simply don;t know to be honest

**Comment by mojoaxel** [comment] 2016-11-23 08:40
@vcamaral  Use line breaks or `nodeSpacing`.

**Comment by mojoaxel** [comment] 2016-11-23 08:43
duplicate of #2326

**Closed** 2016-11-23 08:44 UTC
Labels: Duplicate, Network, Question
