### ISSUE TITLE
Timeline.focus only adjusts range and not the vertical placement

### ISSUE THREAD

**Issue by tinyels** [almende/vis#617] opened 2015-02-03 20:15 UTC
According to the documentation, `Timeline.focus` adjusts the visible window such that the selected item (or multiple items) are centered on screen. However, if you have a timeline with many items such that some are outside the viewport, calling focus with one of these items only adjusts the range of time displayed. It does not scroll to the requested item.

**Comment by josdejong** [comment] 2015-02-03 20:31
Thanks, good point. The focus should also adjust the vertical scroll position.

**Comment by carueda** [comment] 2016-11-18 04:12
Although #1846 was marked as duplicate of this one, seems to me that issue is actually closer to the desired behavior I still see lacking, which is to also **adjust vertical scroll in case the desired item is not visible**. I note that support for a **vertical scrollbar** was [just introduced](https://github.com/almende/vis/commit/b889a5057d027e8c94ac98f10b44c908dc1009d6) in vis 4.17.0 (the latest at time of writing).  

Anyways, I hope `.focus` will be enhanced to also pay attention to the vertical scroll. While this is implemented, I wonder whether anyone could suggest a workaround?  Thanks.

**Comment by yotamberk** [comment] 2016-11-18 06:06
You can use jquery scrollTop on the elements (vis-left and vis-centerContainer.) That should work in the mean time

**Comment by carueda** [comment] 2016-11-18 19:58
Thanks for the tip.  My particular project is not using jquery, though.

**Comment by jscudder** [comment] 2017-07-28 14:37
Could you please provide a small example of how you would use jQuery scrollTop to accomplish this?

**Comment by renancastro** [comment] 2017-09-03 22:50
Altough the other bug is more detailed this is the same as bug #2851

**Comment by Areson** [comment] 2017-09-29 06:27
Example of one way to work around this with jQuery and scrollTop: [jsFiddle](https://jsfiddle.net/Areson/z2rsyhow/)

**Comment by carueda** [comment] 2017-09-29 15:58
Thanks all that have suggested workarounds. Seems like I should include jquery in my project.

**Comment by yotamberk** [comment] 2017-09-29 16:24
Closing due to duplicate (#2851)

**Closed by yotamberk** 2017-09-29 16:24 UTC
Labels: Confirmed Bug, For everyone!, Timeline

**Comment by jscudder** [comment] 2017-09-29 16:26
Thankbyou for this well written example. I could not modify it to scroll to
a specific item though

**Comment by Areson** [comment] 2017-09-29 16:59
@jscudder I've updated the fiddle so you can specify an ID.
