### ISSUE TITLE
On mobile it's not possible to move an item between groups on the timeline

### ISSUE THREAD

**Issue by abariatti** [almende/vis#615] opened 2015-02-03 15:53 UTC
On a mobile device it's not possible to move an item from group to group on the timeline using drag and drop. It's possible to move it back and forth using drag and drop though. 

I've tested it on android chrome and native browser. I used this example : http://visjs.org/examples/timeline/09_order_groups.html

**Comment by josdejong** [comment] 2015-02-04 08:44
Thanks @GluedToTheScreen :)

You are right @abariatti, this issue is not yet fixed. This report is a duplicate of #443, I suggest we continue the discussion there.

**Closed by josdejong** 2015-02-04 08:44 UTC
