### ISSUE TITLE
A layout bug with no clue of reasons

### ISSUE THREAD

**Issue by qubotong** [almende/vis#2297] opened 2016-11-10 23:30 UTC
![image](https://cloud.githubusercontent.com/assets/6183742/20198494/d0de15f2-a759-11e6-913a-124f809020a8.png)

As the img above shows, some nodes are distributed very far away from others in horizontal. Any body know the reason of this sick layout?

I have a really complicated tree structure data, each node can has multiple parents and multiple children, and the image above only show few of the edges. If I include all edges, the results will be just a line and when I zoom in, all results are gone as following image shows.

![image](https://cloud.githubusercontent.com/assets/6183742/20198652/97b838ec-a75a-11e6-80b0-ce2823ce3617.png)

My option setting as follows:
  		layout: {
			hierarchical: {
				enabled:true,
				levelSeparation: 250,
				treeSpacing:10,
				nodeSpacing:150,
				direction: "DU",
				sortMethod: 'directed'
			}
		},

**Comment by qubotong** [comment] 2016-11-11 00:15
Here is the codes of the problem example in my github:
https://github.com/qubotong/vis/blob/96ff1b8d683215ecb405e7fbaab6df8855c27a09/examples/network/layout/problematic_hierarchicallayout.html

**Comment by mojoaxel** [comment] 2016-11-11 09:57
> Here is the codes of the problem example in my github:

Here is the running example: http://jsbin.com/bavojuy/1/edit?output

**Comment by qubotong** [comment] 2016-11-11 22:12
@mojoaxel thanks, any idea of the reasons of this?

**Comment by mojoaxel** [comment] 2016-11-13 20:05
> thanks, any idea of the reasons of this?

No, static layouts are quite complicated.
You could try increasing the `levelSeparation` thats brings the Network more "together".

I'll played around with your data and stumbled on multiple issues. I simply have not the time to get into the network layouting. Maybe we can find the problems over time and create simple demos to isolate them.

**Comment by wimrijnders** [comment] 2017-05-15 08:03
From the jsbin:

>There are **two problems**:
>(1) some nodes are distributed to very far away from others.
>(2) if uncomments all edges, then the zoom in will lead to no results at all. 

The issues are fixed by pending PR #3017. The resulting network now looks like this:

![download](https://cloud.githubusercontent.com/assets/769037/26047196/7743c2f4-3952-11e7-88e6-6947574dec1c.png)

This is much more structured and compact. But I'll admit I miss the elegant curves of the original a bit.

**Comment by wimrijnders** [comment] 2017-05-15 08:04
**Closing**, duplicate of #1735.

**Closed by wimrijnders** 2017-05-15 08:04 UTC
Labels: Confirmed Bug, Network
