### ISSUE TITLE
Dragging external events

### ISSUE THREAD

**Issue by aakashrathore** [almende/vis#2180] opened 2016-10-19 00:44 UTC
Hey,
First of all, great work! You have no idea how much this timeline has helped me in my projects.
Anyway, my question is, is there any way I could drag an external event(like "Eat Breakfast") and place it on the timeline (say 8:00am Oct14 2016)? I was going through the events(not the event I talked about in the previous line) of timeline and I couldn't find hovering or getting properties based on mouse's cursor on the timeline. for eg: we have the click event which returns the properties of the timeline (start, click location etc).
Is there a clickOut or hover or mouseX-Y event for the timeline so that when I am trying to drag an external event, I could place it inside the timeline base on my cursor's x and y coordinates inside the timeline. for eg: Dragging some timeEvent and then when I enter the timeline and drop it (say at 8:00am Oct14 2016), the event gets added to that particular time on the timeline. I know how to add external events and how drag and drop works, but I don't know how to get the properties when dropping the event. I'd appreciate any help.

Thanks!

**Comment by yotamberk** [comment] 2016-10-24 10:06
Sounds like a cool Feature Request! 
I was thinking of implementing this in the next few days. 
It's not going to be an easy task but if successful, it will be very useful!
I'll assign it to myself

**Comment by mojoaxel** [comment] 2016-10-28 08:10
duplicate of #1881

**Closed by mojoaxel** 2016-10-28 08:10 UTC
Labels: Feature-Request, Timeline
