### ISSUE TITLE
Broken rendering inside hidden divs (Network graphs)

### ISSUE THREAD

**Issue by mgrobelin** [almende/vis#449] opened 2014-11-18 14:26 UTC
Hy,

there was Bug https://github.com/almende/vis/issues/116 for the Timeline -->

Graphs aren't rendered correctly when inside an 'inactive' Bootstrap Tab.

I'm facing a very same problem with a Network graph now.

**Good:** Page loaded while graph beeing in 'active' Bootstrap tab "Relations"
![active](https://cloud.githubusercontent.com/assets/310107/5088794/a5d1dcde-6f36-11e4-93f3-072a5ee5e940.png)

**Bad:** Page loaded initially with 'active' Bootstrap tab not beeing that one with the graph, e.g. "Metrics". Afterwards clicked on tab "Relations".
![inactive_to_active](https://cloud.githubusercontent.com/assets/310107/5088849/e99439e4-6f36-11e4-8f30-096196c363c3.png)

**As you can see only the navigation elements are shown. The graph itself is missing.**

My graph options are as follows:
```
        var options = {
            height: '450px',
            navigation: true,
            keyboard: false,
            groups: {
                system: {
                    shape: 'box',
                    color: {
                        background: "#428bca"
                    },
                    fontColor: 'white',
                    fontSize: 12
                },
                running_service: {
                    shape: 'dot',
                    color: {
                        color: 'white',
                        border: "#428bca"
                    },
                    fontSize: 10

                }
            }
        };
```

**If I replace the Network with a Timeline graph, it's redrawn automaticially like mentioned in https://github.com/almende/vis/issues/116 .**

**Comment by AlexDM0** [comment] 2015-01-07 11:37
@josdejong Could you take a look at this?

**Comment by DanielViglione** [comment] 2015-01-17 00:46
Any luck on this? I am suffering the same issue with bootstrap tabs.

**Comment by ciccia** [comment] 2015-03-10 13:02
same for me

**Comment by utensil** [comment] 2015-03-13 13:53
Same problem for me, and I've created a fiddler to reproduce: http://jsfiddle.net/e905ssy5/

**Comment by utensil** [comment] 2015-03-13 14:48
Calling `redraw()` doesn't fix it: http://jsfiddle.net/utensil/tL6kLsga/3/

**Comment by utensil** [comment] 2015-03-13 14:58
I believe this is caused by incorrect canvas size calculation:

`#vis` works fine:

```
canvasBottomRight: {x: -201.41569628719768y: -298.85502765291767}, 
canvasTopLeft:{x: -201.41569628719768y: -298.85502765291767}
```

`#vis-hidden` doesn't:

```
canvasBottomRight: { x: Infinity, y: Infinity},
canvasTopLeft: { x: NaN, y: NaN }
```

**Comment by utensil** [comment] 2015-03-14 12:58
I've found a workaround for this bug. Just force `scale=1` when setting scale to 0. The code is at https://github.com/utensil/vis/tree/449-render-hidden-div/ .

The working fiddler is at http://jsfiddle.net/utensil/tL6kLsga/5/ . Caveats: The graph is rendered, but rendered outside of canvas(left-top corner), you have to drag it down-right into the visible area of canvas.

**Comment by AlexDM0** [comment] 2015-03-14 13:00
Hi all,

I'll include a proper fix for this in the 4.0 release. We expect 4.0 around April.

Regards,

Alex

**Comment by utensil** [comment] 2015-03-14 14:00
:+1:

**Comment by AlexDM0** [comment] 2015-04-22 14:36
I'm going by all things marked for v4 and checking if they are in yet. This one has been added. I'll mark it as done and close it on release of v4.

**Comment by MorganGeek** [comment] 2015-04-22 15:04
The suggested fix won't work in all case. In my case (with the fix), the graph was rendered but with very wrong coordinates (he was rendered with his center in the top left corner). So I've been forced to use a trick in order to move forward : I refresh the graph only when the user has the focus on the page/tab in which the hidden div is included. I expect a better solution, under the form of a proper fix in V4.

**Comment by AlexDM0** [comment] 2015-04-22 15:07
Which fix are you referring to? V4 has a proper fix, which is not copied from this page. It will require you to call a zoomExtent to center it when you show it though, it is the same mechanism that is performed initially to position the camera. The rest is taken care of by vis.

**Comment by MorganGeek** [comment] 2015-04-22 15:10
I was referring to the suggested fix of utensil, which I tried some weeks ago when I was facing the problem.

**Comment by utensil** [comment] 2015-04-23 02:48
@MorganGeek  Mine was just a workaround (with serious problem) to reveal the problem further, I wouldn't call it a fix. :wink:

**Comment by MorganGeek** [comment] 2015-04-23 16:06
ok, sorry for the exagered use of this word then :)

**Comment by AlexDM0** [comment] 2015-05-22 12:52
With the launch of v4, this issue can be closed. Remember to call the fit() function when showing the previously hidden network!

**Closed by AlexDM0** 2015-05-22 12:52 UTC
Labels: bug, Done, moved to 4.0, Network

**Comment by mgrobelin** [comment] 2015-10-28 11:55
@AlexDM0 works as described after updating to v4.9 and calling fit(). Thx! :+1:
