### ISSUE TITLE
Network: HTML formatted text in nodes disappears after setting new options

### ISSUE THREAD

**Issue by Steff1337** [almende/vis#3047] opened 2017-05-11 07:08 UTC
Hello,

i recently faced a problem while using the VisJS library. I created a network with some nodes that have HTML formatted text (bold and italic). That works fine so far, but when i change the options - e.g. to switch the direction of the network - the formatted part of the text dissapears.

I have setted up an [example on jsfiddle](https://jsfiddle.net/67tkkkks/2/).

The only workaround i found was calling the location.reload() method. But this only works if the options can be saved before the reload. In my case this works because i am using the library for a Vaadin addon which keeps the state inside a java object. If somebody knows a better solution i would be very pleased :). Reloading the whole page works this way but may be confusing to the user.

Thanks in advanced.

Regrads,

Steff

**Comment by wimrijnders** [comment] 2017-05-11 12:22
After some intensive debugging, I discovered that in the internal representation, field `vadjust` becomes undefined for any texts within tags. Because of this, the draw fails for these blocks.

The next step is to discover why this happens. But I suppose that a check can be placed in the draw location (ref: `Label.js method _drawText(), line 363`) to prevent this from happening.

In any case: confirmed.

**Comment by wimrijnders** [comment] 2017-05-11 13:06
I can trace the problem all the way down to the missing of the `defaultOptions` field in `NodesHandler`.

I'm sorry to report I have no easy fix for this. The problem is simple but sorting out how to fix it is non-trivial. The best fix I can offer you, is to re-pass the option definitions when you call `setOptions()`.

Unless you got vis.js from the repo and built it yourself, of course. In that case, I can give you a simple two-line fix for this.

**Comment by wimrijnders** [comment] 2017-05-11 13:35
According to the doc `vadjust` for the special fonts:

> Defaults to the base font's valign.

This would be in essence the issue here. It does not default to that value.

**Comment by Steff1337** [comment] 2017-05-12 06:45
Thanks again for your quick response :)

What do you mean by 

> re-pass the option definitions when you call setOptions()

Do you mean passing the whole options object with the changed values or do i have to pass something in addition?

Regards,

Steff

**Comment by wimrijnders** [comment] 2017-05-13 08:48
I've figured out a fix. Will make a PR soon.

**Comment by wimrijnders** [comment] 2017-05-13 09:03
> Do you mean passing the whole options object with the changed values

Yes, that's what I meant. But I tried to verify this and, unfortunately, it doesn't work. The only way to get this working properly is to fix some code (`Label.getFormattingValues()`).

**Comment by Steff1337** [comment] 2017-05-18 07:59
Thanks again :)

I will wait for the release and use my workaround until then.

**Closed** 2017-05-21 19:19 UTC
Labels: Confirmed Bug, Fixed awaiting release, Network
