### ISSUE TITLE
Network graph shifts each layer to the left.

### ISSUE THREAD

**Issue by JohnwMoody** [almende/vis#3008] opened 2017-04-22 21:16 UTC
When numerous layers are added to a network, each layer is shifted slightly to the left.

See: 
http://jsbin.com/qihipebeto/edit?html,output

I noted that in an older version (4.9.0) it appears to be more central:

http://jsbin.com/xipeqohuna/edit?html,output

Centrally aligned would be ideal, including centrally horizontal.

Kudos to the work, this is a fantastic project.

EDIT: 

Further example (v4.19.1) looks to just display a line http://jsbin.com/fobuloxayi/edit?html,output (Theres a network there I promise!)

Using (v4.9.0) it actually looks really good: http://jsbin.com/veqehewada/edit?html,output

EDIT v2:

Using (v4.10.0) is perfect: http://jsbin.com/kurukuxeza/edit?html,output

**Comment by wimrijnders** [comment] 2017-04-26 18:58
> Further example (v4.19.1) looks to just display a line

Well whoop-dee-doo, and another one. This particular report is a duplicate of #1735.

**Comment by wimrijnders** [comment] 2017-04-26 20:16
FWIW, I can get a pretty decent layout if I set the following options for `v4.19.1`:

```
            layout: {
                randomSeed: undefined,
                improvedLayout: true,          // <= Where it should be
                hierarchical: {
                    //improvedLayout: true,    // <= Wrong location!
                    edgeMinimization: false,   // <= Changed
                }
            },
            physics: {
              enabled: true,
	      stabilization: {
		iterations: 10000
	      }
	    }
```

![untitled](https://cloud.githubusercontent.com/assets/769037/25454738/c710bc3a-2acd-11e7-90bb-8542c6dea05a.png)

**Comment by wimrijnders** [comment] 2017-04-26 20:21
I have deduced in other issues that there is something awry with option `layout.hierarchical.edgeMinimization: true`, but it is evidently only part of the story. The initial positions of all the nodes is just way too spread out.

But with physics enabled, it can fix itself to something presentable, see previous comment.

**Comment by wimrijnders** [comment] 2017-04-27 10:36
The problem is in method `LayoutEngine._validatePositionAndContinue()`. By the looks of it, the method assumes a strict hierarchy, in which child nodes have only one parent.

By disabling the method, a decent network is shown for multiple parents as well, like image above.

**Comment by wimrijnders** [comment] 2017-04-27 10:39
@JohnwMoody, could you live with the following layout?

![untitled](https://cloud.githubusercontent.com/assets/769037/25479791/6dda8cc6-2b46-11e7-8a07-4d0cd796a156.png)

It's like your jsbin of `v4.10.0`, except left-aligned.

**Comment by wimrijnders** [comment] 2017-04-27 10:41
This find, BTW, definitely marks the issue as a duplicate of #1735. I am closing this issue and continuing the work there.

**Closed by wimrijnders** 2017-04-27 10:41 UTC
Labels: Network, Problem
