### ISSUE TITLE
Support custom network hierarchical sortMethod

### ISSUE THREAD

**Issue by dbkaplun** [almende/vis#2151] opened 2016-10-15 18:48 UTC
Looks like this was introduced as private code but never implemented: https://github.com/almende/vis/blob/6de24a283c0ef549c616470f53aaaf0cb1488f82/lib/network/modules/LayoutEngine.js#L332

My particular use case is a [displacy](https://demos.explosion.ai/displacy/) clone for sentence diagramming.

I propose that a function, akin to the first argument to [`Array#sort`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#Description), should be passed to specify custom node order. The compare function may have parameters (nodeA, nodeB, and possibly edge) and should return a positive, 0, or negative value to specify order.

**Comment by acmookey** [comment] 2016-11-03 16:00
@dbkaplun hi，i'm wondering did you implement your own custom sortMethod yet, I just have a similar requirement. I would be grateful if you can provide the code  for my reference.

**Comment by wimrijnders** [comment] 2017-04-30 10:42
This issue has been noted. As remarked, someone has already worked on the custom sorting function, but it has not been released yet. I will pick this up RSN.

Closing this issue as a duplicate of #528. Further work will be done there.

**Closed by wimrijnders** 2017-04-30 10:42 UTC
Labels: Duplicate, Feature-Request, Network
