### ISSUE TITLE
Graph3D

### ISSUE THREAD

**Issue by MarlioR** [almende/vis#1913] opened 2016-06-15 22:26 UTC
Very, very nice !
Apologies if my question is trivial !
Is it possible show multiple data sets within one container of a 3D chart ?

**Comment by cgrandfield** [comment] 2016-07-01 16:28
No. This is a pending feature request http://visjs.org/featureRequests.html

**Comment by mojoaxel** [comment] 2016-08-05 22:18
duplicate of #524

**Closed** 2016-08-05 22:18 UTC
Labels: duplicate, Graph3D, question
