### ISSUE TITLE
network.getSelectedEdges()

### ISSUE THREAD

**Issue by Chroedde** [almende/vis#2078] opened 2016-09-08 08:37 UTC
Hi,
is there a way to get the full details of a selected edge, e.g. by using network.getSelectedNodes()? At the moment I only get the id, but not title, no label, etc.
Thanks and best regards!

**Comment by Tooa** [comment] 2016-09-08 09:12
Why should you use ``network.getSelectedNodes`` to get information about the edge? Here's an [example](http://jsfiddle.net/771fox0o/22/) showing how to get all information about a edge when clicking on it. 

Your question is basically a duplicate of #2068 and I already told you the solution there. Please use Stackoverflow for questions in future and read the documentation!

**Comment by mojoaxel** [comment] 2016-09-08 21:42
duplicate of #2068

**Closed by mojoaxel** 2016-09-08 21:42 UTC
Labels: duplicate, Network, question
