### ISSUE TITLE
Arrow head of edge to node with icon shape  hides inside the icon

### ISSUE THREAD

**Issue by DeviNagaraj** [almende/vis#1056] opened 2015-07-02 07:50 UTC
Hi,

While creating a network with shape as icon arrow head goes inside the icon because of  icon's tranparency(I think).So arrow head is not visible in some times.Please give me a suggestion to overcome this issue.

**Comment by AlexDM0** [comment] 2015-07-02 07:58
Hi,

This issue has is a duplicate of #1039. It has been fixed on develop and will be released tomorrow. 

Regards

**Closed** 2015-07-02 07:59 UTC
Labels: bug, duplicate, Fixed awaiting release, Network

**Comment by DeviNagaraj** [comment] 2015-07-02 09:19
Hi

Ok thanks
