### ISSUE TITLE
Vis Timeline issue with vis-today and vis-even/vis-odd classes

### ISSUE THREAD

**Issue by vettesem** [almende/vis#2942] opened 2017-04-01 16:40 UTC
I think I have found an issue when using the autoResize option for Vis timeline. When the user zooms in past the hour marker threshold and the display changes to 15 minute increments the classes aren't being assigned correctly. Instead of continuing with the application of vis-today and vis-odd/vis-even, the class 'vis-todayvis-odd' or 'vis-todayvis-even' is attached.  I think it's clear that it is just a missed space.  This can be found by drilling down through the timeline container to the elements contains 'vis-timeline vis-bottom' then 'vis-panel vis-top' then 'vis-time-axis vis-foreground'. 

If there is anything else I can provide please let me know.

**Comment by yotamberk** [comment] 2017-04-01 20:32
duplicate of #2888 and fixed in #2909

**Closed by yotamberk** 2017-04-01 20:32 UTC
Labels: Confirmed Bug, Duplicate, Timeline
