### ISSUE TITLE
Network crashes when using numbers for labels in v3.9.1

### ISSUE THREAD

**Issue by Mekeymaker** [almende/vis#979] opened 2015-06-15 15:52 UTC
Graph is breaking. Can we discuss over email - I know issue and fix.

**Comment by AlexDM0** [comment] 2015-06-15 16:19
Hi,

I'd rather this be handled over here if that's ok with you. If you have the fix you can also do a pull request, although a little more information would be great :)

Regards,

Alex

**Comment by Mekeymaker** [comment] 2015-06-15 17:17
Hi Alex,Thanks for quick reply.  We are releasing product soon. Once product released will share details of product and graph. It really works well. Issue - If Label value is number then graph will not load.Changes are in below code - around line no. 20740Node.prototype.getTextSize = function(ctx) { if (this.label !== undefined) { ctx.font = (this.selected ? "bold " : "") + this.options.fontSize + "px " + this.options.fontFace; this.label = this.label.toString(); var lines = this.label.split('\n'), height = (Number(this.options.fontSize) + 4) * lines.length, width = 0;for (var i = 0, iMax = lines.length; i < iMax; i++) { width = Math.max(width, ctx.measureText(lines[i]).width); }return {"width": width, "height": height, lineCount: lines.length}; } else { return {"width": 0, "height": 0, lineCount: 0}; } };Let me know you have any issue.Rds,SuyogOn June 15, 2015 at 12:19 PM Alex <notifications@github.com> wrote:Hi,I'd rather this be handled over here if that's ok with you. If you have the fix you can also do a pull request, although a little more information would be great :)Regards,Alex—Reply to this email directly or view it on GitHub.  Thanks,Suyog

**Comment by AlexDM0** [comment] 2015-06-15 19:29
Hi,

Labels are supposed to be strings. If you are using numbers, wouldn't it be better to typecast them to strings before putting them in? Putting them in the inner loop can be a waste of performance, I'd argue that typecasting inside the setOptions would be better. 

We will not release before at least the end of next week so if you are in a rush I'd suggest you make a fix locally. The network shouldn't crash so I'll fix this before our next release. 

Regards,

Alex

**Comment by Mekeymaker** [comment] 2015-06-16 16:14
All right Thanks Alex.On June 15, 2015 at 3:29 PM Alex <notifications@github.com> wrote:Hi,  Labels are supposed to be strings. If you are using numbers, wouldn't it be better to typecast them to strings before putting them in? Putting them in the inner loop can be a waste of performance, I'd argue that typecasting inside the setOptions would be better.   We will not release before at least the end of next week so if you are in a rush I'd suggest you make a fix locally. The network shouldn't crash so I'll fix this before our next release.   Regards,  Alex     > On 15 jun. 2015, at 19:18, Mekeymaker <notifications@github.com> wrote: >  >  >  > Hi Alex,Thanks for quick reply. We are releasing product soon. Once product released will share details of product and graph. It really works well. Issue - If Label value is number then graph will not load.Changes are in below code - around line no. 20740Node.prototype.getTextSize = function(ctx) { if (this.label !== undefined) { ctx.font = (this.selected ? "bold " : "") + this.options.fontSize + "px " + this.options.fontFace; this.label = this.label.toString(); var lines = this.label.split('\n'), height = (Number(this.options.fontSize) + 4) * lines.length, width = 0;for (var i = 0, iMax = lines.length; i < iMax; i++) { width = Math.max(width, ctx.measureText(lines[i]).width); }return {"width": width, "height": height, lineCount: lines.length}; } else { return {"width": 0, "height": 0, lineCount: 0}; } };Let me know you have any issue.Rds,SuyogOn June 15, 2015 at 12:19 PM Alex <notifications@github.com> wrote:Hi,I'd rather this be handled over here if that's ok with you. If you have the fix you can also do a pull request, although a little more information would be great :)Regards,Alex—Reply to this email directly or view it on GitHub. Thanks,Suyog > — > Reply to this email directly or view it on GitHub. > —Reply to this email directly or view it on GitHub.  Thanks,Suyog

**Comment by AlexDM0** [comment] 2015-06-18 17:03
Hi,

I cannot reproduce this. Can you make a jsbin to show the problem?

Regards,

Alex

**Comment by Mekeymaker** [comment] 2015-06-18 17:31
No worries Alex. i have fixed in my local and changes working fine. It's hard at this moment create jsbin, but once i have something share with you.Rds,SuyogOn June 18, 2015 at 1:03 PM Alex <notifications@github.com> wrote:Hi,I cannot reproduce this. Can you make a jsbin to show the problem?Regards,Alex—Reply to this email directly or view it on GitHub.  Thanks,Suyog

**Comment by AlexDM0** [comment] 2015-06-18 17:31
What version of vis are you using?

**Comment by Mekeymaker** [comment] 2015-06-18 17:36
@version 3.9.1 * @date 2015-01-22On June 18, 2015 at 1:31 PM Alex <notifications@github.com> wrote:What version of vis are you using?—Reply to this email directly or view it on GitHub.

**Comment by AlexDM0** [comment] 2015-06-18 17:37
I see, in that case, it's fixed in the v4 releases.

Regards,

Alex

**Closed** 2015-06-18 17:37 UTC
Labels: bug, Network, question

**Comment by Mekeymaker** [comment] 2015-06-18 17:42
Okie. Thats good news. i will update to 4On June 18, 2015 at 1:37 PM Alex <notifications@github.com> wrote:I see, in that case, it's fixed in the v4 releases.Regards,Alex—Reply to this email directly or view it on GitHub.  Thanks,Suyog

**Comment by AlexDM0** [comment] 2015-06-18 17:43
The v4 release is breaking so you may have to rework your current setup a bit. The docs and examples have all been redone to suit the v4 release. We do not support the v3 branch any longer.

Regards,

Alex
