### ISSUE TITLE
Image vs Icon

### ISSUE THREAD

**Issue by mdcanham** [almende/vis#2408] opened 2016-12-05 00:23 UTC
I was wondering if anyone can provide me with some insight into the difference in rendering with images and rendering with icons (SVGs).

Currently I am producing graphs that are on the order of 1500 objects and when I use 'icons' the performance is good, when I use 'images' (PNGs) the performance is terrible, even when the image is the same on all nodes.

Obviously rendering a PNG is going to use more resources than an SVG but I was wondering if anyone has encountered this issue and found a way to improve performance when rendering PNGs for the node images, particularly when the images are all the same?

**Comment by yotamberk** [comment] 2016-12-05 16:49
What happens if you try to use a smaller png? doe sit improve?

**Comment by mdcanham** [comment] 2016-12-05 22:13
@yotamberk This does improve performance, it is still slower than when using SVGs. Currently aiming to produce graphs on the order of 20K+ objects in which case even 1x1 PNGs are causing the graph to perform slowly.

**Comment by yotamberk** [comment] 2016-12-06 08:14
I think the problem is reloading the image to the canvas over and over. I've read somewhere that png images should be cached in canvas, especially if reusing that image. We might need to implement caching node images... @Tooa or @eymiha do you have any insights to do this?

**Comment by zheyong91** [comment] 2017-01-26 07:45
Hi all, i am facing the same issues as well. Adding close to 1k nodes on the canvas with custom images push the memory usage of the browser to almost 2gb. Is there any fix for this?

**Comment by mdcanham** [comment] 2017-01-26 07:47
@zheyong91 I settled for using PNGs until someone has the time to look into this. As far as I am aware it is not resolved at this point.

**Comment by zheyong91** [comment] 2017-01-26 07:56
@mdcanham ic ok. Have you encountered a situation where the memory usage is close to 2gb because of images?

**Comment by mdcanham** [comment] 2017-01-26 08:05
@zheyong91 No I have never encountered memory usage on that level. I am using images for the nodes that are only on the order of KBs (64x64 PNGs). 

Based on the numbers that you have given each of your node images must be on the order of 1-2MB. If this is true then I would start by reducing the size of your node images, do they need to be that big.

Also are the images that you are using able to be represented by a simple SVG icon? If they are then I would recommend switching to SVGs for far better performance. What I did was modify the graph so that when you are zoomed out you see the SVG icons and when you zoom in past a certain point you will see the actual images. This improves performance significantly as when zoomed in only a small number of images are displayed on the screen which means less rendering work to be done. I can't say whether or not this 'fix' imporves memory performance or not.

**Comment by zheyong91** [comment] 2017-01-31 06:20
@mdcanham ic thank you for your help, managed to solve it by using font awesome as an alternative.

**Comment by wimrijnders** [comment] 2017-04-21 09:28
Duplicate of #2952. I will put further discussion of image performance in that issue.

**Comment by wimrijnders** [comment] 2017-04-29 11:59
Solution pending with PR for #2952. As a workaround, you can disable interpolation:

```
nodes: {
  shapeProperties: {
    interpolation: false    // 'true' for intensive zooming
  }
}
```
This skips the code causing the performance issues, at the expense of perhaps worse-looking images.

Closing this issue.

**Closed by wimrijnders** 2017-04-29 11:59 UTC
Labels: Network, Problem
