### ISSUE TITLE
To divide the library into separate modules

### ISSUE THREAD

**Issue by grimalschi** [almende/vis#3270] opened 2017-07-18 10:15 UTC
I think it's not easy to find maintainer because he should control 5 different modules.

I use timeline, and I don't want to have extra modules in my project. Timeline is valuable in itself.

And I don't care about other modules.

Maybe it can be more easy to find several maintainers for 5 modules, than 1 maintainer for a whole library?

And I think it would be more pleasant to use only one special module you want.

My idea is to make different repositories for each module of visjs.

1 - visDataSet.js
2 - visGraph2d
3 - visGraph3d
4 - visNetwork.js
5 - visTimeline.js

And to develop them separately.

**Comment by wimrijnders** [comment] 2017-07-18 10:24
Duplicate of #2405.

You're not the first to think of this. Eventually, it will happen, if we sort out the handling of it.
But I understand your concern. Perhaps, as an interim solution, `timeline` could be isolated as a separate deliverable. @yotamberk, would this be possible?

**Comment by wimrijnders** [comment] 2017-07-18 11:06
> Maybe it can be more easy to find several maintainers for 5 modules, than 1 maintainer for a whole library?

There are several maintainers already. However, they are not all available all the time and even then, there are not enough to fully handle everything that needs to be done. It really is a serious problem, we're totally understaffed here (hint, hint).

If we have this problem for 1 project, then I'm very very skeptical that it will be easier for 5 projects. From my point of view, it's the situation we have now times 5.

**Comment by bradh** [comment] 2017-07-21 09:39
Closing as duplicate.

**Closed by bradh** 2017-07-21 09:39 UTC
Labels: Duplicate, Feature-Request
