### ISSUE TITLE
VisJS: Improve rendering time for dynamic nodes(5 to 5000 nodes)

### ISSUE THREAD

**Issue by gowti1992** [almende/vis#3278] opened 2017-07-21 10:14 UTC
I have a requirement to display dynamic nodes(5 to 5000)when user double click any of the existing nodes.

When number of child node is more than 100, my network taking more time to stabilize. I am not sure how many child nodes i will get for that selected node. so, I cant use `storePosition()`.

Can someone suggest me how to precalculate node positions or some other idea which will improve my rendering time?

Please find my configuration and code sample below

```js
 physics: {
  barnesHut: {
    gravitationalConstant: -2000,
    centralGravity: 0.3,
    springLength: 95,
    springConstant: 0.04,
    damping: 0.09
 },
maxVelocity: 146,
solver: 'barnesHut',
timestep: 0.35,
stabilization: {
    enabled: true,
    iterations: 2000,
    updateInterval: 25
}
}
```

[Plunker:Sample app which will load 5000 nodes dynamically](https://plnkr.co/edit/3PF4X4TznVqCJxJOWKC9?p=preview)

**Comment by wimrijnders** [comment] 2017-07-21 11:04
Duplicate of #2906, #3240 and others.

This is a running question. First off, please accept the fact that monster-networks just plain take a longer time to render. Scan the issues mentioned above for ideas on how to improve the performance.

> Can someone suggest me how to precalculate node positions....

If you mean 'calculate the node positions before they are sent to the base', i.e. on the server, this is currently not possible. However, for the next release, the components will be in place to make that work; it *will* be possible and I guess I should write up a HOWTO of some kind for it.

Short answer: use modules `jsdom` and `canvas` for off-line rendering.

... but I won't endorse this until I'm totally sure it works as expected (I'm busy setting up unit tests for/with them).

If that is not the question, please elaborate.

> ... or some other idea which will improve my rendering time?

From #3240, redacted:

I've been accumulating empirical observations during usage to increase the performance, such as:

- Doing stabilization is orders of magnitude faster than displaying the network
- Edge type `dynamic` is more computing intensive than the rest
- The `barnesHut` solver is way slower than the other ones
- increasing 'timestep'  in `physics` stresses out the processor less; it also makes for more nervous networks

These are the best guidelines I can give you right now.

**Comment by gowti1992** [comment] 2017-07-23 05:30
@wimrijnders  Thanks you so much for your suggestion.

It helps me a lot.

I have noticed network stabilization is much faster for the first time. 

I have tried loading 500 nodes during initialization which is taking few sec to stabilize(no node movement on screen). But if i add same 500 nodes on double click of a node(already rendered) it is taking more than 2 mins to stabilize(nodes keep moving on screen).

Currently, i am using nodes.add([nodeObject]) on double click of a node. If i change it to network.setData({nodes:nodes.add([nodeObject]), edges:edges.add([edgeObject])}) and it is much faster but it is re-rendering the whole network which i cant use all the time

It will be helpful if you suggest me how to achieve same effect of network.setData in nodes.add() or Did i missing anything before i do nodes.add()?

**Comment by wimrijnders** [comment] 2017-07-24 06:01
> But if i add same 500 nodes on double click of a node(already rendered) it is taking more than 2 mins to stabilize(nodes keep moving on screen).

OK, so that's not the actual stabilize routine running, the 'stabilization' is happening on-screen. Do an explicit call of `network.stabilize(iterationCount)` directly after loading the data. This will disable the screen updating for the number of iterations and should be much, much faster.

> Currently, i am using `nodes.add([nodeObject])` ... It will be helpful if you suggest me how to achieve same effect of `network.setData()` ...

`nodes.add()` does a view refresh after every single call. If you're doing this 500 times in a row, yes, it's going to be slow and it won't even be stabilized.

Options for dealing with this:
- *Easiest:* pass all 500 nodes in a single call by putting the all in the array parameter, e.g.: `nodes.add([nodeObject0,...,nodeObject499])`
- *Nifty:* Use the `queue` option for `DataSets` to delay updates of data and handle them in batches, see the [DataSet documentation](http://visjs.org/docs/data/dataset.html).
- *Not so good:* Put the data update between `network.stopSimulation()` and `network.startSimulation()`. This saves on the calculation of physics during addition of new nodes.

It's possible to combine all three options for maximum effect. This plus the explicit call to `stabilize()` should make a world of difference.

**Comment by gowti1992** [comment] 2017-07-24 07:38
@wimrijnders  Thank you so much.

network.stabilize(iterationCount) is what i was missing. Now i can see the changes which is much much faster than before.

And, i am already storing the dynamic nodes in an array before nodes.add();

Thanks a lot.

**Closed** 2017-07-24 07:38 UTC
Labels: Network, Question
