### ISSUE TITLE
TypeError: util.elementsCensor is not a function

### ISSUE THREAD

**Issue by dmitrirussu** [almende/vis#3026] opened 2017-05-02 10:11 UTC
http://visjs.org/examples/timeline/other/hidingPeriods.html

TypeError: util.elementsCensor is not a function
http://visjs.org/dist/vis.js
Line 28690

**Comment by bradh** [comment] 2017-05-02 10:42
Duplicate of https://github.com/almende/vis/issues/2918 resolved by https://github.com/almende/vis/pull/2947.

**Closed by bradh** 2017-05-02 10:42 UTC
