### ISSUE TITLE
Direction Hierarchies With Multiple Chains

### ISSUE THREAD

**Issue by programster** [almende/vis#730] opened 2015-03-22 14:54 UTC
If one creates a graph with an automatic "direction" hierarchy with the following in the configuration option:
```
hierarchicalLayout: { layout: "direction" }
```
...then one currently cannot have multiple "chains" of nodes. All nodes have to be connected to each other, directly or indirectly. Otherwise the viewer is left with a blank page. This also means that as soon as one adds a node to such a hierarchy, the graph disappears, because the node that is added will start out not being connected to anything.

However, if one changes to a "hub" based hierarchy, then the user can view a setup similar to the following layout:

![selection_178](https://cloud.githubusercontent.com/assets/5709838/6769851/fff038b4-d0a2-11e4-9420-e5d2e69b87a3.png)

Tested in chromium and firefox.

**Comment by AlexDM0** [comment] 2015-03-23 09:30
Hi,

At the moment the hierarchical system is only ment for single connected networks. The fact that the hubsize does show something is more of a fluke than intended behaviour. The physics systems doing the sorting also do not really support multiple unconnected networks. 

I'll see if I can improve on this in the next big iteration of the network. 

Regards,

Alex

**Comment by AlexDM0** [comment] 2015-03-23 17:18
This has been fixed in 4.0. We expect 4.0 around April.

Regards,

Alex

**Closed** 2015-03-23 17:18 UTC
Labels: moved to 4.0, Network, question

**Comment by programster** [comment] 2015-03-23 19:45
Thats great news!
