### ISSUE TITLE
selectEdge fired when user select a node

### ISSUE THREAD

**Issue by JonathanGeoffroy** [almende/vis#1144] opened 2015-07-31 12:33 UTC
When user selects a node by clicking it, the *selectEdge* function is fired too (for any node which have at least an edge). However, the doc says: "Fired when a edge has been selected **by the user**." In this case, the edge has been selected, but not by the user.

Is it a bug, or a documentation problem ? 

In my case, I can distinguish if the edge is selected because user clicked on it, or just because the edge is connected to the selected node.

Regards.

**Comment by JonathanGeoffroy** [comment] 2015-08-03 09:15
Moreover, it seems the *selectEdge* handler is not fired if a node is selected. Here is a way to reproduce the problem:

1. select a node. The *selectEdge* handler is fired, and each edge connected to the selected node is found in parameter.
2. select an edge which isn't connected to the selected node: the network is refreshed (so we see different edges in bold), but the *selectEdge* handler is NOT fired.

**Comment by AlexDM0** [comment] 2015-08-03 09:29
Hi Jonathan,

The intended behaviour is that it should only fire if the user clicks on an edge. I will fix this soon (its kind of busy at the moment).

Regards

**Comment by JonathanGeoffroy** [comment] 2015-08-03 12:57
Hello,

I sent a PR which works for my case. Note that I tested manually for single selection, only quickly for multiSelection, and not at all for clusters ...

So my solution may not be the best way for your project: feel free to ask for any improvement, or deny the PR if you don't find it enough good.

Regards.

**Comment by AlexDM0** [comment] 2015-08-29 10:09
fixed in 4.8

**Closed by AlexDM0** 2015-08-29 10:09 UTC
Labels: bug, Fixed awaiting release, Network
