### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by ddesna** [almende/vis#3058] opened 2017-05-16 07:30 UTC
I'm using Vis.js network for my project, and I have seen that when I'm displaying the network, CPU usage is increasing drastically (from 5% to 25-30%).
I have measured the performance and I have seen that nodes has been redrawed each second.
![image](https://cloud.githubusercontent.com/assets/10425077/26094374/11da7264-3a1a-11e7-94e5-18b865103e41.png)

It is possible that I'm making bad use of Vis.js or its normal performance for it ?

Thanks.

**Comment by wimrijnders** [comment] 2017-05-16 07:48
Hi there, are you using images, svg or icons in your nodes?

In that case, this is a known problem (see #2952), and PR #3010 will fix this.
If not, please supply an example in `jsfiddle` or suchlike.

**Comment by wimrijnders** [comment] 2017-05-16 08:20
> I have seen that nodes has been redrawed each second

It's likely more often than that. The nodes get redrawn on the canvas every time something changes in the visualization.
The question is not that they are redrawn often, but that they should be redrawn efficiently.

**Comment by ddesna** [comment] 2017-05-16 08:20
Thanks for the quick response @wimrijnders. Yes, each node have SVG icon (with some animation, like blinking), and I'm displaying like 122 nodes and 162 edges at the same time.
In my case, CPU usage is increasing just showing the network, without making zoom or draging the nodes.
Also, making debug, I have seen that `_startRendering` function is called very frequently (each second or less).

Do you think that  #3010 will solve my CPU performance issue ?

Thanks.

**Comment by wimrijnders** [comment] 2017-05-16 08:26
> Do you think that #3010 will solve my CPU performance issue ?

Absolutely! It's going to make a huge difference.
But, to check if you have the same issue as #2952, could you try the following please?

In your options, set:

```
nodes: {
  shapeProperties: {
    interpolation: false
  }
}
```

...and then see if the performance improves. You can then also use it as a workaround for now.

**Comment by ddesna** [comment] 2017-05-16 10:37
@wimrijnders I have tryed to use `interpolation: false` and I have not noticed the change in performance. It's still using 25-30% of CPU :(
Also I have builded #3010 and unfortunetly it doesn't solve my problem.
Maybe I need to pass some extra options ?

This is what I'm passing to options:
```json
{
   "autoResize": true,
   "height": "100%",
   "width": "100%",
   "locale": "en",
   "clickToUse": false,
   "interaction": {
      "dragNodes": true,
      "dragView": true,
      "hideEdgesOnDrag": false,
      "hideNodesOnDrag": false,
      "hover": true,
      "multiselect": false,
      "navigationButtons": true,
      "selectable": true,
      "selectConnectedEdges": true,
      "tooltipDelay": 300,
      "zoomView": true
   },
   "physics": {
      "enabled": true,
      "barnesHut": {
         "gravitationalConstant": 0,
         "centralGravity": 0,
         "springLength": 0,
         "springConstant": 0,
         "damping": 0,
         "avoidOverlap": 0
      },
      "maxVelocity": 0,
      "minVelocity": 0,
      "solver": "barnesHut",
      "timestep": 0.01,
      "adaptiveTimestep": true
   }
}
```
And this is the example of one of the nodes:
```json
{
   "borderWidth": 1,
   "borderWidthSelected": 2,
   "font": {
      "color": "#343434",
      "size": 16,
      "face": "arial",
      "background": "red",
      "strokeWidth": 0,
      "strokeColor": "#ffffff",
      "align": "center"
   },
   "hidden": false,
   "id": "115",
   "image": "assets/icon.svg",
   "label": "Element",
   "labelHighlightBold": true,
   "mass": 1,
   "physics": true,
   "shape": "image",
   "size": 25,
   "x": 669,
   "y": 679
}
```

**Comment by wimrijnders** [comment] 2017-05-17 14:11
If it's not the image interpolation issue, I can't tell what the problem is. I see nothing out of the ordinary in the extensive options you gave.

Could you please make an example illustrating the problem in `jsfiddle` or suchlike? That would simplify making an objective evaluation.

**Comment by ddesna** [comment] 2017-05-22 07:41
Hi @wimrijnders, please, check this [JSFiddle](https://jsfiddle.net/g9jqheLd/). If you open Chrome Task Manager (Shift+Esc) you will see that when this JSFiddle tab is active, CPU usage is over 25-30%.

**Comment by wimrijnders** [comment] 2017-05-22 09:25
Thank you for taking the time to make the `jsfiddle`, I appreciate it.

**Aside:** You say 'over 25-30%'; on my dev machine it goes over 98%! I have a 3Ghz i7 here, which I thought was blazing fast. You must have some major kick-ass machine!

Looking at the data and code, I see:

- Coordinates are already supplied with the nodes; there's no reason to enable `physics` at all
- In addition, all options for `physics` have been set to zero, so the physics module has zero effect

I propose to just turn `physics` off in your case:

```
    var options =
    {
...
    	"physics": {
    		"enabled": false
    		},
...
    	},
...
    };
```

This is far and away the easiest solution for the performance issue. When I do nothing in the page, CPU usage drops to a nice 0.0%.

Hope this helps. In the meantime, I'll have a look why the usage was so high in the first place.

**Comment by ddesna** [comment] 2017-05-22 10:34
Thank you so much ! You have a right, turning off `physics`, drops CPU usage to 0.0% :tada:

**Comment by wimrijnders** [comment] 2017-05-22 10:34
> In the meantime, I'll have a look why the usage was so high in the first place.

Well, nothing really out of the ordinary  is happening in the `_draw()` routines of the edges and nodes. They just get called often. There is no quick and easy fix here.

I do note, however, that if I set non-zero option values for the physics, the CPU usage eventually stabilizes to 0.0%. There might be a problem with the physics determining when it is done.

**Comment by wimrijnders** [comment] 2017-05-22 10:47
My sincere pleasure! Always glad to be helpful.

**Comment by wimrijnders** [comment] 2017-05-22 10:48
Please close the issue if you're happy with the result!

**Closed** 2017-05-22 11:37 UTC
Labels: Network, Problem

**Comment by ddesna** [comment] 2017-05-22 14:27
**Just for information:**
I have noticed that dragging nodes is working very slowly in Firefox when `option.physics.enabled` is `false`.
In Chrome and Internet Explorer (:laughing:) nodes dragging works perfectly smooth.

**Comment by wimrijnders** [comment] 2017-05-22 14:41
OK. Just tried it, to be honest I don't notice any difference at all.
