### ISSUE TITLE
[enchancement] more options for the edges' endings

### ISSUE THREAD

**Issue by kagestrife** [almende/vis#1993] opened 2016-07-27 21:07 UTC
Other than just an arrow, could we get a circle, a rectangular, etc? This may be trivial, but it's a really important feature, due to the use of different symbols in various graphical standards (i.e. in biology).
I am using the visNetwork library (R Shiny) and the mods there directed me here, to the vis repository.

**Comment by mojoaxel** [comment] 2016-07-28 07:30
@kagestrife Good Idea! What kind of symbols would you like/need?

**Comment by kagestrife** [comment] 2016-08-24 11:49
@mojoaxel Hi and sorry for the late response, I was on vacation and could not comment ASAP.

About the edges' endings, what I would like to be added is an " O ", an " X ", a " | ", a rectangular and maybe a tail " < ".

Let me know if it is doable, and thank you for the help. If I come up with other ideas, I will let you know.

**Comment by mojoaxel** [comment] 2016-08-25 12:55
@kagestrife Do you maybe have any demo chart for this kind of biological data? We would need to create an example for this and "real" data would be nice.

This enhancement could be done in about 1-3 hours. If I see a nice use case for this maybe I'm willing to spend the time ;-)

**Comment by kagestrife** [comment] 2016-08-26 09:16
@mojoaxel It's a particular algorithm that needs this set of icons. An example of a graph like this is: https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQRB1FsCKIoUPKIhSTGNiFMR2BrITt9bxhBZB7ul3dfzx3gSUtabw

Where instead of circles, X's or |'s might be needed. Also, let us know when the updated version is available. A simple short example on how to use it, would be more than helpful as well.

**Comment by mojoaxel** [comment] 2016-08-26 11:01
@kagestrife Is this an official diagram type? Has this type maybe even a name? Where is it used? I'm asking because it would be much more interesting to provide a often used diagram type instead of implementing something just for you :-)

**Comment by kagestrife** [comment] 2016-08-26 11:28
@mojoaxel Yes, its an official diagram type and its called "Partial Ancestral Graphs". 
https://en.wikipedia.org/wiki/Ancestral_graph
There are some algorithms (such as FCI on the package pcalg) that output such graphs, which may use circle endpoints to indicate ambiguous orientations.
But, beyond that, we (or another user) may need some different end points for the edges that are not currently under a known network, such as the ones we were referring before.

**Comment by mojoaxel** [comment] 2016-09-02 10:46
I still have problems finding a definition or something about these "Ancestral Graphs". There are no examples of the symbols you described. 

I could take the time to implement this new feature but I would need a specific definition what kind of symbols you want to use and what they should represent.

If that is just something for one specific project, than you must find another way (e.g. drawing an the chart yourself). Sorry.

**Comment by kagestrife** [comment] 2016-09-02 13:39
@mojoaxel , Thanks for your answer.

What we need exactly, is just a different ending point (a small circle instead of an arrow) for some of our network edges, regardless of the type of the network or  the method being used.
Just for the record, this is going to be used for the output of the FCI algorithm (R package pcalg, https://cran.r-project.org/web/packages/pcalg/pcalg.pdf).
The circle end-point on an edge represents an ambiguous orientation.
This is a research academic project and the only new feature we need by you is to just give us the ability to use a circle end-point on some edges instead of the classic ones that you already have in your implementation. Is this feasible?

Thanks a lot for your time and regards.

**Comment by mojoaxel** [comment] 2016-09-04 08:40
I'll try to look into this. But I can't promise to do that in the next days...

**Comment by mojoaxel** [comment] 2016-10-03 11:02
this is actually a duplicate of #1444 , but lets keep it open until @kagestrife has what he needs.

**Comment by mojoaxel** [comment] 2016-10-17 12:09
@kagestrife The edge ending "circel" is now implemented in the "develop" branch. Can we close this issue or do you need more edge endings?

**Comment by kagestrife** [comment] 2016-10-17 12:17
@mojoaxel I think for the time being we do not need anything else. Thanks for the help.

**Closed** 2016-10-17 12:17 UTC
Labels: duplicate, enhancement, Fixed awaiting release, Hacktoberfest, Network
