### ISSUE TITLE
Network - Navigation Zoom is broken (4.18)

### ISSUE THREAD

**Issue by Kokozzi** [almende/vis#2613] opened 2017-01-22 07:49 UTC
After #2377 commit to 4.18 Zoom events for Navigation at Network module are broken. Example of it is active at official example page - http://visjs.org/examples/network/other/navigation.html

`Uncaught ReferenceError: pointer is not defined` - when trying to zoom in or zoom out with help of bottom buttons.

**Comment by Tooa** [comment] 2017-01-22 14:11
I can confirm this issue. There is no pointer in the scope of the button events :/

**Comment by yoavdamri** [comment] 2017-01-23 06:46
@Tooa, I saw it, in this case i can pass null (since the pointer is not relevant) or the translation x, y.
what do you think?

**Comment by Tooa** [comment] 2017-01-25 20:30
Thanks for reporting this issue. Fixed by @CapitanMorgan with https://github.com/almende/vis/pull/2615

**Closed by Tooa** 2017-01-25 20:30 UTC
Labels: Confirmed Bug, Fixed awaiting release, Network, PRIORITY
