### ISSUE TITLE
Graphs moving away from each other

### ISSUE THREAD

**Issue by ivangfr** [almende/vis#576] opened 2015-01-16 17:33 UTC
Hi, I have the following problem that you can see here: http://jsfiddle.net/jhzd9xcf/

As you can see, the graphs start to move away from each other and never stop, unless we do a zoom out.

How can I fix it?

Thanks

**Comment by AlexDM0** [comment] 2015-01-16 17:46
Hi,

You could try increasing the central gravity? I can't see them moving on my phone now but I can check on a pc on Monday. Try turning on the configure physics and play around a little. 

The hierarchical physics setting is not designed for multiple unconnected networks so you could also put invisible edges in between the two groups. 

Finally I see you gave everything a level manually. That's great :) it occurred to me that the level delegation system is expecting a connected network. 

Regards,

Alex

**Comment by ivangfr** [comment] 2015-01-16 19:24
Now testing on my notebook (MAC OS X, Chrome browser) I don't have the same problem that I had on my PC at work (Window7, Chrome browser).
I'll try the things that you suggested and I tell something in the next days.
Thanks

**Comment by AlexDM0** [comment] 2015-01-16 19:29
Hi,

I checked on my pc just now. You're right. iOS just did differently. I also tried the gravity, very small value like 0.08 suffices. But please play around to see what you like best. 

Regards,

Alex

**Comment by ivangfr** [comment] 2015-01-17 19:54
Hi Alex,

It works if I use centralGravity property of the hierarchicalRepulsion with the value that you suggested!
The graphs don’t move away from each other anymore when the network is loaded.

However I have another problem.
Try the following example and click on the button “Find es000001”.
Here is the link: http://jsfiddle.net/jhzd9xcf/1/

After locating the node, the graph starts moving to the right. I tried already, and it happens on Windows and Mac.

Thanks!

**Comment by AlexDM0** [comment] 2015-01-17 22:19
Hi Ivan,

That is an interesting case. The reason for this is that the minimum velocity required to be stable is dependent on the zoom level. The network stabilizes (long detailed discussion on it here: #344) for the initial zoom level and everything is fine. Then, the animation starts. The animation uses the normal simulation-draw loop the normal system uses but it forces to 'continue simulation and rendering' for the duration of the animation. Finally, we are at a zoom level where the network is not really stabilized! Thus the movement.

So now, is this a bug yes or no... the reason this happens is by design. The unfortunate collections of events shows this in a negative sense. An obvious question would be: "why not have it REALLY stabilize, regardless of zoom level?". Well, performance. You really don't need it stable to the pixel level if you're zooming so far out!

So another solution to this case: freeze the simulation as you zoom in. Well no, in general you don't want to only zoom in if everything is frozen. It can be kind of fun to have it work on a moving node! Besides, It'd look weird if you;d have a moving graph that was still settling and everything froze because you click a button.

You could lock all nodes in place when everything is stabilized. There are multiple issues about this, most notably this one #458 where we also link to the others.

What do you think would be a good solution? 

Regards,

Alex

**Comment by ivangfr** [comment] 2015-01-18 23:58
Hi Alex,

I’ve been playing with vis.js during the last few days so I’m not the best person to suggest a solution :)

Nowadays, what I exactly need to do is to draw the informations of a power grid in a hierarchical graph. With vis.js I easily did it in a couple of minutes. However, I faced the issues that I mentioned before.

Well, for me, a good solution would be, once the network is stabilized, I can call “focusOnNode” and the graphs don’t start moving again.

The function “focusOnNode” should just move "screen" to the node location, in the same way that I can find, zoom in or out the node manually. If I do it on my example, using the mouse or navigation buttons, i can find “es000001” manually and the graphs stay fixed.

But I don’t know the code details and its complexity so it’s just a suggestion.

Thanks.

**Comment by AlexDM0** [comment] 2015-01-19 12:55
Hi Ivan,

I have decoubled the animation from the physics. I have pushed the fix to develop.

Cheers!

**Closed by AlexDM0** 2015-01-19 12:55 UTC
Labels: Network, question
