### ISSUE TITLE
Numeric range for the x-axis

### ISSUE THREAD

**Issue by audy** [almende/vis#92] opened 2014-04-16 17:17 UTC
Is it possible to create a Timeline with a plain numeric range for the x-axis?

**Comment by AlexDM0** [comment] 2015-01-09 14:18
Hi,

Over the last year a lot of feature requests have been made. We have just introduced our new website which has a list of the requested features. We have placed this request on that list. 

The list can be found here:
http://visjs.org/featureRequests.html

An explaination of the new system can be found here:
http://visjs.org/blog.html#New\ website\ for\ vis\.js\!

I would like to stress that this does not mean we abandon this request. Discussion here will continue if needed on this feature but we will close it to keep our Github issue page more of a bug-todo list.

Future feature requests will still be made here and then added to the website by us.

Regards,

Alex

**Comment by Jayomat** [comment] 2015-11-03 14:40
Hi,
the doc say "Date or number or string or Moment". Does that imply we can use "arbitrary" numbers as start/end now or is number just another expression for time in ms?

**Comment by josdejong** [comment] 2015-11-03 21:31
number as date expects a unix timestamp in milliseconds, like `1446586258426` (i.e. `new Date().getTime()`).

**Comment by mojoaxel** [comment] 2016-10-24 11:00
This is propably a duplicate of #455 and should be fixed together.

**Comment by mojoaxel** [comment] 2016-10-24 11:00
Reopening as Feature-Request issue (see #2114). 
Everybody: Please feel free to implement this!

**Comment by sawatsky** [comment] 2016-10-26 16:03
This would be highly helpful! I'm currently providing arbitrary DateTime data, hiding the x-axis with CSS, and using labels to represent a new x-axis. This feature would save me so much hassle!

**Comment by yotamberk** [comment] 2016-10-26 16:28
Hi @sawatsky , are you able to pick up this feature?

**Comment by sawatsky** [comment] 2016-10-26 16:38
@yotamberk I'd love to if I had the time. Unfortunately, I am completely swamped with work! I'm the only frontend developer working on a new project for network simulations.

**Comment by yotamberk** [comment] 2016-12-08 10:51
@sawatsky & @audy  I've managed to accomplish this with the current `develop` branch using the `options.format` with the next function:
``` javascript
var options = {
    start: new Date(0),
    end: new Date(100),
    min: new Date(0),
    format: {
      minorLabels: function(date, scale, step) {
        switch (scale) {
          case 'millisecond':
            return new Date(date).getTime() + "ms";
          case 'second':
            var seconds = Math.round(new Date(date).getTime() / 1000);
            return seconds + "s";
          case 'minute':
            var minutes = Math.round(new Date(date).getTime() / 1000 * 60);
            return minutes + "m";
         ............................ and so on ..........................
      }
    }
  };
```
You can change how the label will be presented. The above is a simple example.

I'm closing this issue. If this doesn't fulfill your needs, please reopen and elaborate what is missing.

**Closed by yotamberk** 2016-12-08 10:51 UTC
Labels: Feature-Request, Timeline

**Comment by mojoaxel** [comment] 2016-12-13 19:54
@yotamberk In the context of the timeline it might be enogh to just show numbers instead of dates. But in the graph-2D a real number-scale is still needed. See #455

**Comment by jcc10** [comment] 2018-08-05 17:12
Dear future people, since it was never clearly stated here is the solution:

---

In the options of the timeline set the following:

```
options = {
    format: {
      minorLabels: function(date,scale,step) {
        // must have a space otherwise it will get mad.
        return new Date(date).getTime() + "";
      },
      majorLabels: function(date,scale,step) {
        // must have a space otherwise it will get mad.
        return new Date(date).getTime() + "";
      }
    },
    timeAxis:{scale:'millisecond'}
}
```

Then each timeline item can be like so:

`{id: 4, content: 'item 4', start: 16, end: 19}`

---

You are welcome future people. (probably future me.)

... This should really get it's own example.

**Comment by GaneshNimkar** [comment] 2019-02-28 06:03
> Not yet. We are about to implement a line chart in the timeline though, having an horizontal a time axis and a vertical number axis. When we do that, it is a little step to just support two types of axis (Dates and Numbers), and support them both horizontally and vertically.

Has this feature implemented, I have the same requirement  of plain numeric series on x-axis

**Comment by GaneshNimkar** [comment] 2019-02-28 08:43
> ```js
> var options = {
>     start: new Date(0),
>     end: new Date(100),
>     min: new Date(0),
>     format: {
>       minorLabels: function(date, scale, step) {
>         switch (scale) {
>           case 'millisecond':
>             return new Date(date).getTime() + "ms";
>           case 'second':
>             var seconds = Math.round(new Date(date).getTime() / 1000);
>             return seconds + "s";
>           case 'minute':
>             var minutes = Math.round(new Date(date).getTime() / 1000 * 60);
>             return minutes + "m";
>          ............................ and so on ..........................
>       }
>     }
>   };
> ```

Thank you so much this code solve my biggest problem... 

:)
