### ISSUE TITLE
feature request for svg export of network

### ISSUE THREAD

**Issue by brinrosenthal** [almende/vis#2009] opened 2016-08-10 00:20 UTC
Hi there, we love vis.js, and use it all the time for network visualization.  We would love to be able to export a static svg from the canvas, so we have access to high quality images for use in publications.  Right now we are just taking screenshots, which results in grainy text when zooming in.  We tried using svg crowbar, but found out that it is not compatible with vis.js format (http://nytimes.github.io/svg-crowbar/).  Do you have any idea if it would be possible to make something with similar functionality for vis.js?  Thank you so much!!

**Comment by dragonzone** [comment] 2016-08-11 17:37
Duplicate of this: https://github.com/almende/vis/issues/1784

**Closed** 2016-08-11 21:27 UTC
Labels: duplicate, enhancement, Network, question
