### ISSUE TITLE
[Timeline] margin configuration option is "broken"

### ISSUE THREAD

**Issue by mvdam** [almende/vis#2626] opened 2017-01-24 09:10 UTC
When upgrading from v4.16.1 to v4.17.0 / v4.18.0 the margin configuration option seems to be "broken". Timeline items that were nicely aligned after each other are now pushed to a new row. See screenshots below;

At v4.16.1 it works fine!
<img width="353" alt="v4 16 1" src="https://cloud.githubusercontent.com/assets/21951794/22240652/592650c6-e21c-11e6-8729-a805441459c8.png">

When upgrading to v4.17.0 / v4.18.0 the layout is somewhat broken.
<img width="354" alt="v4 18 0" src="https://cloud.githubusercontent.com/assets/21951794/22240653/59272adc-e21c-11e6-88c1-631a2ab544c1.png">

We use the following configuration for "margin".

`margin: {
    axis: 5,
    item : {
      vertical: 0,
      horizontal: 0
    }
}`

Although the margin options still work, you cannot use a value of `0` to prevent items from being pushed to a new row.

**Comment by yotamberk** [comment] 2017-01-24 09:11
Set the margin.vertical to -0.5

בתאריך 24 בינו׳ 2017 11:10 לפנה״צ,‏ "Martin van Dam" <
notifications@github.com> כתב:

**Comment by yotamberk** [comment] 2017-01-24 09:12
*margin.item.horizontal

בתאריך 24 בינו׳ 2017 11:11 לפנה״צ,‏ "Yotam Berkowitz" <yotamberk@gmail.com>
כתב:

**Comment by mvdam** [comment] 2017-01-24 09:33
Thank you, your solution works. Is it intended behaviour to use a negative value? Seems more like a hack to me?

**Comment by yotamberk** [comment] 2017-01-24 09:38
It is kind of a hack. There is a bug that i couldnt solve elegantly so in
the meantime this solves it

בתאריך 24 בינו׳ 2017 11:33 לפנה״צ,‏ "Martin van Dam" <
notifications@github.com> כתב:

**Comment by mojoaxel** [comment] 2017-01-27 13:20
> It is kind of a hack. There is a bug that i couldnt solve elegantly so in the meantime this solves it

@yotamberk Can you please refer to the issue number of that bug.

**Comment by mojoaxel** [comment] 2017-01-27 13:23
@mvdam By the way: You timeline looks realy nicely styled. Is there any chance that you could provide a public example with this style? A would realy like to add something like this to our [showcases](http://visjs.org/showcase/index.html) or our [examples](http://visjs.org/timeline_examples.html).

**Comment by yotamberk** [comment] 2017-01-27 15:34
duplicate of #2318 
@mojoaxel I remember referring to the PR that introduced this bug. I'll look for it again. I didn't have an elegant way of solving it so I left it as is at the time...

**Comment by yotamberk** [comment] 2017-01-27 15:38
found it: #2107

**Comment by mojoaxel** [comment] 2017-01-29 14:58
@mvdam See https://github.com/almende/vis/issues/2318#issuecomment-262521973
closing as duplicate of #2318

**Closed by mojoaxel** 2017-01-29 14:58 UTC
Labels: Confirmed Bug, Duplicate, Timeline

**Comment by mvdam** [comment] 2017-01-31 08:47
@mojoaxel Unfortunately I can't give you a live example of our timeline. However if you wish I can create lookalike for the examples page?

**Comment by mojoaxel** [comment] 2017-01-31 10:18
> Unfortunately I can't give you a live example of our timeline. However if you wish I can create lookalike for the examples page?

@mvdam That would be amazing! At the moment almost all Timelines look the same. If you can com up with a nice styled example I'm more than happy to add it to our examples or showcases.
