### ISSUE TITLE
Multiple lines and surfaces in Graph3d

### ISSUE THREAD

**Issue by nithingit** [almende/vis#1005] opened 2015-06-22 05:21 UTC
Is there a way to create groups in graph3d? .

I saw an example of creating groups in graph2d (barssidebysidegroups). I was wondering whether the same could be implemented in bargraph generated using graph3d?

**Comment by josdejong** [comment] 2015-07-08 07:37
Sorry for the late reply. Graph3d does not have support for groups, and you can only draw a single surface.

**Comment by zhulik** [comment] 2015-08-18 17:33
It is sad to hear it, i looking for ability to draw multiple 3d lines. Is it possible without groups?

**Comment by josdejong** [comment] 2015-08-19 20:38
No, this isn't supported right now. 

Shall I put this as a feature request?...

**Comment by zhulik** [comment] 2015-08-20 07:49
I think, i am not alone in my desire to draw multiple 3d lines. Please, create feature request. Thanks!

**Comment by josdejong** [comment] 2015-08-21 07:18
I've marked this issue as "enhancement", and changed the title to better reflect the feature request.

**Comment by shahimclt** [comment] 2016-02-26 18:25
Yup. I would like to see that too..

**Comment by mojoaxel** [comment] 2016-10-24 11:32
duplicate of #524

**Closed by mojoaxel** 2016-10-24 11:32 UTC
Labels: Feature-Request, Graph3D
