### ISSUE TITLE
Set background or watermark on canvas

### ISSUE THREAD

**Issue by jmgarciamari** [almende/vis#1397] opened 2015-10-26 21:07 UTC
I'm asking if is possible to set a backgroudn or watermark on canvas, I'm using dot network, Thanks

**Comment by Tooa** [comment] 2015-10-27 14:56
Hi,
take a look at the provided examples [1]. Looks like this is what you are searching for. 

Best Uli

[1] http://visjs.org/examples/network/events/renderEvents.html

**Comment by dragonzone** [comment] 2015-10-29 13:53
Take a look at this: http://jsfiddle.net/2xc45on2/

**Comment by jmgarciamari** [comment] 2015-10-29 17:51
mmmm css solution doesn't help me because I want that if I right click on image and click download, download with watermark, and css solution doesnt works, and the first solution, Throws error when I try to getContext 2d of div. Sorry for my english.

**Comment by Tooa** [comment] 2015-10-29 17:53
We need code and the exact error message to help you. Could you please provide a jsfiddle?

**Comment by jmgarciamari** [comment] 2015-10-29 19:43
I need to draw an image, maybe onload time is a problem, here is my code:

```javascript

    var canvas;
    var image = new Image();

    image.onload = function() {
      console.log('image loaded');
      canvas = new Vis.Network(container, data, options);

      canvas.on("beforeDrawing", function(ctx) {
        console.log('beforeDrawing');
          ctx.drawImage(image, 0, 0);
        });
      }
    image.src = 'img/logo_trans.png';

```
Only image loaded is fired, beforeDrawing event is not fired, network is drawed but not image

**Comment by dragonzone** [comment] 2015-10-30 13:57
This example show you how to use the beforeDrawing Event. http://jsfiddle.net/t5cw2cn0/

**Comment by jmgarciamari** [comment] 2015-10-30 17:33
I forgot to mention that I'm using ReactJS, I think that is why Vis events doesn't work.

**Comment by AlexDM0** [comment] 2015-11-02 09:57
In that case I think it's a scoping issue, not a vis issue. Dragonzone has shown exactly what you need to do to have it working in vis.

I'll close this issue. If you can show that the problem is with vis we can help you further.

Regards

**Comment by jmgarciamari** [comment] 2015-11-11 19:48
I've upgraded all my pm packages and now it works, I can draw a watermark, but If i put coordinates 0,0 on drawImage begin to draw in de center of the image, can I drawImage beginning on top left position of canvas?

**Comment by josdejong** [comment] 2015-11-12 10:06
How about subtracting half of the canvas width and height from the coordinates (0,0) ?

**Closed** 2015-12-23 13:35 UTC
Labels: Network, question

**Comment by luchex** [comment] 2016-01-21 12:55
ohh thanks for your reply.
but if you want the background to move, for example using a plane of my house
then I need to move my background
you can do that?

**Comment by josdejong** [comment] 2016-01-26 08:49
yes you can do that. There are methods like `getScale` and getViewPosition to figure out where you should draw your background to keep it positioned relative to the origin and taking into account the current scale.

**Comment by esh-cherukuri** [comment] 2016-03-17 23:25
Hi,

I am having the same issue with background image. i need functionality like this http://jsfiddle.net/t5cw2cn0/

In my view i can see the background when i don't load the nodes, if i load the nodes i can see the nodes but not the background image. Please suggest me where i am wrong.
I am using angular.js custom directive to load visjs network.

Thanks.

**Comment by AlexDM0** [comment] 2016-03-18 07:02
Your fiddle works. I can't see the issue.

**Comment by esh-cherukuri** [comment] 2016-03-18 07:35
That fiddle is working. but, In my working application view i can see the background when i don't load the nodes, if i load the nodes i can see the nodes but not the background image. Please suggest me where i am wrong.
I am using angular.js custom directive to load vis network.

Thanks.

**Comment by AlexDM0** [comment] 2016-03-18 07:39
Without seeing it going wrong we can't help you. If I were to guess, the error could be in all things you do differently than the example so that's not useful.

**Comment by esh-cherukuri** [comment] 2016-03-18 09:47
Hi,

I had created a jsfiddle http://jsfiddle.net/eshch/vedv32uj/4/ with my code.

The background image is loading when i click on Run button of jsfiddle, but if you refresh the browser background image is not loading until you click on any where on the network. try clicking on reload button of chrome browser you will see the changes.

Thanks.

**Comment by AlexDM0** [comment] 2016-03-18 10:09
I see, basically the image has not loaded before the network stabilizes and stops redrawing. You can preload the image to get around this or schedule a setTimeout with the redraw method once the image has loaded. 

Regards

**Comment by esh-cherukuri** [comment] 2016-03-23 18:08
Thank you so much for you help i can able to load image properly now. i am having some other issue where if i move node positions and click on zoomExtend icon the background image is moving, i need the background image to be fixed and when there is window resize the background image has to be resized and positioned according to that.

Here is the fiddle link: http://jsfiddle.net/eshch/vedv32uj/23/

To reproduce the problem, keep moving nodes to some other locations and click on zoomExtend icon. you can notice the background image moving.

Thanks,
Rajesh.

**Comment by AlexDM0** [comment] 2016-03-23 18:10
Well yea you position it in a fixed canvas position. If you move the canvas it will change. You'll need to get new coordinates every time you redraw based on Dom coordinates. We have a method for that called DomToCanvas.

**Comment by esh-cherukuri** [comment] 2016-03-23 18:33
If you don't mine can you tell me how can i get the new coordinates of Dom.

Thanks.

**Comment by AlexDM0** [comment] 2016-03-23 20:29
The DOM stays constant. It's relative to the div containing the network. So you could take the DOM coordinates of 200,200 if your div is 400x400px. 

Regards

**Comment by esh-cherukuri** [comment] 2016-03-24 07:16
Its not working, the background image is still moving here is the updated fiddle http://jsfiddle.net/eshch/vedv32uj/24/. if i use dynamic x,y values to draw an image then the image is not moving with network when we press up,down,left,right buttons.

If we give static values for x,y like ctx.drawImage(imageb, -200, -250); then the background image is moving when we press up,down,left,right buttons.

**Comment by AlexDM0** [comment] 2016-03-24 07:31
I see. I assumed you wanted it absolutely fixed. In that case you'll have to determine when you want to move it and when you don't. Either bind another listener to the fit button or distill it from the scale of the network. 

Regards

**Comment by esh-cherukuri** [comment] 2016-03-24 07:34
can you provide me any sample code or if you can update that fiddle that will be grateful to me. Thanks for your prompt responses.

**Comment by AlexDM0** [comment] 2016-03-24 07:43
I'm not sure what the goal is. If you only want the image to stay on a window resize and not on a move of the canvas listen to the resize event. Or dynamically calculate the position and size based on the scale and / or window size.

**Comment by esh-cherukuri** [comment] 2016-03-24 07:52
The goal is : The background image should be always aligned center to the network .when we move the nodes positions and we click on zoomExtend button the background image has to fit center to that network. 
If the window is resized nodes has to be fitted in that network and image has to be resized according to that window and canvas size.
When we zoom in or zoom out and when ever we press up,down,left,right buttons the background image has to be moved along with network.

**Comment by AlexDM0** [comment] 2016-03-24 08:03
What is the center of the network? The center of all node positions or 0,0?

You can listen to the fit event (not in docs, we can add it) and the resize event to change your position settings. The rest should be done by the canvas. 

I don't have time to write the code but it should be quite straightforward. 

Regards

**Comment by esh-cherukuri** [comment] 2016-03-24 17:31
I think currently the center of network is center of all nodes. How can i make center at 0,0 for network?

I understood now, If you can  add that fit event in docs i will start working on that.

Thanks.

**Comment by AlexDM0** [comment] 2016-03-24 18:03
The center of the network is arbitrary, as is 0,0. The central Gravity is directed to 0,0 but we cannot change the center coordinates. Imagine a piece of paper with a camera above it. What you see in the div is what that camera sees. 0,0 is a fixed point on the paper but the camera can be above a different point.

**Comment by esh-cherukuri** [comment] 2016-03-24 18:17
Ok got it. can you send me doc for fit event.

**Comment by AlexDM0** [comment] 2016-03-24 18:18
network.on("fit", callback)

**Comment by esh-cherukuri** [comment] 2016-03-24 19:06
ok cool.Thank you.
