### ISSUE TITLE
unable to scroll and zoom timeline when using in WebBrowser Control

### ISSUE THREAD

**Issue by matvdl** [almende/vis#1445] opened 2015-11-19 15:27 UTC
I am using your control in a hosted application that uses and WebBrowser control for IE.  Generally it works well, but I find that if I change the focus away from the control to another form within the hosted application or any other application, and return to your control later, I am no longer able to zoom, and scrolling becomes unreliable.

Interestingly I have found that if I drag and select your control, it will regain the focus and start to zoom again.  Scrolling still appears to work after returning to the page, but it's performance is markedly reduced and difficult to use.

I have confirmed that this only appears to occur in the WebBrowser Control, and when the same page is displayed in IE it has no problems.

I have the page set to IE9 compatibility and are operating on windows 8.1 on IE 11.
[tmpHTML27029055.txt](https://github.com/almende/vis/files/39082/tmpHTML27029055.txt)

**Comment by AlexDM0** [comment] 2015-11-19 15:57
This is... very little to go on. Which module do you use? We have no need for this very specific case I'm afraid. If you can pinpoint the cause so we can reproduce it we can check if we can fix the error.

Regards

**Comment by matvdl** [comment] 2015-11-19 16:21
We are using the timeline control,

I have better luck when I use buttons for the left/right/zoom functions, but it remains un-reliable.

When I step through the stepWindow function there are no errors generated that I can see, but I am not sure what else I can try at this time.

**Comment by oinkspoink** [comment] 2015-11-19 16:51
Personally, i don't think its a problem with the timeline. The WebBrowser control is known for some focus issues.

Maybe [this](http://stackoverflow.com/questions/19007341/webbrowser-control-focus) helps or try to set the focus back to the timeline manually.

**Comment by josdejong** [comment] 2015-11-30 12:50
@matvdl does the pointer that @oinkspoink gave you solve the issue?

**Comment by matvdl** [comment] 2015-11-30 13:41
I have looked into the issue further, but at this time have not been able to diagnose what is failing or fix the issue.  I have tried various setFocus options that were discussed in different posts without success.

I will keep searching and if I find something I will make sure I post the solution.

**Comment by josdejong** [comment] 2015-11-30 14:19
Ok thanks for your update. Shall we close the issue for now? I think there is nothing we can do in vis.js itself to fix this.

**Closed** 2016-10-17 22:06 UTC
Labels: question, Timeline
