### ISSUE TITLE
How to add non-draggable custom time?

### ISSUE THREAD

**Issue by dtslvr** [almende/vis#1698] opened 2016-02-29 07:35 UTC
Hi guys,

I’m rendering a deadline as a vertical bar with custom time. How can I add this custom time which can not be dragged by the user? 

Thanks in advance.
Thomas

**Comment by josdejong** [comment] 2016-02-29 09:42
Duplicate of #1296

**Closed by josdejong** 2016-02-29 09:42 UTC

**Comment by dtslvr** [comment] 2016-02-29 19:27
Thanks, I haven't found the other issue.
