### ISSUE TITLE
Timeline zoomable=false and mouse wheel does nothing

### ISSUE THREAD

**Issue by Rince7** [almende/vis#2331] opened 2016-11-18 15:39 UTC
So I have several timelines with groups on a page, all are not zoomable. 
When the mouse is over one of them the mouse wheel events are ignored. 
If the mouse is not over a timeline, or over the groups part of one, I can scroll with the mouse wheel.

**Comment by yotamberk** [comment] 2016-11-18 16:11
Duplicate of #2273. This was fixed for in #2301

**Closed by yotamberk** 2016-11-18 16:11 UTC
Labels: Bug, Duplicate, Timeline
