### ISSUE TITLE
Timeline Error after updating to 4.11.0 from 3.11.0

### ISSUE THREAD

**Issue by aquadisco** [almende/vis#1545] opened 2016-01-04 19:17 UTC
Updated visjs and am now getting "Uncaught Error: Invalid start "NaN" on vis.js:13579  i traced this back to a divide by zero issue but that could just be a symptom.  

My dataset only has 1 item.  In "Timeline.prototype.getItemRange = function () {..." on line 10525 interval (which in my case is 10 since my dataset min/max are equal) is divided by _this.props.center.width which evaluates to '0'.

If i revert back to 3.11.0, the error goes away.

**Comment by josdejong** [comment] 2016-01-04 19:47
Can you post your code, so we can see what's going wrong?

**Comment by nalinielkins** [comment] 2016-02-11 16:06
I am having the same problem using version 4.7.0.  The line number is: Line: 13952 in vis.js.

I have multiple items.  This code works fine in Chrome but not in IE11.

Is this problem fixed in a later version of vis.js?

**Comment by josdejong** [comment] 2016-02-12 08:05
> Is this problem fixed in a later version of vis.js?

... maybe just try if that's the case? ...

**Comment by nalinielkins** [comment] 2016-02-12 16:39
I have tried it on the latest version of vis.js and it does not work.  It only appears to work in Chrome.
I have attached the file.   I do not want to post on github as we develop software for a living and this is part of our code.
I wonder if it has something to do with the millisecond calculations. Thanks,
Nalini ElkinsInside Products, Inc.www.insidethestack.com(831) 659-8360

**Comment by josdejong** [comment] 2016-02-15 16:25
> I have attached the file.   I do not want to post on github as we develop software for a living and this is part of our code.

You're writing this in a public project issue on github. I don't see any attached file. 

A code example and/or description on what is going wrong would be useful. Note that there are breaking API changes between v3.11.0 and v4.11.0, so you will probably have to do some changes in your code before it works with v4.

**Comment by nalinielkins** [comment] 2016-02-17 15:46
Actually, the problem was my date formatting.  Once I fixed that, then everything works! Thanks,
Nalini ElkinsInside Products, Inc.www.insidethestack.com(831) 659-8360

**Comment by josdejong** [comment] 2016-02-17 16:03
ok great to hear it's solved now.

**Closed by josdejong** 2016-02-17 16:03 UTC
Labels: Timeline

**Comment by federicoco** [comment] 2016-11-25 12:39
Hello I know that this issue has been closed.
Happened to me and quickly found the solution :
It's not a bug ,it's a problem with your database.
If you set to NOT NULL the field which you'll associate to end field of Timeline Vis, and you'll leave it without inserting a date, your field will not contain null but 0000-00-00 00:00:00 (with DATE or DATETIME).

So, Vis.js reads 0000-00-00 00:00:00 , how it is going to display it and where ??
The fix is to make the date field to be null (so uncheck NOT NULL options in your database)
