### ISSUE TITLE
Phantom edges with clustering in 4.5.1

### ISSUE THREAD

**Issue by dragonzone** [almende/vis#1083] opened 2015-07-10 01:30 UTC
There is a new bug that was introduced in v4.4.0 but works fine in v.4.3.0. If I cluster two nodes together to make Cluster-1. Then I select Cluster-1 with another node to create Cluster-2, if I open that cluster, all the edges of Cluster-1 will go missing.

You can go here to check out my sample code: https://github.com/dragonzone/JsSamplerApp. Run jetty.bat and go to Link Analysis. The latest code point to your v4.4.0, which you will see the issue. However, if you revert the vis folder (only) to BEFORE my July 7th upgrade of v4.4.0, which will be v4.3.0. You will see that it run just fine.

**Comment by AlexDM0** [comment] 2015-07-10 08:15
Hi,

I'll look into it. For next time though, it's not feasible for me to look through your codebase for debugging. If you could make a small example in jsbin based on one of our examples for instance that would really speed things up. 

Thank you for reporting though!

Just to be clear, you form cluster "1" from 2 nodes, then form a cluster "2" from "1" and another node. Finally you open cluster "2"?

Regards

**Comment by dragonzone** [comment] 2015-07-10 09:25
Yes, that is correct. I knew it will be a little complicated for you to look into my code, therefore, I kinda explain to you in general what is wrong with it. Also, this is a kinda deep problem so re-writing will not be that simple. Sorry.

BTW, your phantom link issue seem to be resolve in v.4.4.0.

**Comment by dragonzone** [comment] 2015-07-10 09:41
I just realized this, but I am not sure by fixing to the phantom link (https://github.com/almende/vis/issues/1055#) problem may have cause this bug or not since it deal with clustering/declustering.

**Comment by AlexDM0** [comment] 2015-07-10 10:04
Hi, 

Yes I figured it was because of that. I have tested the code in a few cases, apparently this case is different.

I tried this: 
http://jsbin.com/fefupizoge/1/edit?html,output

How is it different from your case? Could you help me to reproduce it in that jsbin?

Regards

**Comment by dragonzone** [comment] 2015-07-10 10:40
I have modified your example by adding another link and delayed the timeout so you can see the diff. However, you have to click on "c2" to see the result.

http://jsbin.com/remuye/edit?html,output

**Comment by AlexDM0** [comment] 2015-07-10 12:20
Hi Dragonzone,

I've fixed this on develop. Thanks for helping track it down!

Regards

**Comment by dragonzone** [comment] 2015-07-10 12:25
Do you have an estimated date/time when the new release will be out? This affects what I am using on my project which we may go live soon. Thanks for quick response/fix!

**Comment by AlexDM0** [comment] 2015-07-10 12:26
Hi,

Probably next week, you could however copy the lines affected by the commit and rebuild it yourself if you need it quicker.

Regards

**Comment by AlexDM0** [comment] 2015-07-17 13:03
released in 4.5

**Comment by dragonzone** [comment] 2015-07-17 13:04
Alex,
I've just upgraded to v4.5.0, I notice the phantom link is coming back. But let me double-check.

**Comment by AlexDM0** [comment] 2015-07-17 13:05
Try control F5 for cache reload?

**Comment by dragonzone** [comment] 2015-07-17 13:06
Yea, it's still back, b/c I use Firebug to view the vis.js, it says v4.5.0. I'll try to create the example later for u.

**Comment by AlexDM0** [comment] 2015-07-17 13:08
Thats odd, the case you gave me is working..
http://jsbin.com/zoqininefe/edit?html,output

**Comment by dragonzone** [comment] 2015-07-17 13:09
It's 1 of the old phantom case, that's closed, but I can't to search it back.

**Comment by dragonzone** [comment] 2015-07-17 13:10
When you have two separate links, like:

a -> b -> c
x -> y -> z

Then you cluster, a + z = c1, c1 -> b, then you'll c the extra link.

**Comment by AlexDM0** [comment] 2015-07-17 13:12
you mean where it's stuck to nothing?

**Comment by AlexDM0** [comment] 2015-07-17 13:20
Hi Dragon,

Could you verify if this version works for you?
https://rawgit.com/almende/vis/develop/dist/vis.js

Its the vis.js from the dev branch.

I think I found the problem.

Regards

**Comment by dragonzone** [comment] 2015-07-17 13:26
Yes, that version works! The phantom link doesn't show up.

**Comment by AlexDM0** [comment] 2015-07-17 13:26
Ok great! I'll do a bugfix release monday

**Comment by dragonzone** [comment] 2015-07-17 13:27
Ok, I'll wait, Thanks! I'll test out some other issues to make sure they work also.

**Comment by dragonzone** [comment] 2015-07-17 13:45
BTW, I saw another issue, but it's minor. It deals with network.setOptions(), for layout. In the demo example you have, configuration.html, if you change to point to the vis.js dev. version you have:

<script src="https://rawgit.com/almende/vis/develop/dist/vis.js"></script>

If you toggle, Layout | Hierarchical, it will work. However, if you then uncheck, to go back to the default layout, it is stuck w/ the old layout. For now, I have to redraw the whole thing which is a workaround.

**Comment by dragonzone** [comment] 2015-07-17 13:58
There's still another bug w/ the cluster, here's the case

a - > b -> c -> d
w -> x -> y -> z

cluster b + x = c1, cluster d + z = c2, then cluster c1 + c2 = c3. If you open cluster c3, you'll broken link.

Sorry to report so many problems. I know it's hard.

**Comment by AlexDM0** [comment] 2015-07-17 14:01
Could you expand the example we had to show this? I fixed the hierarchical toggle on develop.

**Comment by dragonzone** [comment] 2015-07-17 14:35
Something is wrong w/ jsbin, I think some stuff is block from here. But I'll paste the whole page here, you can cut & paste into new file and run it locally. Note: once the 'c3' node is created, click on it and you will see. 

```
<!doctype html>
<html>
<head>
    <title>Network | Clustering</title>

    <script type="text/javascript" src="https://rawgit.com/almende/vis/develop/dist/vis.js"></script>


    <style type="text/css">
        #mynetwork {
            width: 600px;
            height: 600px;
            border: 1px solid lightgray;
        }

        p {
            max-width: 600px;
        }

        h4 {
            margin-bottom: 3px;
        }
    </style>
</head>

<body>



<div id="mynetwork"></div>

<script type="text/javascript">
    // create an array with nodes
    var nodes = [
        {id: 1, label: '1'},
        {id: 2, label: '2'},
        {id: 3, label: '3'},
        {id: 4, label: '4'},
        {id: 'a', label: 'a'},
        {id: 'b', label: 'b'},
        {id: 'c', label: 'c'},
        {id: 'd', label: 'd'}
    ];

    // create an array with edges
    var edges = [
        {from: '1', to: '2', arrows:'to'},
        {from: '2', to: '3', arrows:'to'},
        {from: '3', to: '4', arrows:'to'},
        {from: 'a', to: 'b', arrows:'to'},
        {from: 'b', to: 'c', arrows:'to'},
        {from: 'c', to: 'd', arrows:'to'}
    ];

    // create a network
    var container = document.getElementById('mynetwork');
    var data = {
        nodes: nodes,
        edges: edges
    };
    var options = {layout: {randomSeed: 8}};
    var network = new vis.Network(container, data, options);

    // if we click on a node, we want to open it up!
    network.on("selectNode", function (params) {
        if (params.nodes.length == 1) {
            if (network.isCluster(params.nodes[0]) == true) {
                network.openCluster(params.nodes[0])
            }
        }
    });

	setTimeout(function() {
	alert("Clustering 1 and 'a'");
	var clusterOptionsByData = {
		joinCondition: function(node) {
			if (node.id == '1' || node.id == 'a') 
				return true;
			return false;
		},
		clusterNodeProperties: {id:"c1", label:'c1'}
	}
	network.cluster(clusterOptionsByData);
	}, 1000)

	setTimeout(function() {
	alert("Clustering 3 and 'c'");
	var clusterOptionsByData = {
		joinCondition: function(node) {
			if (node.id == '3' || node.id == 'c') 
				return true;
			return false;
		},
		clusterNodeProperties: {id:"c2", label:'c2'}
	}
	network.cluster(clusterOptionsByData);
	}, 5000)


	setTimeout(function() {
	alert("Clustering c1 and c2");
	var clusterOptionsByData = {
		joinCondition: function(node) {
			if (node.id == 'c1' || node.id == 'c2') 
				return true;
			return false;
		},
		clusterNodeProperties: {id:"c3", label:'c3'}
	}
	network.cluster(clusterOptionsByData);
	}, 10000)

</script>

</body>
</html>
```

**Comment by AlexDM0** [comment] 2015-07-17 15:04
Hi Dragon,

I've pushed another fix to develop. This time I think we have a winner :). Could you test it?

Regards

**Comment by dragonzone** [comment] 2015-07-17 15:09
Can you give me the url or same one to the vis.js?

**Comment by dragonzone** [comment] 2015-07-17 15:10
Seems to work, thx!

**Comment by AlexDM0** [comment] 2015-07-17 15:27
Great, I'll wait till monday for a bugfix release. Let me know if you find any more issues.

Regards

**Comment by AlexDM0** [comment] 2015-07-20 15:08
added in 4.5.1

**Closed by AlexDM0** 2015-07-20 15:08 UTC
Labels: bug, Fixed awaiting release, Network
