### ISSUE TITLE
[Timeline] Long holding left-mouse click isn't recognized

### ISSUE THREAD

**Issue by larisahax** [almende/vis#3668] opened 2017-11-17 18:07 UTC
E.g. here
http://visjs.org/examples/timeline/editing/editingItemsCallbacks.html

Suppose you want to move some item. 
a) 1) You click on item and select it.
    2) You again click on item and hold mouse down for 2 sec
    3) Start to move mouse -> item doesn't move

Moving item works correct only in next situations:
b) 1) You hold mouse down on unselected item (so you skip first step from (a))
    2) Then start to move mouse, doesn't matter how long you wait, it works

c) 1) You click on item and select it.
    2) You again click on item and start to move mouse immediately, it works (step 2) from (a) must be very short)

**Comment by yotamberk** [comment] 2017-11-18 21:34
duplicate of #2098

**Closed by yotamberk** 2017-11-18 21:34 UTC
Labels: Duplicate, Problem, Timeline
