### ISSUE TITLE
Vis.js crashes browser due to long word in node with widthConstraint (network)

### ISSUE THREAD

**Issue by wjureczka** [almende/vis#3001] opened 2017-04-20 10:08 UTC
Hello Everyone!
 Recently I have encountered big problem in my project connected with VIS NETWORK. The problem is that vis.js crashes web browser if the node's label has one long word, which its width is bigger than the widthConstraint of the node. Browser/Tab completely freezes for a few minutes and there is no way to  make the Tab/Browser working again. Please add feature that cut such long words in proper place and add the new line (\n or \r) signs in to prevent this behaviour of such useful library as vis is.
Cheers,
Wojtek

**Comment by wimrijnders** [comment] 2017-04-20 16:11
Duplicate of #2953.

Fix is pending for next release.

**Closed** 2017-04-20 16:11 UTC
Labels: Duplicate, Network, Problem
