### ISSUE TITLE
Hierarchical network exploding

### ISSUE THREAD

**Issue by Menighin** [almende/vis#1735] opened 2016-03-17 12:19 UTC
Hi there,

Im having an issue representating an hierarchical network in which there is some nodes with a lot of edges. The graph simply explodes, stretching itself to a thin grey line in my screen and then its physics starts to pull it back together. Is there any configuration or anything I could do to make it better?

I made a [JSFiddle](http://jsfiddle.net/rehcnz1w/) with an example. You can't really see anything there, but if you remove some edges (actually quite a lot) you can see how the graph should look like.

One interesting thing is this specific scenario use to build right in the version 4.14.0 but now in 4.15.1 it explodes. Simply keeping using the 4.14.0 version won't solve my problem because there is another scenarios in which the 4.14.0 version doesn't work but the 4.15.1 does.

Thanks in advance.

**Comment by MartinUbl** [comment] 2016-04-04 09:53
Hi, I'm experiencing the same issue in my project - hierarchical layout with bigger amount of edges, additionally user-defined node levels (i need to be sure, that specific nodes are on level 0), explodes to one thin line.

I tried messing with various settings, but without any result. I can reproduce this issue on 4.11.0 and higher. Reverting my project to use 4.10.0 is not possible due to need of having 4.11+ features.

Thank you.

**Comment by albertolacework** [comment] 2016-05-10 00:20
#1804 #1813 I've narrowed it down to the algorithm for getBranchBoundary being completely bonkers. As an aside commenting out this._generateMap() fixed this issue but obviously doesn't split the trees so its kinda messy.

**Comment by wimrijnders** [comment] 2017-04-26 07:09
There are quite a few issues reporting this problem. I'm using current issue as the central location for addressing it.

For other duplicates, see the issues referencing current in this list.

**Comment by wimrijnders** [comment] 2017-04-26 08:08
**Notes on this issue**
*for future reference*

- There is a critical limit for number of nodes; network looks ok, adding just one node makes it explode.
- Apparently, issue resolved indirectly for `layout.hierarchical.sortMethod: 'hubsize'`
- Removing following lines fixes the issue in one case:

`LayoutEngine.js`:

```
  _placeNodesByHierarchy(distribution) {
...   
          if (this.positionedNodes[node.id] === undefined) {
...
            if (handledNodeCount > 0) {pos = this._getPositionForHierarchy(nodeArray[i-1]) + this.options.hierarchical.nodeSpacing;}    // <== REMOVE
            this._setPositionForHierarchy(node, pos, level);
            this._validataPositionAndContinue(node, level, pos);  // <== REMOVE
...
          }
...
  }
```

- In one (old) issue, the following option combinations produced better results:
```
options.layout.hierarchical.edgeMinimization = false;
options.layout.hierarchical.blockShifting = true;

options.layout.hierarchical.edgeMinimization = false;
options.layout.hierarchical.blockShifting = false;
```

**Comment by wimrijnders** [comment] 2017-04-27 10:36
The problem is in method `LayoutEngine._validatePositionAndContinue()`. By the looks of it, the method assumes a strict hierarchy, in which child nodes have only one parent.

By disabling the method, a decent network is shown for multiple parents as well, like image above.

**Comment by wimrijnders** [comment] 2017-04-28 13:07
I am working on a solution; however, I have come to realize that `layout.hierarchical.sortMethod: 'hubsize'` suffers from the same/similar problem. Till now, I thought the problem was limited to `directed` only.

I'll try to add a fix for `hubsize` as well before submitting the PR.

**Closed** 2017-05-21 19:19 UTC
Labels: Confirmed Bug, Fixed awaiting release, Network
