### ISSUE TITLE
Network: node Dataset update redraw network with wrong position

### ISSUE THREAD

**Issue by andry85mae** [almende/vis#3588] opened 2017-10-18 07:32 UTC
Hello

when use the network with `neighbourhoodHighlight` function when click inside the svg, the network is redraw with node in new position.
I have build a network with the possibility to drag a node in specific position ( controlled by the user) but when click inside the svg the position change.
I already prove to set the fixed options for nodes (change when drag start and drag end) and with `physic :false` (but there is a bug that not allow to use this configuration) without result.
This is my network configuration:

```js
let options: vis.Options = {
              nodes: {
                  shape: 'dot',
                  scaling: {
                      min: 10,
                      max: 30,
                      label: {
                          enabled: false,
                          min: 1,
                          max: 130,
                          drawThreshold: 1,
                          maxVisible: 130
                      }
                  },
                  font: {
                      size: 12,
                      face: 'Tahoma'
                  }
              },
              edges: {
                  width: 0.15,
                  color: { inherit: 'from' },
                  smooth: {
                      enabled: true,
                      type: 'continuous',
                      roundness: 0,
                  }
              }
              ,
         physics: {
              enabled: false,
              minVelocity: 0.75,
              stabilization: false
          },
              interaction: {
                  tooltipDelay: 200,
                  hideEdgesOnDrag: true
              }
          };`
```
the `neighbourhoodHighlight` is the same of the example.
Thanks

**Comment by wimrijnders** [comment] 2017-10-18 08:10
Could it be that the nodes in your `DataSet` contain initial coordinates? In that case, if you do an update via `DataSet`, these initial coordinates get reset.

I'm not saying that this is desirable behaviour, it's just the way it works right now.

**Comment by andry85mae** [comment] 2017-10-18 08:21
Yes.
The `Dataset` contain initial coordinates provide by a database.
Then when i move the node i want that the new position remain when i update the dataset.
Thare are some solution for this ?

Thanks

**Comment by wimrijnders** [comment] 2017-10-18 08:29
Yes. Two strategies:

- Update the coordinates in the `DataSet` to whatever they are 'now'
- Remove the initial coordinates from the `DataSet` so that they don't get updated

The second option is the easiest, [here is a way to do it](https://github.com/almende/vis/issues/3096#issuecomment-305518575).

HTH

**Comment by wimrijnders** [comment] 2017-10-18 08:29
Duplicate of #3096.

**Comment by andry85mae** [comment] 2017-10-18 08:45
thanks it works !

**Comment by wimrijnders** [comment] 2017-10-18 08:50
Great! If you're happy with the outcome, please close the issue.

**Closed** 2017-10-18 08:52 UTC
Labels: Duplicate, Network, Problem
