### ISSUE TITLE
timeline: setSelection doesn't focus item when having vertical scroll

### ISSUE THREAD

**Issue by jmunozvalencia** [almende/vis#1846] opened 2016-05-11 15:59 UTC
Hi, I have found a workaround to add vertical scroll into the timeline. However, the setSelection method doesn't consider the scroll and it is hard to find the selected node in some scenarios.
It will be good to support this feature right out of the box. 
I have created a simple demo in order to reproduce the issue: http://jsfiddle.net/jmunozvalencia/n56mw9nu/
(If you press select, the item 62 is focused just in the horizontal scroll, you need to scroll down if you want to see it).
Thanks,
Jose

**Comment by renancastro** [comment] 2016-09-18 00:26
It is the same as issue #617

**Comment by mojoaxel** [comment] 2016-09-19 07:14
duplicate of #617

**Closed by mojoaxel** 2016-09-19 07:14 UTC
Labels: duplicate, question, Timeline
