### ISSUE TITLE
Bizarre scale change on network examples, as well as some webpages

### ISSUE THREAD

**Issue by joaobarcia** [almende/vis#1255] opened 2015-09-01 10:52 UTC
Hi,

I'm getting a strange scale change on the network examples as well as some of the webpages listing the examples. The pages load normally, but randomly start zooming in or out:
- On the network examples the network zooms either in or out when I click/drag the mouse on top of the canvas. It it is always "zoom in" or "zoom out" depending on the instance
- Stranger than that, the same thing happens to the pictures on the example list page, they start normal but after a few seconds they keep changing scale until being extremely big/small (screenshots attached)
![screenshot from 2015-09-01 11 29 51](https://cloud.githubusercontent.com/assets/6717014/9602256/d4d9bb88-509e-11e5-82cc-ddba21ced6c4.png)
![screenshot from 2015-09-01 11 40 19](https://cloud.githubusercontent.com/assets/6717014/9602255/d4d8c37c-509e-11e5-8b18-94e448cc6981.png)

I have an Ubuntu 15.04 machine and tested both on Firefox and Chromium with add ons disabled. No other page/js library on my computer do this.

For the networks it happens consistenly, 100% of the times and as soon as I click/drag the mouse. For the webpages it seems to happen like 30% of the times and without any interaction.

I have not been able to replicate it on another Windows 7 machine I have here.

Other modules besides the network do not display the issue (although their examples page do..).

The "showcase" examples do not display the issue.

**Comment by AlexDM0** [comment] 2015-09-01 12:12
Hi,

That.... is really strange. I cannot reproduce it, nor do I have any idea what could be doing it as zooming in the examples page is explicitly disabled... Is the canvas itself changing size as well?

Regards

**Comment by dragonzone** [comment] 2015-09-01 12:37
I have this similar issue in our app, when the network initially loads with v4.8. Somehow, on initial load, it zooms in really close. However, to workaround, I called network.fit(), which resets the zoom.

**Comment by AlexDM0** [comment] 2015-09-01 12:39
This sounds like a different issue dragon, that could be due to kamada kawai not working with the network. I'll look into that.

**Comment by joaobarcia** [comment] 2015-09-01 12:59
The canvas is not changing size.

I am able to reproduce it as well with Chrome on a Macbook running OS X. Exact same symptoms.

Let me know if there is any log or similar I can do. If useful I can screengrab a video.

**Comment by tolleiv** [comment] 2015-09-02 18:50
Hi 
+1 same behaviour on Safari, Chrome and Firefox running on Mac OSX. 

The bad thing is that this even happens with "zoomView" set to "false" whenever you click into the canvas.

Fixing this.
Cheers

**Comment by onexerxes** [comment] 2015-09-02 20:59
Not sure if this is related, but I see extreme zoom-out happening when I click on the Network, but *only* on smaller screen resolutions. For example, on this demo page:

http://visjs.org/examples/network/nodeStyles/shadows.html

With Chrome and 24in monitor, clicking does not cause the bizarre scale change.

But when I turn on Chrome Dev tools and use a smaller screen (ex: Apple Ipad), clicking on the Network zooms way out.

Before clicking:
![image](https://cloud.githubusercontent.com/assets/5999392/9644199/db69ac24-5193-11e5-856b-5c09042de9f1.png)

After clicking:
![image](https://cloud.githubusercontent.com/assets/5999392/9644222/f21a2728-5193-11e5-8b30-65728cca753e.png)

Each additional click zooms out way more.

Can you reproduce this?

**Comment by AlexDM0** [comment] 2015-09-06 13:45
Hi,

This should be fixed on develop now. Thanks for reporting! We'll release a bugfix release this week.

Cheers

**Comment by joaobarcia** [comment] 2015-09-06 16:02
Great!

**Comment by AlexDM0** [comment] 2015-09-07 15:32
This has been fixed in 4.8.1

**Closed by AlexDM0** 2015-09-07 15:32 UTC
Labels: bug, Fixed awaiting release, Network

**Comment by onexerxes** [comment] 2015-09-08 13:52
Awesome! Thanks, Alex.
